import { FormEvent, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { searchAuditEvents } from '../../api/generated';
import type { AuditEvent } from '../../api/generated';
import { contentServiceClient } from '../../api/client/contentServiceClient';
import { unwrap } from '../../api/client/adminApi';
import { AsyncState } from '../../components/AsyncState';

export function AuditPage(){const[actor,setActor]=useState('');const[entityType,setEntityType]=useState('');const[action,setAction]=useState('');const[requestId,setRequestId]=useState('');const[filters,setFilters]=useState({actor:'',entityType:'',action:'',requestId:''});const[page,setPage]=useState(0);const query=useQuery({queryKey:['audit',filters,page],queryFn:()=>unwrap(searchAuditEvents({client:contentServiceClient,query:{...filters,page,size:25}}))});const submit=(event:FormEvent)=>{event.preventDefault();setPage(0);setFilters({actor,entityType,action,requestId});};return <><header className="page-header"><div><span className="eyebrow">Governance</span><h1>Audit log</h1><p>Immutable administrative changes in reverse chronological order.</p></div></header><form className="filters" aria-label="Audit filters" onSubmit={submit}><label>Actor<input value={actor} onChange={e=>setActor(e.target.value)}/></label><label>Entity type<select value={entityType} onChange={e=>setEntityType(e.target.value)}><option value="">All</option>{['Exam','ExamVersion','Source','LearningObjective','KnowledgeFact','Question','Release','Review','MockExamConfiguration'].map(v=><option key={v}>{v}</option>)}</select></label><label>Action<select value={action} onChange={e=>setAction(e.target.value)}><option value="">All</option>{['CREATE','UPDATE','ARCHIVE','APPROVE','REJECT','REQUIRES_UPDATE','SUBMIT','PUBLISH','DELIVER','ACTIVATE','RETIRE'].map(v=><option key={v}>{v}</option>)}</select></label><label>Request ID<input value={requestId} onChange={e=>setRequestId(e.target.value)}/></label><button type="submit">Apply filters</button></form><AsyncState loading={query.isPending} error={query.error}>{query.data?.items.length===0?<p className="card" role="status">No audit events match these filters.</p>:<div className="table-scroll"><table><caption className="sr-only">Administrative audit events</caption><thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Target</th><th>Details</th></tr></thead><tbody>{query.data?.items.map((item:AuditEvent)=><tr key={item.id}><td>{new Date(item.timestamp).toLocaleString()}</td><td>{item.actorName}<br/><small>{item.actorId}</small></td><td><span className="status-badge">{item.action}</span></td><td>{item.entityType}<br/><small>{item.entityId}</small></td><td><details><summary>View change</summary><p>Request: <code>{item.requestId}</code></p><h3>Previous</h3><pre className="json-preview">{JSON.stringify(item.previousState,null,2)}</pre><h3>New</h3><pre className="json-preview">{JSON.stringify(item.newState,null,2)}</pre></details></td></tr>)}</tbody></table></div>}</AsyncState>{query.data&&query.data.totalPages>1&&<nav className="pager" aria-label="Audit pages"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1} of {query.data.totalPages}</span><button disabled={page+1>=query.data.totalPages} onClick={()=>setPage(p=>p+1)}>Next</button></nav>}</>}
