import { Link } from 'react-router-dom';
import { checklists, concepts, glossary, supportedLearnerQuestionTypes } from './content';
import { ConceptSection } from './ConceptSection';
import { ContentFlowDiagram } from './ContentFlowDiagram';

const contents=[['overview','Overview'],['flow','The full content flow'],['concepts','Every concept'],['states','Review and lifecycle states'],['delivery','Release and learner delivery'],['sessions','Practice versus mock exams'],['services','Platform responsibilities'],['example','Complete worked example'],['mistakes','Common mistakes'],['checklists','Administrator checklists'],['glossary','Quick reference glossary']];
const example=['Exam — Swedish Citizenship','Exam Version — Swedish Citizenship 2026','Subject — Democracy and government','Topic — The Riksdag','Learning Objective — Understand the role of the Riksdag.','Knowledge Fact — The Riksdag decides on Swedish laws.','Source — Official Sveriges riksdag webpage','Question — Which institution decides on Swedish laws?','Correct Answer — The Riksdag','Review — Fact and question approved by independent reviewers','Release — Swedish Citizenship 2026.1','Validation — Content and dependencies pass','Publication — Snapshot and checksum are frozen','Delivery — Snapshot is imported into Learning Service','Activation — Release 2026.1 becomes active','Learner — Question appears in practice or a mock exam'];
const mistakes={
 'Content structure':['Creating a question as a learning objective','Writing a broad paragraph as one fact','Creating excessively narrow subjects','Duplicating topics instead of using the hierarchy','Linking content to the wrong exam version'],
 'Sources':['Using unverified blogs when official sources exist','Creating facts without sources','Treating a source title as the fact','Keeping retired sources linked to new content','Ignoring access dates and freshness'],
 'Facts':['Combining unrelated claims','Writing vague or subjective statements','Overwriting approved facts','Duplicating canonical facts','Approving weak evidence'],
 'Questions':['Not linking an approved fact','More than one plausible single-choice answer','Obviously wrong distractors','Explanations that repeat only the answer','Unsupported question types or wrong objective'],
 'Releases':['Assuming approval makes content live','Ignoring validation warnings','Editing without revalidating','Assuming delivery activates','Trying to modify a published release','Forgetting existing sessions remain pinned'],
};

export function ContentSystemGuidePage(){return <article className="guide-page"><header className="page-header"><div><span className="eyebrow">Help · Content governance</span><h1>How the Content System Works</h1><p>A permanent guide for administrators, authors, reviewers, publishers, and operational staff.</p></div></header>
  <section id="overview" className="guide-intro"><h2>Overview</h2><p className="guide-lead">The platform is a controlled pipeline that turns trusted information into learner-facing practice questions and mock exams.</p><p>The conceptual path is <strong>Exam → Exam Version → Subject → Topic → Learning Objective → Knowledge Fact → Question → Review → Release → Practice / Mock Exam</strong>. A source supports a knowledge fact: it is evidence, not a replacement for the fact.</p></section>
  <nav className="guide-toc card" aria-label="On this page"><h2>On this page</h2><ol>{contents.map(([id,label])=><li key={id}><a href={`#${id}`}>{label}</a></li>)}</ol></nav>
  <section id="flow"><h2>The full content flow</h2><ContentFlowDiagram/></section>
  <section id="concepts"><h2>Explanation of every concept</h2><p>These definitions use the terminology implemented by the Content and Learning Service APIs.</p><div className="concept-grid">{concepts.map(concept=><ConceptSection key={concept.id} concept={concept}/>)}</div></section>
  <section id="states"><h2>Review status versus lifecycle status</h2><div className="table-scroll"><table><caption>Two independent questions about governed content</caption><thead><tr><th>Dimension</th><th>Question answered</th><th>Typical states</th></tr></thead><tbody><tr><th>Review status</th><td>Has this content been editorially reviewed?</td><td>UNREVIEWED, UNDER_REVIEW, APPROVED, REJECTED, REQUIRES_UPDATE</td></tr><tr><th>Lifecycle status</th><td>Is this content usable or historical?</td><td>DRAFT, ACTIVE, RETIRED</td></tr></tbody></table></div><p>An approved fact can later be retired when it becomes outdated. Review history and lifecycle history are both preserved.</p><div className="guide-columns"><section className="card"><h3>Fact reviewers check</h3><ul><li>Factual correctness and clarity</li><li>Source authority and freshness</li><li>Scope and validity dates</li></ul></section><section className="card"><h3>Question reviewers check</h3><ul><li>Wording and ambiguity</li><li>Correct answer and distractors</li><li>Linked facts, difficulty, and explanation</li></ul></section></div></section>
  <section id="delivery"><h2>Release and learner delivery</h2><div className="distinction-grid"><div><strong>Review</strong><span>verifies content quality</span></div><div><strong>Validation</strong><span>verifies release consistency</span></div><div><strong>Publication</strong><span>freezes snapshot and checksum</span></div><div><strong>Delivery</strong><span>imports into Learning Service</span></div><div><strong>Activation</strong><span>selects content for new sessions</span></div></div><p><strong>Published does not mean imported. Imported does not mean active.</strong> A published release is immutable. Corrections require a new release. Existing sessions stay pinned when another release becomes active.</p></section>
  <section id="sessions"><h2>Practice versus mock exams</h2><div className="table-scroll"><table><caption>Teaching and assessment behavior</caption><thead><tr><th>Experience</th><th>Purpose</th><th>Feedback</th><th>Runtime</th></tr></thead><tbody><tr><th>Practice</th><td>Teach</td><td>Immediate correctness and explanation</td><td>Learner chooses focused or mixed content; progress is recorded</td></tr><tr><th>Mock exam</th><td>Assess</td><td>Only after final submission</td><td>Fixed questions, timer, flags, score, pass/fail, and breakdowns</td></tr></tbody></table></div><p>Fully learner-supported question types: <strong>{supportedLearnerQuestionTypes.join(', ')}</strong>. Multiple-choice answers use exact-set scoring with no partial credit.</p></section>
  <section id="services"><h2>Platform service responsibilities</h2><div className="service-boundary" role="img" aria-label="Admin Portal connects to Content Service. Content Service sends a published snapshot to Learning Service. Learning Service serves Mobile App."><div>Admin Portal<br/><small>Create, review, publish, monitor</small></div><span aria-hidden="true">↓</span><div>Content Service<br/><small>Owns canonical content and releases</small></div><span aria-hidden="true">↓ published snapshot</span><div>Learning Service<br/><small>Owns imported releases and learner activity</small></div><span aria-hidden="true">↓</span><div>Mobile App<br/><small>Practice and mock exams</small></div></div><p>Content Service and Learning Service own separate databases. They communicate through versioned APIs and immutable snapshots, never shared tables.</p></section>
  <section id="example"><h2>Complete worked example</h2><ol className="worked-example">{example.map((step,index)=><li key={step}><span>{index+1}</span><p>{step}</p></li>)}</ol></section>
  <section aria-labelledby="distinctions"><h2 id="distinctions">Most important distinctions</h2><div className="distinction-grid"><div><strong>Source</strong><span>where evidence comes from</span></div><div><strong>Fact</strong><span>canonical truth in the platform</span></div><div><strong>Question</strong><span>how the learner is tested</span></div><div><strong>Release</strong><span>the exact package learners receive</span></div></div></section>
  <section id="mistakes"><h2>Common mistakes to avoid</h2><div className="concept-grid">{Object.entries(mistakes).map(([group,items])=><section className="card" key={group}><h3>{group}</h3><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></section>)}</div></section>
  <section id="checklists"><h2>Administrator checklists</h2><div className="concept-grid">{checklists.map(list=><section className="card" key={list.title}><h3>{list.title}</h3><ul className="guide-checklist">{list.items.map(item=><li key={item}>{item}</li>)}</ul></section>)}</div></section>
  <section id="glossary"><h2>Quick reference glossary</h2><div className="table-scroll"><table><caption>Content system terms and examples</caption><thead><tr><th>Term</th><th>Meaning</th><th>Example</th></tr></thead><tbody>{glossary.map(entry=><tr key={entry.term}><th>{entry.term}</th><td>{entry.meaning}</td><td>{entry.example}</td></tr>)}</tbody></table></div></section>
  <nav className="card guide-links" aria-label="Continue in Admin Portal"><h2>Continue in the Admin Portal</h2><Link to="/exam-structure">Go to Exams</Link><Link to="/sources">Go to Sources</Link><Link to="/knowledge">Go to Knowledge Facts</Link><Link to="/questions">Go to Questions</Link><Link to="/reviews">Go to Reviews</Link><Link to="/releases">Go to Releases</Link><Link to="/audit">Go to Audit</Link></nav>
 </article>}
