export type Concept = { id:string; term:string; definition:string; example:string; purpose:string; connects:string; mistake?:string };
export type GlossaryEntry = { term:string; meaning:string; example:string };

export const supportedLearnerQuestionTypes=['SINGLE_CHOICE','MULTIPLE_CHOICE','TRUE_FALSE'] as const;

export const concepts:Concept[]=[
 {id:'exam',term:'Exam',definition:'The top-level product or examination category.',example:'Swedish Citizenship (canonical ID: swedish-citizenship)',purpose:'Keeps the overall content domain stable across services.',connects:'Contains one or more exam versions; it is not itself a question set.',mistake:'Do not use a mutable display name as the integration identifier.'},
 {id:'exam-version',term:'Exam Version',definition:'A specific syllabus or content structure for an exam.',example:'Swedish Citizenship 2026',purpose:'Allows future syllabus changes without destroying history.',connects:'Owns the subject and topic hierarchy. It becomes learner-facing only through a release.'},
 {id:'subject',term:'Subject',definition:'A broad content area inside an exam version.',example:'Democracy and government',purpose:'Organizes the syllabus into areas learners can understand and practise.',connects:'Contains topics.',mistake:'Do not make a separate subject for every small idea.'},
 {id:'topic',term:'Topic',definition:'A focused content section inside a subject.',example:'The Riksdag, within Democracy and government',purpose:'Supports focused learning and practice.',connects:'Contains learning objectives; it is not an individual fact.'},
 {id:'objective',term:'Learning Objective',definition:'A statement of what the learner should understand.',example:'Understand the role of the Riksdag.',purpose:'Connects curriculum structure to facts and assessment.',connects:'Belongs to a topic and groups knowledge facts and questions.',mistake:'“How many members does the Riksdag have?” is a question, not an objective.'},
 {id:'fact',term:'Knowledge Fact',definition:'A precise canonical statement that the platform treats as true.',example:'The Riksdag decides on Swedish laws.',purpose:'Provides the source-backed truth from which questions and explanations are derived.',connects:'Belongs to an objective, is supported by sources, and is linked to questions.',mistake:'Do not combine unrelated claims or overwrite an approved version.'},
 {id:'source',term:'Source',definition:'The evidence supporting a knowledge fact.',example:'Sveriges riksdag — “Så fungerar riksdagen” (official webpage)',purpose:'Makes facts traceable and reviewable.',connects:'One source can support many facts; one fact can have several sources.',mistake:'Do not paste a whole webpage as a fact. Extract a precise statement and link the evidence.'},
 {id:'question',term:'Question',definition:'An assessment item that tests one or more approved knowledge facts.',example:'Which institution decides on Swedish laws? Correct answer: The Riksdag.',purpose:'Tests understanding without becoming the source of truth.',connects:'Belongs to an objective, links exact fact versions, and includes options and an explanation.',mistake:`Learner delivery currently supports ${supportedLearnerQuestionTypes.join(' and ')}. Do not release unsupported types.`},
 {id:'review',term:'Review',definition:'The editorial process that verifies facts and questions.',example:'DRAFT → UNDER_REVIEW → APPROVED',purpose:'Separates authoring from independent quality decisions.',connects:'Authors submit; reviewers approve, reject, or require updates. Approval is not publication.',mistake:'Authors cannot approve their own work.'},
 {id:'versioning',term:'Versioning',definition:'Preservation of the exact historical form of governed content.',example:'Fact v1 approved; fact v2 is a draft correction.',purpose:'Keeps releases, learner sessions, review evidence, and audits reproducible.',connects:'Approved content is retained; edits produce a new draft version.',mistake:'Never overwrite an approved historical version, even for a small correction.'},
 {id:'review-queue',term:'Review Queue',definition:'The shared workspace for submitted facts and questions.',example:'A reviewer claims a submitted question, comments, and approves it.',purpose:'Coordinates pending work, assignment, feedback, and history.',connects:'It is a workflow tool, not another content type.'},
 {id:'release',term:'Release',definition:'A frozen package of exact approved fact and question versions.',example:'Swedish Citizenship 2026.1',purpose:'Defines precisely what can be delivered to learners.',connects:'Is validated, published into a snapshot, delivered, and activated.',mistake:'A release is not a dynamic collection of everything currently approved.'},
 {id:'validation',term:'Release Validation',definition:'Checks that a draft release is complete, supported, and internally consistent.',example:'Approved dependencies, valid answers, supported question types, and correct hierarchy.',purpose:'Blocks inconsistent snapshots before publication.',connects:'Errors block publishing; warnings need attention; editing makes validation stale.'},
 {id:'snapshot',term:'Snapshot and Checksum',definition:'The snapshot is a self-contained published release; its checksum is a SHA-256 fingerprint.',example:'The same snapshot always produces the same checksum.',purpose:'Lets Learning Service import verified content without querying Content Service per question.',connects:'Contains hierarchy, facts, questions, answers, and exact version identifiers.'},
 {id:'delivery',term:'Publication, Delivery, and Activation',definition:'Publication freezes; delivery imports; activation selects content for new learner sessions.',example:'DRAFT → VALIDATED → PUBLISHED → DELIVERED / IMPORTED → ACTIVE',purpose:'Makes every transition explicit and recoverable.',connects:'Only one release is active per exam. Existing sessions stay pinned.',mistake:'Published does not mean imported, and imported does not mean active.'},
 {id:'practice',term:'Practice Session',definition:'A teaching-focused learner session with immediate feedback.',example:'Choose The Riksdag, answer, then see correctness and explanation.',purpose:'Builds understanding and records progress.',connects:'Uses the active release at creation and remains pinned to it.'},
 {id:'mock-exam',term:'Mock Exam',definition:'A timed assessment with a fixed question set and post-submission feedback.',example:'Answer freely, flag questions, submit, then receive score and breakdowns.',purpose:'Simulates assessment conditions rather than teaching during each answer.',connects:'Is pinned to one release; the server owns timer, scoring, and pass/fail.'},
 {id:'audit',term:'Audit Event',definition:'An immutable record of an administrative action.',example:'A reviewer approved a question or a publisher activated a release.',purpose:'Answers who did what, when, and to which entity.',connects:'Complements domain versions and review history; it does not replace them.'},
];

export const glossary:GlossaryEntry[]=[
 ['Exam','Top-level examination category','Swedish Citizenship'],['Exam Version','Specific syllabus structure','Swedish Citizenship 2026'],['Subject','Broad syllabus area','Democracy and government'],['Topic','Focused part of a subject','The Riksdag'],['Learning Objective','What a learner should understand','Understand the role of the Riksdag'],['Knowledge Fact','Canonical source-backed truth','The Riksdag decides on Swedish laws'],['Source','Evidence for a fact','Official Riksdag webpage'],['Question','How understanding is assessed','Which institution decides on laws?'],['Review','Editorial quality decision','APPROVED'],['Lifecycle','Whether content is usable or historical','ACTIVE or RETIRED'],['Version','Preserved revision','Fact version 2'],['Review Queue','Workspace for submitted content','Claim and review a question'],['Release','Frozen content package','2026.1'],['Validation','Release consistency check','No missing dependencies'],['Snapshot','Self-contained delivery artifact','Published JSON snapshot'],['Checksum','Snapshot fingerprint','SHA-256'],['Publish','Freeze a validated release','PUBLISHED'],['Deliver','Import snapshot into Learning','DELIVERED / IMPORTED'],['Activate','Select release for new sessions','ACTIVE'],['Practice','Teaching with immediate feedback','Topic practice'],['Mock Exam','Timed assessment with delayed feedback','15-minute mock'],['Audit Event','Immutable administrative record','Question approved']
].map(([term,meaning,example])=>({term,meaning,example}));

export const checklists=[
 {title:'Before Creating Content',items:['Confirm the correct exam version','Choose the correct subject and topic','Define a clear learning objective','Identify authoritative sources','Split knowledge into precise facts','Avoid duplicating existing facts']},
 {title:'Before Submitting a Fact',items:['Statement is precise','Source supports the exact statement','Source is active and current','Validity dates are correct','Wording is neutral and understandable']},
 {title:'Before Submitting a Question',items:['Question links to approved facts','One clearly correct answer for single choice','Distractors are plausible','Wording is unambiguous','Explanation teaches the concept','Difficulty is appropriate','Question type is supported by learners']},
 {title:'Before Publishing a Release',items:['Release contains intended approved versions','Validation has no errors','Warnings have been reviewed','Checksum and preview look correct','Release number is correct','Publication irreversibility is understood','Delivery and activation are separate steps']},
];
