import { environment } from '../../app/config/environment';

export const adminQueryKey=(...parts:unknown[])=>[environment.appEnvironment,...parts] as const;
export const adminQueryKeys={
 exams:{all:adminQueryKey('exams'),list:(filters:unknown)=>adminQueryKey('exams','list',filters),detail:(id:string)=>adminQueryKey('exams','detail',id),versions:(id:string)=>adminQueryKey('exams',id,'versions')},
 structure:{subjects:(id:string)=>adminQueryKey('subjects',id),topics:(id:string)=>adminQueryKey('topics',id)},
 sources:{all:adminQueryKey('sources'),list:(filters:unknown)=>adminQueryKey('sources','list',filters),detail:(id:string)=>adminQueryKey('sources','detail',id)},
 objectives:{all:adminQueryKey('learning-objectives'),list:(filters:unknown)=>adminQueryKey('learning-objectives','list',filters),detail:(id:string)=>adminQueryKey('learning-objectives','detail',id)},
 facts:{all:adminQueryKey('knowledge-facts'),list:(filters:unknown)=>adminQueryKey('knowledge-facts','list',filters),detail:(id:string)=>adminQueryKey('knowledge-facts','detail',id),versions:(id:string)=>adminQueryKey('knowledge-facts',id,'versions')},
 questions:{all:adminQueryKey('questions'),list:(filters:unknown)=>adminQueryKey('questions','list',filters),detail:(id:string)=>adminQueryKey('questions','detail',id),versions:(id:string)=>adminQueryKey('questions',id,'versions')},
 reviews:{all:adminQueryKey('reviews'),summary:adminQueryKey('reviews','summary'),list:(filters:unknown)=>adminQueryKey('reviews','list',filters),detail:(id:string)=>adminQueryKey('reviews','detail',id)},
 releases:{all:adminQueryKey('releases'),list:(filters:unknown)=>adminQueryKey('releases','list',filters),detail:(id:string)=>adminQueryKey('releases','detail',id),eligible:(id:string)=>adminQueryKey('releases','eligible',id)},
 ai:{job:(id:string)=>adminQueryKey('ai','jobs',id),proposals:(id:string)=>adminQueryKey('ai','jobs',id,'proposals'),editorialJob:(factId:string,operation:string,id:string)=>adminQueryKey('ai','editorial','facts',factId,'operations',operation,'jobs',id),editorialProposals:(factId:string,operation:string,id:string)=>adminQueryKey('ai','editorial','facts',factId,'operations',operation,'jobs',id,'proposals'),editorialFindings:(factId:string,operation:string,id:string)=>adminQueryKey('ai','editorial','facts',factId,'operations',operation,'jobs',id,'findings'),questionEligibility:(factId:string,factVersionId:string)=>adminQueryKey('ai','question-generation','facts',factId,'versions',factVersionId,'eligibility'),questionHistory:(factId:string)=>adminQueryKey('ai','question-generation','facts',factId,'history'),questionJob:(factId:string,factVersionId:string,id:string)=>adminQueryKey('ai','question-generation','facts',factId,'versions',factVersionId,'jobs',id),questionProposals:(factId:string,factVersionId:string,id:string)=>adminQueryKey('ai','question-generation','facts',factId,'versions',factVersionId,'jobs',id,'proposals'),questionLineage:(id:string)=>adminQueryKey('ai','question-proposals',id,'lineage'),batches:(filters:unknown)=>adminQueryKey('ai','question-batches',filters),batch:(id:string)=>adminQueryKey('ai','question-batches',id),batchItems:(id:string,filters:unknown)=>adminQueryKey('ai','question-batches',id,'items',filters),batchProposals:(id:string,filters:unknown)=>adminQueryKey('ai','question-batches',id,'proposals',filters),providerStatus:adminQueryKey('ai','provider','status'),providerAlerts:adminQueryKey('ai','provider','alerts')}
};
