import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { acceptAiKnowledgeFactProposal, cancelAiKnowledgeFactJob, createAiKnowledgeFactJob, editAiKnowledgeFactProposal, getAiKnowledgeFactJob, getSource, listAiKnowledgeFactProposals, listLearningObjectives, rejectAiKnowledgeFactProposal, type AiGenerationRequest } from '../../../api/generated';
import { contentServiceClient } from '../../../api/client/contentServiceClient';
import { unwrap } from '../../../api/client/adminApi';
import { adminQueryKeys } from '../../../api/query-keys/adminQueryKeys';
import { AsyncState } from '../../../components/AsyncState';
import { PageHeader, StatusBadge } from '../../../components/AdminUi';

const terminal = new Set(['COMPLETED','PARTIALLY_COMPLETED','FAILED','CANCELLED']);
export function AiKnowledgeFactGenerationPage(){
 const {sourceId,jobId}=useParams();const nav=useNavigate();const qc=useQueryClient();const [selected,setSelected]=useState<string[]>([]);
 const source=useQuery({queryKey:adminQueryKeys.sources.detail(sourceId!),queryFn:()=>unwrap(getSource({client:contentServiceClient,path:{sourceId:sourceId!}}))});
 const objectives=useQuery({queryKey:adminQueryKeys.objectives.list({picker:true}),queryFn:()=>unwrap(listLearningObjectives({client:contentServiceClient,query:{page:0,size:100}}))});
 const job=useQuery({queryKey:adminQueryKeys.ai.job(jobId??'new'),queryFn:()=>unwrap(getAiKnowledgeFactJob({client:contentServiceClient,path:{jobId:jobId!}})),enabled:!!jobId,refetchInterval:q=>q.state.data&&terminal.has(q.state.data.status)?false:1500});
 const proposals=useQuery({queryKey:adminQueryKeys.ai.proposals(jobId??'new'),queryFn:()=>unwrap(listAiKnowledgeFactProposals({client:contentServiceClient,path:{jobId:jobId!}})),enabled:!!jobId&&!!job.data&&terminal.has(job.data.status)});
 const form=useForm<AiGenerationRequest>({defaultValues:{sourceId:sourceId!,learningObjectiveId:'',requestedCount:8,language:'sv',editorialInstruction:'',idempotencyKey:crypto.randomUUID()}});
 const create=useMutation({mutationFn:(body:AiGenerationRequest)=>unwrap(createAiKnowledgeFactJob({client:contentServiceClient,body})),onSuccess:x=>nav(`/sources/${sourceId}/ai-generation/${x.id}`)});
 const refresh=()=>{qc.invalidateQueries({queryKey:adminQueryKeys.ai.proposals(jobId!)});qc.invalidateQueries({queryKey:adminQueryKeys.ai.job(jobId!)})};
 const act=useMutation({mutationFn:async({id,kind,text,version}:{id:string;kind:'edit'|'reject'|'accept';text?:string;version:number})=>kind==='edit'?unwrap(editAiKnowledgeFactProposal({client:contentServiceClient,path:{proposalId:id},body:{text:text!,version}})):kind==='reject'?unwrap(rejectAiKnowledgeFactProposal({client:contentServiceClient,path:{proposalId:id},body:{reason:null,version}})):unwrap(acceptAiKnowledgeFactProposal({client:contentServiceClient,path:{proposalId:id},body:{version}})),onSuccess:refresh});
 const acceptSelected=async()=>{if(!confirm(`${selected.length} proposals will become DRAFT Knowledge Facts. Human review remains required.`))return;for(const id of selected){const p=proposals.data?.find(x=>x.id===id);if(p)await act.mutateAsync({id,kind:'accept',version:p.version});}setSelected([])};
 return <><PageHeader eyebrow="AI-assisted editorial workflow" title="Generate Knowledge Facts" description="Grounded suggestions remain proposals until you accept them as normal drafts. AI cannot submit, approve, or publish content." actions={<Link className="button secondary" to={`/sources/${sourceId}`}>Back to source</Link>}/>
 <AsyncState loading={source.isPending||objectives.isPending} error={source.error||objectives.error}>
  <section className="card"><h2>Source</h2><strong>{source.data?.title}</strong><p>{source.data?.contentText?.slice(0,600)||'This source has no usable content.'}</p>{source.data?.contentText&&source.data.contentText.length>600&&<small>Preview truncated. The full stored text is used.</small>}</section>
  {!jobId&&<form className="form" onSubmit={form.handleSubmit(v=>create.mutate(v))}><label>Learning objective<select {...form.register('learningObjectiveId',{required:true})}><option value="">Select an objective</option>{objectives.data?.items.map(o=><option key={o.id} value={o.id}>{o.subjectName} / {o.topicName} / {o.title}</option>)}</select></label><label>Number of proposals<input type="number" min="1" max="20" {...form.register('requestedCount',{valueAsNumber:true,min:1,max:20})}/></label><label>Language<input {...form.register('language',{required:true})}/></label><label>Optional editorial instruction<textarea {...form.register('editorialInstruction',{maxLength:1000})}/></label><p className="warning card">AI suggestions may be incomplete or inaccurate. Review every proposal and its evidence against the source before creating Knowledge Facts.</p>{create.error&&<p className="error" role="alert">{create.error.message}</p>}<button disabled={create.isPending||!source.data?.contentText}>Generate proposals</button></form>}
  {jobId&&<AsyncState loading={job.isPending} error={job.error}><section className="card"><div className="page-header"><div><h2>Generation job</h2><StatusBadge value={job.data?.status??'QUEUED'}/></div>{job.data&&!terminal.has(job.data.status)&&<button className="secondary" onClick={()=>unwrap(cancelAiKnowledgeFactJob({client:contentServiceClient,path:{jobId}})).then(refresh)}>Cancel</button>}</div><p>{job.data?.generatedCount} of {job.data?.requestedCount} proposals · {job.data?.provider} / {job.data?.model}</p>{job.data?.errorMessage&&<p className="error" role="alert">{job.data.errorMessage}</p>}</section>
   <AsyncState loading={proposals.isPending} error={proposals.error}>{proposals.data?.length===0&&<p className="card">No proposals were produced.</p>}{selected.length>0&&<div className="actions"><button onClick={acceptSelected}>Accept selected ({selected.length})</button></div>}<div className="proposal-grid">{proposals.data?.map(p=><article className="card" key={p.id}><div className="actions"><label className="checkbox"><input type="checkbox" disabled={!['PROPOSED','EDITED'].includes(p.status)} checked={selected.includes(p.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,p.id]:s.filter(x=>x!==p.id))}/><span>Select</span></label><StatusBadge value={p.status}/><StatusBadge value="AI ASSISTED"/></div><label>Proposed fact<textarea defaultValue={p.editedText} disabled={!['PROPOSED','EDITED'].includes(p.status)} onBlur={e=>{if(e.target.value!==p.editedText)act.mutate({id:p.id,kind:'edit',text:e.target.value,version:p.version})}}/></label><h3>Source evidence</h3>{p.sourceEvidence.map((e,i)=><blockquote key={i}>{e.quote}{e.location&&<footer>{e.location}</footer>}</blockquote>)}<p>{p.modelNote}</p>{['PROPOSED','EDITED'].includes(p.status)&&<div className="actions"><button onClick={()=>act.mutate({id:p.id,kind:'accept',version:p.version})}>Accept as draft</button><button className="secondary" onClick={()=>act.mutate({id:p.id,kind:'reject',version:p.version})}>Reject</button></div>}{p.resultingKnowledgeFactId&&<Link to={`/knowledge/facts/${p.resultingKnowledgeFactId}`}>Open resulting draft</Link>}</article>)}</div></AsyncState>
  </AsyncState>}
 </AsyncState></>;
}
