import { useQuery } from '@tanstack/react-query';
import { getAiProviderOperations } from '../../../api/generated/sdk.gen';
import { contentServiceClient } from '../../../api/client/contentServiceClient';
import { unwrap } from '../../../api/client/adminApi';

type Row=Record<string,unknown>;
const value=(v:unknown)=>v==null||v===''?'—':String(v);
export function AiProvidersPage(){
  const query=useQuery({queryKey:['ai','provider-operations'],queryFn:()=>unwrap(getAiProviderOperations({client:contentServiceClient}))});
  const data=query.data;const attempts=(data?.recentAttempts??[]) as Row[];const paidAccounting=(data?.paidAccounting??[]) as Row[];
  return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">AI operations</p><h1>AI Providers</h1><p>Provider readiness, free-first routing, capped paid fallback and request accounting.</p></div><button className="secondary" onClick={()=>query.refetch()} disabled={query.isFetching}>Refresh provider status</button></header>
    <p className="warning" role="note"><strong>Free providers always run first.</strong> OpenRouter paid is the final fallback and is guarded by the application budget. Generation pauses when the next maximum request estimate cannot be reserved.</p>
    {query.isPending&&<p role="status">Loading provider status…</p>}{query.error&&<p role="alert" className="error">Provider status could not be loaded.</p>}
    {data&&<><section className="card"><h2>Routing policy</h2><div className="report-grid"><Metric label="Billing policy" value={data.billingPolicy}/><Metric label="Paid fallback" value={data.allowPaidFallback?'Enabled':'Disabled'}/><Metric label="Zero cost required first" value={data.requireZeroCostProvider?'Yes':'No'}/><Metric label="Automatic billing upgrade" value={data.allowAutomaticBillingUpgrade?'Enabled':'Disabled'}/><Metric label="Current routing decision" value={data.currentRoutingDecision}/></div><p><strong>Priority:</strong> {data.priority.join(' → ')}</p></section>
    <section><h2>Providers</h2><div className="proposal-grid">{data.providers.map(p=>{const capacity=p.capacity as Row;const paid=p.provider==='OPENROUTER_PAID';return <article className="card" key={p.provider}><div className="actions"><h3>{p.provider.replaceAll('_',' ')}</h3><span className="status-badge">{p.status.replaceAll('_',' ')}</span></div><dl><dt>Model</dt><dd>{value(p.model)}</dd><dt>Priority</dt><dd>{p.priority}</dd><dt>Enabled</dt><dd>{p.enabled?'Yes':'No'}</dd><dt>Credentials configured</dt><dd>{p.credentialConfigured?'Yes':'No'}</dd><dt>Billing route</dt><dd>{paid?'Capped paid fallback':'FREE'}</dd>{paid&&<><dt>Configured budget</dt><dd>{usd(capacity.configuredBudgetUsd)}</dd><dt>Spent</dt><dd>{usd(capacity.spentUsd)}</dd><dt>Remaining</dt><dd>{usd(capacity.remainingUsd)}</dd><dt>Estimated next request</dt><dd>{usd(capacity.estimatedNextRequestUsd)}</dd></>}<dt>Circuit</dt><dd>{value(p.circuitState)}</dd><dt>Next retry/reset</dt><dd>{p.nextRetryAt?new Date(p.nextRetryAt).toLocaleString():'—'}</dd><dt>Last successful request</dt><dd>{p.lastSuccessfulRequest?new Date(String(p.lastSuccessfulRequest)).toLocaleString():'—'}</dd><dt>Average latency</dt><dd>{p.averageLatencyMs==null?'—':`${p.averageLatencyMs} ms`}</dd></dl><details><summary>Capacity and capabilities</summary><pre>{JSON.stringify({capacity:p.capacity,capabilities:p.capabilities},null,2)}</pre></details></article>})}</div></section>
    <section className="card"><h2>Recent provider attempts</h2><div className="table-wrap"><table><thead><tr><th>Started</th><th>Operation</th><th>Provider</th><th>Model</th><th>Status</th><th>Free</th><th>Tokens</th><th>Latency</th><th>Error/fallback</th></tr></thead><tbody>{attempts.length===0?<tr><td colSpan={9}>No provider attempts recorded.</td></tr>:attempts.map((a,i)=><tr key={String(a.id??i)}><td>{a.startedAt?new Date(String(a.startedAt)).toLocaleString():'—'}</td><td>{value(a.operation)}</td><td>{value(a.provider)}</td><td>{value(a.model)}</td><td>{value(a.status)}</td><td>{a.confirmedFree===true?'Yes':'No'}</td><td>{Number(a.inputTokens??0)+Number(a.outputTokens??0)}</td><td>{a.latencyMs==null?'—':`${a.latencyMs} ms`}</td><td>{value(a.errorCode??a.fallbackReason)}</td></tr>)}</tbody></table></div></section>
    <section className="card"><h2>Paid request accounting</h2><div className="table-wrap"><table><thead><tr><th>Started</th><th>Model</th><th>Status</th><th>Prompt</th><th>Completion</th><th>Reasoning</th><th>Estimated</th><th>Actual</th><th>Budget before</th><th>Budget after</th><th>Routing reason</th></tr></thead><tbody>{paidAccounting.length===0?<tr><td colSpan={11}>No paid requests recorded.</td></tr>:paidAccounting.map((a,i)=><tr key={String(a.id??i)}><td>{a.createdAt?new Date(String(a.createdAt)).toLocaleString():'—'}</td><td>{value(a.model)}</td><td>{value(a.status)}</td><td>{value(a.promptTokens)}</td><td>{value(a.completionTokens)}</td><td>{value(a.reasoningTokens)}</td><td>{usd(a.estimatedCostUsd)}</td><td>{usd(a.actualCostUsd)}</td><td>{usd(a.budgetBeforeUsd)}</td><td>{usd(a.budgetAfterUsd)}</td><td>{value(a.routingReason)}</td></tr>)}</tbody></table></div></section></>}
  </div>;
}
function Metric({label,value}:{label:string,value:unknown}){return <div><small>{label}</small><strong>{String(value)}</strong></div>}
function usd(value:unknown){if(value==null||value==='')return '—';const parsed=Number(value);return Number.isFinite(parsed)?`$${parsed.toFixed(6)}`:'—'}
