import { render,screen,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClient,QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter,Route,Routes } from "react-router-dom";
import { AiQuestionBatchListPage } from "./AiQuestionBatchListPage";
import { AiQuestionBatchDetailPage } from "./AiQuestionBatchDetailPage";

const batch={id:"11111111-1111-1111-1111-111111111111",scopeType:"TOPIC",scopeId:"22222222-2222-2222-2222-222222222222",scopeLabel:"Topic · Democracy",language:"sv",configuration:{questionsPerKnowledgeFact:2},createdBy:"author",status:"COMPLETED",provider:"FAKE",model:"deterministic-v1",createdAt:"2026-07-23T08:00:00Z",requested:2,generated:2,failed:0,cancelled:0,generationProgressPercentage:100,reviewProgressPercentage:0,acceptanceProgressPercentage:0,version:2};
const page={items:[batch],page:0,size:20,totalItems:1,totalPages:1};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});}
function renderPage(detail=false){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[detail?`/ai/question-batches/${batch.id}`:"/ai/question-batches"]}><Routes><Route path="/ai/question-batches" element={<AiQuestionBatchListPage/>}/><Route path="/ai/question-batches/:id" element={<AiQuestionBatchDetailPage/>}/></Routes></MemoryRouter></QueryClientProvider>);}
describe("AI question batch pages",()=>{
  it("lists persisted batches and previews scope before enabling creation",async()=>{vi.stubGlobal("fetch",vi.fn().mockImplementation((request:Request)=>{if(request.url.endsWith("/preview"))return Promise.resolve(json({resolvedKnowledgeFactCount:4,estimatedProposalCount:8,excludedKnowledgeFactCount:0,configuredMaximum:200,withinLimit:true,estimatedProviderCalls:8,warnings:[]}));if(request.method==="POST")return Promise.resolve(json(batch,202));return Promise.resolve(json(page));}));renderPage();expect(await screen.findByText("Topic · Democracy")).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"Generate AI Questions"}));await userEvent.type(screen.getByLabelText("Scope ID"),batch.scopeId);expect(screen.getByRole("button",{name:"Create Batch"})).toBeDisabled();await userEvent.click(screen.getByRole("button",{name:"Preview Batch"}));expect(await screen.findByText(/4 eligible facts · 8 proposals/)).toBeInTheDocument();expect(screen.getByRole("button",{name:"Create Batch"})).toBeEnabled();});
  it("blocks malformed scope identifiers before calling the service",async()=>{const fetch=vi.fn().mockResolvedValue(json(page));vi.stubGlobal("fetch",fetch);renderPage();await screen.findByText("Topic · Democracy");await userEvent.click(screen.getByRole("button",{name:"Generate AI Questions"}));await userEvent.type(screen.getByLabelText("Scope ID"),"ai1");expect(screen.getByRole("alert")).toHaveTextContent("valid scope UUID");expect(screen.getByRole("button",{name:"Preview Batch"})).toBeDisabled();expect(fetch).toHaveBeenCalledTimes(1);});
  it("renders separate generation, review and acceptance progress with batch items",async()=>{vi.stubGlobal("fetch",vi.fn().mockImplementation((request:Request)=>{if(request.url.includes("/items"))return Promise.resolve(json({items:[{id:"33333333-3333-3333-3333-333333333333",batchId:batch.id,sequence:0,knowledgeFactId:"44444444-4444-4444-4444-444444444444",knowledgeFactVersionId:"55555555-5555-5555-5555-555555555555",questionType:"SINGLE_CHOICE",language:"sv",targetDifficulty:"EASY",targetBloomLevel:"REMEMBER",status:"FAILED",attemptCount:3,rateLimitCount:0,failureCode:"GROUNDING_FAILED",failureMessage:"Grounding did not pass",createdAt:batch.createdAt,version:1}],page:0,size:100,totalItems:1,totalPages:1}));if(request.url.includes("/proposals"))return Promise.resolve(json({items:[],page:0,size:100,totalItems:0,totalPages:0}));return Promise.resolve(json(batch));}));renderPage(true);expect(await screen.findByRole("heading",{name:"Generation"})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Review"})).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Acceptance"})).toBeInTheDocument();expect(await screen.findByText("GROUNDING_FAILED")).toBeInTheDocument();await waitFor(()=>expect(screen.getAllByText("100%").length).toBeGreaterThan(0));});
});
