import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import {
  assignAiQuestionProposalReviewer, bulkAcceptAiQuestionProposals, bulkRegenerateAiQuestionProposals,
  bulkRejectAiQuestionProposals, cancelAiQuestionGenerationBatch, exportAiQuestionGenerationBatch,
  getAiQuestionGenerationBatch, listAiQuestionGenerationBatchItems, listAiQuestionGenerationBatchProposals,
  retryFailedAiQuestionGenerationBatchItems, type AiQuestionRejectionReason,
  unassignAiQuestionProposalReviewer,
} from "../../../api/generated";
import { contentServiceClient } from "../../../api/client/contentServiceClient";
import { unwrap } from "../../../api/client/adminApi";
import { adminQueryKeys } from "../../../api/query-keys/adminQueryKeys";
import { QuestionProposalCard } from "../components/AiQuestionGenerationWorkspace";

const terminal=new Set(["COMPLETED","PARTIALLY_COMPLETED","FAILED","CANCELLED"]);
type Action="assign"|"unassign"|"reject"|"regenerate"|"accept"|null;
export function AiQuestionBatchDetailPage(){
  const {id=""}=useParams();const qc=useQueryClient();const [proposalStatus,setProposalStatus]=useState("");const [itemStatus,setItemStatus]=useState("");const [itemPage,setItemPage]=useState(0);const [proposalPage,setProposalPage]=useState(0);const [selected,setSelected]=useState<Set<string>>(new Set());const [action,setAction]=useState<Action>(null);const [text,setText]=useState("");const [reason,setReason]=useState<AiQuestionRejectionReason>("AMBIGUOUS");const [result,setResult]=useState<{succeeded:number;failed:number}|null>(null);
  const batch=useQuery({queryKey:adminQueryKeys.ai.batch(id),queryFn:()=>unwrap(getAiQuestionGenerationBatch({client:contentServiceClient,path:{batchId:id}})),refetchInterval:q=>terminal.has(q.state.data?.status??"")?false:2000});
  const items=useQuery({queryKey:adminQueryKeys.ai.batchItems(id,{itemStatus,itemPage}),queryFn:()=>unwrap(listAiQuestionGenerationBatchItems({client:contentServiceClient,path:{batchId:id},query:{page:itemPage,size:50,status:itemStatus||undefined}}))});
  const proposals=useQuery({queryKey:adminQueryKeys.ai.batchProposals(id,{proposalStatus,proposalPage}),queryFn:()=>unwrap(listAiQuestionGenerationBatchProposals({client:contentServiceClient,path:{batchId:id},query:{page:proposalPage,size:25,status:proposalStatus||undefined}}))});
  const chosen=useMemo(()=>proposals.data?.items.filter(p=>selected.has(p.id))??[],[proposals.data,selected]);const versions=Object.fromEntries(chosen.map(p=>[p.id,p.version]));
  const refresh=()=>{qc.invalidateQueries({queryKey:adminQueryKeys.ai.batch(id)});qc.invalidateQueries({queryKey:["ai","question-batches",id]});};
  const cancel=useMutation({mutationFn:()=>unwrap(cancelAiQuestionGenerationBatch({client:contentServiceClient,path:{batchId:id}})),onSuccess:refresh});
  const retry=useMutation({mutationFn:()=>unwrap(retryFailedAiQuestionGenerationBatchItems({client:contentServiceClient,path:{batchId:id},body:{itemIds:[]}})),onSuccess:refresh});
  const bulk=useMutation({mutationFn:async()=>{if(action==="assign")return unwrap(assignAiQuestionProposalReviewer({client:contentServiceClient,body:{proposalIds:[...selected],reviewerId:text}}));if(action==="unassign")return unwrap(unassignAiQuestionProposalReviewer({client:contentServiceClient,body:{proposalIds:[...selected]}}));if(action==="reject")return unwrap(bulkRejectAiQuestionProposals({client:contentServiceClient,body:{proposalIds:[...selected],reasonCode:reason,reviewerComment:text||null,versions}}));if(action==="regenerate")return unwrap(bulkRegenerateAiQuestionProposals({client:contentServiceClient,body:{proposalIds:[...selected],reviewerFeedback:text,versions,idempotencyKey:crypto.randomUUID()}}));return unwrap(bulkAcceptAiQuestionProposals({client:contentServiceClient,body:{proposalIds:[...selected],versions}}));},onSuccess:r=>{setResult({succeeded:r.succeeded,failed:r.failed});setSelected(new Set());refresh();}});
  const exportBatch=async()=>{const value=await unwrap(exportAiQuestionGenerationBatch({client:contentServiceClient,path:{batchId:id},query:{format:"JSON"}}));const blob=new Blob([JSON.stringify(value,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`ai-question-batch-${id}.json`;link.click();URL.revokeObjectURL(url);};
  if(batch.isPending)return <p role="status">Loading batch…</p>;if(batch.error)return <p role="alert" className="error">{batch.error.message}</p>;if(!batch.data)return null;const b=batch.data;const canCancel=["PENDING","RUNNING"].includes(b.status);
  return <div className="page-stack"><header className="page-header"><div><Link to="/ai/question-batches">← Question batches</Link><p className="eyebrow">{b.scopeLabel??b.scopeType}</p><h1>Batch {b.id.slice(0,8)}</h1><p>Created by {b.createdBy} · {new Date(b.createdAt).toLocaleString()}</p></div><div className="actions"><span className="status-badge">{b.status.replaceAll("_"," ")}</span>{canCancel&&<button className="secondary" disabled={cancel.isPending} onClick={()=>cancel.mutate()}>Cancel Batch</button>}{b.failed>0&&<button className="secondary" disabled={retry.isPending} onClick={()=>retry.mutate()}>Retry Failed</button>}<button className="secondary" onClick={exportBatch}>Export JSON</button></div></header>
    <section className="metric-grid"><Progress title="Generation" value={b.generationProgressPercentage} detail={`${b.generated} generated · ${b.failed} failed · ${b.cancelled} cancelled / ${b.requested}`}/><Progress title="Review" value={b.reviewProgressPercentage} detail={`${Number((b as unknown as Record<string,number>).reviewed??0)} reviewed / ${b.generated}`}/><Progress title="Acceptance" value={b.acceptanceProgressPercentage} detail={`${Number((b as unknown as Record<string,number>).accepted??0)} accepted / ${b.generated}`}/></section>
    <section className="card"><h2>Configuration and usage</h2><pre>{JSON.stringify(b.configuration,null,2)}</pre><p><strong>Provider:</strong> {b.provider} / {b.model}</p><p><strong>Tokens:</strong> {Number(((b as unknown as {usage?:{totalTokens?:number}}).usage?.totalTokens)??0)} tracked · monetary cost unavailable without versioned pricing configuration</p></section>
    <section className="card"><div className="actions"><h2>Batch Items</h2><label>Status<select aria-label="Item status filter" value={itemStatus} onChange={e=>{setItemStatus(e.target.value);setItemPage(0);}}><option value="">All</option>{["PENDING","PROCESSING","RETRY_SCHEDULED","GENERATED","FAILED","CANCELLED"].map(v=><option key={v}>{v}</option>)}</select></label></div>{items.isPending&&<p role="status">Loading items…</p>}<div className="table-wrap"><table><thead><tr><th>Knowledge Fact</th><th>Type</th><th>Difficulty</th><th>Bloom</th><th>Status</th><th>Attempts</th><th>Proposal</th><th>Failure</th></tr></thead><tbody>{items.data?.items.map(i=><tr key={i.id}><td><code>{i.knowledgeFactId.slice(0,8)}</code></td><td>{i.questionType.replaceAll("_"," ")}</td><td>{i.targetDifficulty}</td><td>{i.targetBloomLevel}</td><td><span className="status-badge">{i.status.replaceAll("_"," ")}</span></td><td>{i.attemptCount}</td><td>{i.proposalId?<a href={`#proposal-${i.proposalId}`}>Review</a>:"—"}</td><td>{i.failureCode?<><strong>{i.failureCode}</strong><small>{i.failureMessage}</small></>:"—"}</td></tr>)}</tbody></table></div><Pager page={itemPage} totalPages={items.data?.totalPages??0} setPage={setItemPage}/></section>
    <section className="card"><div className="actions"><div><h2>Batch Review Workspace</h2><p>{selected.size} selected · each action is validated independently.</p></div><label>Proposal status<select aria-label="Proposal status filter" value={proposalStatus} onChange={e=>{setProposalStatus(e.target.value);setProposalPage(0);setSelected(new Set());}}><option value="">All</option>{["PROPOSED","REJECTED","ACCEPTED","SUPERSEDED"].map(v=><option key={v}>{v}</option>)}</select></label></div>
      <div className="actions"><button className="secondary" onClick={()=>setSelected(new Set(proposals.data?.items.filter(p=>p.status==="PROPOSED").map(p=>p.id)))}>Select visible eligible</button><button className="secondary" onClick={()=>setSelected(new Set())}>Clear</button>{(["assign","unassign","reject","regenerate","accept"] as const).map(a=><button key={a} disabled={selected.size===0} onClick={()=>{setAction(a);setText("");setResult(null);}}>{a[0].toUpperCase()+a.slice(1)} selected</button>)}</div>
      {proposals.isPending&&<p role="status">Loading proposals…</p>}{proposals.error&&<p role="alert" className="error">{proposals.error.message}</p>}
      <div className="proposal-grid">{proposals.data?.items.map(p=><div id={`proposal-${p.id}`} key={p.id}><label><input type="checkbox" aria-label={`Select ${p.questionText}`} checked={selected.has(p.id)} onChange={()=>setSelected(current=>{const next=new Set(current);if(next.has(p.id))next.delete(p.id);else next.add(p.id);return next;})}/> Select proposal</label><QuestionProposalCard proposal={p} factId={p.targetKnowledgeFactId} factVersionId={p.targetKnowledgeFactVersionId} jobId={p.generationJobId} canReview canAccept onRegenerationQueued={()=>refresh()} onChanged={refresh}/></div>)}</div><Pager page={proposalPage} totalPages={proposals.data?.totalPages??0} setPage={page=>{setProposalPage(page);setSelected(new Set());}}/>
    </section>
    {action&&<BulkDialog action={action} count={selected.size} text={text} setText={setText} reason={reason} setReason={setReason} pending={bulk.isPending} result={result} error={bulk.error?.message} close={()=>setAction(null)} confirm={()=>bulk.mutate()}/>}
  </div>;
}
function Progress({title,value,detail}:{title:string;value:number;detail:string}){return <article className="card"><h2>{title}</h2><strong>{value}%</strong><progress max={100} value={value}>{value}%</progress><p>{detail}</p></article>;}
function Pager({page,totalPages,setPage}:{page:number;totalPages:number;setPage:(page:number)=>void}){if(totalPages<=1)return null;return <nav className="actions" aria-label="Pagination"><button className="secondary" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1} of {totalPages}</span><button className="secondary" disabled={page+1>=totalPages} onClick={()=>setPage(page+1)}>Next</button></nav>;}
function BulkDialog({action,count,text,setText,reason,setReason,pending,result,error,close,confirm}:{action:Exclude<Action,null>;count:number;text:string;setText:(v:string)=>void;reason:AiQuestionRejectionReason;setReason:(v:AiQuestionRejectionReason)=>void;pending:boolean;result:{succeeded:number;failed:number}|null;error?:string;close:()=>void;confirm:()=>void}){const needsText=action==="assign"||action==="regenerate"||(action==="reject"&&reason==="OTHER");return <section role="dialog" aria-modal="true" aria-label={`${action} selected proposals`} className="card split-confirmation"><h2>{action[0].toUpperCase()+action.slice(1)} {count} proposals?</h2>{action==="accept"&&<p className="warning">Each proposal will be revalidated independently. Some may fail. Every success creates one DRAFT / UNREVIEWED canonical Question.</p>}{action==="regenerate"&&<p className="warning">Each proposal creates a separate successor and immutable lineage.</p>}{action==="unassign"&&<p>This removes the current reviewer assignment without changing proposal review state.</p>}{action==="reject"&&<label>Reason<select value={reason} onChange={e=>setReason(e.target.value as AiQuestionRejectionReason)}>{["AMBIGUOUS","FACTUALLY_INCORRECT","DUPLICATE","POOR_DISTRACTORS","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label>}{action!=="accept"&&action!=="unassign"&&<label>{action==="assign"?"Reviewer ID":action==="regenerate"?"Concrete reviewer feedback":"Reviewer comment"}<textarea aria-label="Bulk action input" value={text} onChange={e=>setText(e.target.value)}/></label>}{result&&<p role="status" className="success">{result.succeeded} succeeded · {result.failed} failed</p>}{error&&<p role="alert" className="error">{error}</p>}<div className="actions"><button className="secondary" onClick={close}>Close</button><button disabled={pending||count===0||(needsText&&!text.trim())} onClick={confirm}>{pending?"Applying…":"Confirm"}</button></div></section>;}
