import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import { learningApi } from '../../api/learningApi';
import { friendlyError } from '../../api/errors';
import { useAppStore } from '../../app/store';
import { AppHeader } from '../../components/AppHeader';
import { Screen } from '../../components/Screen';
import { Button, Card, EmptyState, ErrorState, Loading, ProgressBar } from '../../components/ui';
import type { RootStackParamList } from '../../navigation/types';
import { theme } from '../../theme';
import { useEffect, useRef, useState } from 'react';

export function TopicLessonScreen({navigation,route}:NativeStackScreenProps<RootStackParamList,'TopicLesson'>){
 const identity=useAppStore(s=>s.learnerIdentity);const client=useQueryClient();const query=useQuery({queryKey:['lesson',identity,route.params.topicId],queryFn:()=>learningApi.lesson(identity,route.params.topicId),enabled:Boolean(identity)});
 const [index,setIndex]=useState(0);const [saveError,setSaveError]=useState(false);const initializedTopic=useRef<string|undefined>(undefined);
 useEffect(()=>{if(query.data&&initializedTopic.current!==query.data.topicId){const target=route.params.sectionId??query.data.progress.lastSectionId;setIndex(Math.max(0,query.data.sections.findIndex(s=>s.sectionId===target)));initializedTopic.current=query.data.topicId;}},[query.data,route.params.sectionId]);
 const mutation=useMutation({mutationFn:({sectionId,completed}:{sectionId:string;completed:boolean})=>learningApi.updateLessonProgress(identity,route.params.topicId,sectionId,completed),retry:2,onSuccess:progress=>{setSaveError(false);client.setQueryData(['lesson',identity,route.params.topicId],(lesson:typeof query.data)=>lesson?{...lesson,progress}:lesson);void client.invalidateQueries({queryKey:['continue-learning']});void client.invalidateQueries({queryKey:['study-topics']});},onError:()=>setSaveError(true)});
 useEffect(()=>{const section=query.data?.sections[index];if(section)mutation.mutate({sectionId:section.sectionId,completed:false});},[index,query.data?.topicId]);
 if(query.isPending)return <Screen><Loading label="Loading lesson…"/></Screen>;if(query.isError)return <Screen><AppHeader onBack={()=>navigation.goBack()}/><ErrorState message={friendlyError(query.error)} retry={()=>query.refetch()}/></Screen>;if(!query.data.sections.length)return <Screen><EmptyState message="This topic is not available for study yet."/></Screen>;
 const lesson=query.data,section=lesson.sections[index],last=index===lesson.sections.length-1;const completed=Math.max(lesson.progress.completedSectionCount,index);const finish=()=>mutation.mutate({sectionId:section.sectionId,completed:true},{onSuccess:()=>{if(!last)setIndex(value=>value+1);}});
 if(lesson.progress.completed&&last)return <Screen><AppHeader onBack={()=>navigation.goBack()}/><Card><Text accessibilityRole="header" style={styles.title}>Topic completed</Text><Text style={styles.body}>You reviewed {lesson.sections.length} key facts.</Text><Button label="Practice this topic" onPress={()=>navigation.navigate('PracticeSetup',{mode:'TOPIC',topicId:lesson.topicId,topicName:lesson.title})}/><Button label="Back to topics" variant="secondary" onPress={()=>navigation.goBack()}/></Card></Screen>;
 return <Screen><AppHeader onBack={()=>navigation.goBack()} action="help"/><Text style={styles.eyebrow}>KEY FACT {index+1} OF {lesson.sections.length}</Text><Text accessibilityRole="header" style={styles.title}>{lesson.title}</Text><ProgressBar value={(index+1)*100/lesson.sections.length} accessibilityLabel={`Section ${index+1} of ${lesson.sections.length}`}/><Card><Text accessibilityRole="header" style={styles.sectionTitle}>{section.title}</Text><Text style={styles.body}>{section.explanation}</Text>{section.sourceLinks.length>0&&<View style={styles.sources}><Text style={styles.sourceHeading}>Sources</Text>{section.sourceLinks.map(source=><Pressable accessibilityRole="link" accessibilityLabel={`Open source ${source.title}`} key={source.url} onPress={()=>void Linking.openURL(source.url)}><Text style={styles.link}>{source.title}</Text></Pressable>)}</View>}</Card>{saveError&&<Text accessibilityRole="alert" style={styles.error}>Your progress could not be saved. It will retry automatically.</Text>}<View style={styles.controls}>{index>0&&<View style={styles.control}><Button label="Previous" variant="secondary" onPress={()=>setIndex(value=>value-1)}/></View>}<View style={styles.control}><Button label={last?'Complete lesson':'Next'} onPress={finish} disabled={mutation.isPending}/></View></View><Button label="Practice this topic" variant="secondary" onPress={()=>navigation.navigate('PracticeSetup',{mode:'TOPIC',topicId:lesson.topicId,topicName:lesson.title})}/><Text style={styles.meta}>{completed} of {lesson.sections.length} key facts reviewed · about {Math.max(1,Math.ceil(lesson.readingTimeSeconds/60))} min</Text></Screen>
}
const styles=StyleSheet.create({eyebrow:{color:theme.colors.primary,...theme.typography.label,marginTop:theme.spacing.xs},title:{color:theme.colors.text,...theme.typography.heading},sectionTitle:{color:theme.colors.primary,...theme.typography.subheading},body:{color:theme.colors.text,...theme.typography.bodyLarge,lineHeight:28},sources:{borderTopColor:theme.colors.divider,borderTopWidth:1,gap:8,marginTop:theme.spacing.sm,paddingTop:theme.spacing.sm},sourceHeading:{color:theme.colors.text,...theme.typography.label},link:{color:theme.colors.primary,...theme.typography.body,textDecorationLine:'underline'},controls:{flexDirection:'row',gap:theme.spacing.sm},control:{flex:1},error:{color:theme.colors.error,...theme.typography.caption},meta:{color:theme.colors.muted,...theme.typography.caption,textAlign:'center'}});
