package se.medbo.examplatform.content.source;

import java.net.URI;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.slf4j.Logger; import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import se.medbo.examplatform.content.shared.DomainException;

@Service
public class SourceService {
    private static final Logger LOG=LoggerFactory.getLogger(SourceService.class);
    private static final List<String> TYPES=List.of("GOVERNMENT_WEBPAGE","GOVERNMENT_DOCUMENT","LEGISLATION","PUBLIC_AUTHORITY_GUIDANCE","LICENSED_MATERIAL","INTERNAL_RESEARCH","OTHER");
    private final JdbcClient jdbc; public SourceService(JdbcClient jdbc){this.jdbc=jdbc;}
    private static final String FIELDS="id,publisher,title,url,source_type AS \"sourceType\",document_version AS \"documentVersion\",publication_date AS \"publicationDate\",accessed_at AS \"accessedAt\",copyright_notes AS \"copyrightNotes\",internal_notes AS \"internalNotes\",content_text AS \"contentText\",content_checksum AS \"contentChecksum\",review_status AS \"reviewStatus\",status,replacement_source_id AS \"replacementSourceId\",created_at AS \"createdAt\",updated_at AS \"updatedAt\",version";
    public record Input(String publisher,String title,String url,String sourceType,String documentVersion,LocalDate publicationDate,LocalDate accessedAt,String copyrightNotes,String internalNotes,String contentText,UUID replacementSourceId,Long version){}
    public record Retire(UUID replacementSourceId,Long version){}

    public Map<String,Object> list(int page,int size,String search,String publisher,String type,String review,String status,LocalDate before,LocalDate after){size=Math.min(Math.max(size,1),100);page=Math.max(page,0);String w=" WHERE (CAST(:search AS text) IS NULL OR lower(title) LIKE lower('%'||:search||'%')) AND (CAST(:publisher AS text) IS NULL OR lower(publisher) LIKE lower('%'||:publisher||'%')) AND (CAST(:type AS text) IS NULL OR source_type=:type) AND (CAST(:review AS text) IS NULL OR review_status=:review) AND (CAST(:status AS text) IS NULL OR status=:status) AND (CAST(:before AS date) IS NULL OR accessed_at<:before) AND (CAST(:after AS date) IS NULL OR accessed_at>:after) ";var q=jdbc.sql("SELECT count(*) FROM source_reference"+w);params(q,search,publisher,type,review,status,before,after);long total=q.query(Long.class).single();var data=jdbc.sql("SELECT "+FIELDS+" FROM source_reference"+w+" ORDER BY updated_at DESC,id LIMIT :size OFFSET :offset");params(data,search,publisher,type,review,status,before,after);var items=data.param("size",size).param("offset",page*size).query().listOfRows();return Map.of("items",items,"page",page,"size",size,"totalItems",total,"totalPages",(total+size-1)/size);}
    @Transactional public Map<String,Object> create(Input in){validate(in);var id=UUID.randomUUID();var now=OffsetDateTime.now(ZoneOffset.UTC);String content=blank(in.contentText());jdbc.sql("INSERT INTO source_reference(id,publisher,title,url,source_type,document_version,publication_date,accessed_at,copyright_notes,internal_notes,content_text,content_checksum,review_status,status,created_at,updated_at) VALUES(:id,:publisher,:title,:url,:type,:document,:published,:accessed,:copyright,:internal,:content,:checksum,'UNREVIEWED','ACTIVE',:now,:now)").param("id",id).param("publisher",in.publisher()).param("title",in.title()).param("url",blank(in.url())).param("type",in.sourceType()).param("document",blank(in.documentVersion())).param("published",in.publicationDate()).param("accessed",in.accessedAt()).param("copyright",blank(in.copyrightNotes())).param("internal",blank(in.internalNotes())).param("content",content,java.sql.Types.VARCHAR).param("checksum",checksum(content),java.sql.Types.VARCHAR).param("now",now).update();log("source.created",id);return get(id);}
    public Map<String,Object> get(UUID id){var rows=jdbc.sql("SELECT "+FIELDS+" FROM source_reference WHERE id=:id").param("id",id).query().listOfRows();if(rows.isEmpty())throw DomainException.notFound("Source");return rows.getFirst();}
    @Transactional public Map<String,Object> update(UUID id,Input in){validate(in);expect(in.version());String content=blank(in.contentText());int c=jdbc.sql("UPDATE source_reference SET publisher=:publisher,title=:title,url=:url,source_type=:type,document_version=:document,publication_date=:published,accessed_at=:accessed,copyright_notes=:copyright,internal_notes=:internal,content_text=:content,content_checksum=:checksum,updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND status='ACTIVE'").param("publisher",in.publisher()).param("title",in.title()).param("url",blank(in.url())).param("type",in.sourceType()).param("document",blank(in.documentVersion())).param("published",in.publicationDate()).param("accessed",in.accessedAt()).param("copyright",blank(in.copyrightNotes())).param("internal",blank(in.internalNotes())).param("content",content,java.sql.Types.VARCHAR).param("checksum",checksum(content),java.sql.Types.VARCHAR).param("now",OffsetDateTime.now(ZoneOffset.UTC)).param("id",id).param("version",in.version()).update();changed(c,id);return get(id);}
    @Transactional public Map<String,Object> review(UUID id,long v){return transition(id,v,"review_status='REVIEWED'","source.reviewed");}
    @Transactional public Map<String,Object> requireUpdate(UUID id,long v){return transition(id,v,"review_status='REQUIRES_UPDATE'","source.requires_update");}
    @Transactional public Map<String,Object> retire(UUID id,Retire r){expect(r.version());if(id.equals(r.replacementSourceId()))throw DomainException.conflict("A source cannot replace itself");if(r.replacementSourceId()!=null){var replacement=get(r.replacementSourceId());if("RETIRED".equals(replacement.get("status")))throw DomainException.conflict("Replacement source must be active");}int c=jdbc.sql("UPDATE source_reference SET status='RETIRED',replacement_source_id=:replacement,updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND status='ACTIVE'").param("replacement",r.replacementSourceId()).param("now",OffsetDateTime.now(ZoneOffset.UTC)).param("id",id).param("version",r.version()).update();changed(c,id);log("source.retired",id);return get(id);}
    private Map<String,Object> transition(UUID id,long v,String set,String action){int c=jdbc.sql("UPDATE source_reference SET "+set+",updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND status='ACTIVE'").param("now",OffsetDateTime.now(ZoneOffset.UTC)).param("id",id).param("version",v).update();changed(c,id);log(action,id);return get(id);}
    private void validate(Input in){if(in.publisher()==null||in.publisher().isBlank())bad("publisher is required");if(in.title()==null||in.title().isBlank())bad("title is required");if(in.accessedAt()==null)bad("accessedAt is required");if(!TYPES.contains(in.sourceType()))bad("Invalid sourceType");if(in.url()!=null&&!in.url().isBlank()){try{var uri=URI.create(in.url());if(uri.getScheme()==null||uri.getHost()==null)bad("url must be absolute");if(List.of("GOVERNMENT_WEBPAGE","GOVERNMENT_DOCUMENT","PUBLIC_AUTHORITY_GUIDANCE").contains(in.sourceType())&&!"https".equalsIgnoreCase(uri.getScheme()))bad("Government and public authority URLs must use HTTPS");}catch(IllegalArgumentException e){bad("url must be valid");}}}
    private void changed(int c,UUID id){if(c==0){get(id);throw DomainException.conflict("The source was changed, retired, or is no longer editable");}}
    private void expect(Long v){if(v==null||v<0)bad("version is required");}
    private void bad(String m){throw new DomainException(HttpStatus.UNPROCESSABLE_ENTITY,"VALIDATION_ERROR",m);}
    private String blank(String s){return s==null||s.isBlank()?null:s;}
    private String checksum(String value){if(value==null)return null;try{var bytes=java.security.MessageDigest.getInstance("SHA-256").digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8));return java.util.HexFormat.of().formatHex(bytes);}catch(java.security.NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
    private void params(JdbcClient.StatementSpec q,String search,String publisher,String type,String review,String status,LocalDate before,LocalDate after){q.param("search",blank(search)).param("publisher",blank(publisher)).param("type",blank(type)).param("review",blank(review)).param("status",blank(status)).param("before",before).param("after",after);}
    private void log(String action,UUID id){LOG.info("content_action={} actor={} entity_id={}",action,SecurityContextHolder.getContext().getAuthentication().getName(),id);}
}
