import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { listQuestions,type FactReviewStatus,type FactStatus,type QuestionDifficulty,type QuestionType } from '../../../api/generated';
import { contentServiceClient } from '../../../api/client/contentServiceClient';
import { unwrap } from '../../../api/client/adminApi';
import { adminQueryKeys } from '../../../api/query-keys/adminQueryKeys';
import { AsyncState } from '../../../components/AsyncState';
import { EmptyState, PageHeader, StatusBadge, TableFrame } from '../../../components/AdminUi';
import { AdminIcon } from '../../../components/AdminIcon';

export function QuestionListPage(){
  const[search,setSearch]=useState('');const[type,setType]=useState('');const[difficulty,setDifficulty]=useState('');const[review,setReview]=useState('');const[status,setStatus]=useState('');const[page,setPage]=useState(0);
  const filters={search,type,difficulty,review,status,page};
  const query=useQuery({queryKey:adminQueryKeys.questions.list(filters),queryFn:()=>unwrap(listQuestions({client:contentServiceClient,query:{page,size:20,search:search||undefined,questionType:(type||undefined)as QuestionType|undefined,difficulty:(difficulty||undefined)as QuestionDifficulty|undefined,reviewStatus:(review||undefined)as FactReviewStatus|undefined,status:(status||undefined)as FactStatus|undefined}}))});
  return <><PageHeader eyebrow="Question bank" title="Questions" description="Source-backed assessment items linked to approved knowledge facts." actions={<Link className="button" to="/questions/new"><AdminIcon name="plus"/>Create question</Link>} />
    <div className="filters" aria-label="Question filters"><label>Search<input value={search} placeholder="Search question text or code" onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option><option>SINGLE_CHOICE</option><option>MULTIPLE_CHOICE</option><option>TRUE_FALSE</option></select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">All difficulties</option><option>EASY</option><option>MEDIUM</option><option>HARD</option></select></label><label>Review<select value={review} onChange={e=>setReview(e.target.value)}><option value="">All review states</option><option>UNREVIEWED</option><option>UNDER_REVIEW</option><option>APPROVED</option><option>REJECTED</option><option>REQUIRES_UPDATE</option></select></label><label>Lifecycle<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All lifecycle states</option><option>DRAFT</option><option>ACTIVE</option><option>RETIRED</option></select></label></div>
    <AsyncState loading={query.isPending} error={query.error}>{query.data?.items.length===0?<EmptyState title="No questions match these filters." description="Adjust the filters or create a new question."/>:<TableFrame><table><caption className="sr-only">Question bank</caption><thead><tr><th>Question</th><th>Type</th><th>Difficulty</th><th>Objective</th><th>Review</th><th>Lifecycle</th><th>Facts</th><th>Updated</th></tr></thead><tbody>{query.data?.items.map(q=><tr key={q.id}><td><Link className="table-primary" to={`/questions/${q.id}`}>{q.questionText}</Link><br/><small>{q.code}</small></td><td>{q.questionType.replaceAll('_',' ')}</td><td><StatusBadge value={q.difficulty}/></td><td>{q.learningObjectiveTitle}</td><td><StatusBadge value={q.reviewStatus}/></td><td><StatusBadge value={q.status}/></td><td>{q.knowledgeFactCount}</td><td>{new Date(q.updatedAt).toLocaleDateString()}</td></tr>)}</tbody></table></TableFrame>}<nav className="pager" aria-label="Question pages"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1} of {Math.max(query.data?.totalPages??1,1)}</span><button disabled={!query.data||page+1>=query.data.totalPages} onClick={()=>setPage(p=>p+1)}>Next</button></nav></AsyncState></>;
}
