package se.medbo.examplatform.ai.provider;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicReference;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Component;

@Component
final class CloudflareWorkersAiFreeProvider implements StructuredAiProvider {
  private final ObjectMapper mapper;private final JdbcClient jdbc;private final HttpClient http;private final String account,key,model,base;private final boolean enabled,freeOnly;private final long limit;private final AtomicLong used=new AtomicLong();private final AtomicReference<java.time.LocalDate> usageDay=new AtomicReference<>(java.time.LocalDate.now(ZoneOffset.UTC));private volatile boolean loaded;private final Duration timeout;
  CloudflareWorkersAiFreeProvider(ObjectMapper mapper,JdbcClient jdbc,@Value("${ai.cloudflare.account-id:}")String account,@Value("${ai.cloudflare.api-token:}")String key,@Value("${ai.cloudflare.model:}")String model,@Value("${ai.cloudflare.base-url:https://api.cloudflare.com/client/v4}")String base,@Value("${ai.cloudflare.enabled:false}")boolean enabled,@Value("${ai.cloudflare.free-only:true}")boolean freeOnly,@Value("${ai.cloudflare.daily-neuron-limit:10000}")long limit,@Value("${ai.cloudflare.timeout-seconds:45}")long seconds){this.mapper=mapper;this.jdbc=jdbc;this.account=account;this.key=key;this.model=model;this.base=official(base);this.enabled=enabled;this.freeOnly=freeOnly;this.limit=limit;this.timeout=Duration.ofSeconds(Math.max(1,seconds));this.http=HttpClient.newBuilder().connectTimeout(timeout).build();}
  public String provider(){return "CLOUDFLARE_WORKERS_AI";}public String model(){return model;}public int priority(){return 3;}public boolean enabled(){return enabled;}public boolean credentialsConfigured(){return !account.isBlank()&&!key.isBlank()&&!model.isBlank();}public Capabilities capabilities(){return new Capabilities(true,true,true,true,true,true,32_000,4096,false,true,false);}
  public Availability availability(Request r){resetIfNeeded();load();if(!enabled)return no("DISABLED",FreeStatus.UNKNOWN);if(!credentialsConfigured())return no("MISSING_CREDENTIALS",FreeStatus.UNKNOWN);if(!freeOnly||limit<=0)return no("FREE_STATUS_UNVERIFIED",FreeStatus.UNKNOWN);long remaining=Math.max(0,limit-used.get());long estimate=r==null?0:Math.max(1,(r.prompt().length()+r.systemInstruction().length())/1000);boolean ready=remaining>estimate;return new Availability(ready,ready?"READY":"FREE_QUOTA_EXHAUSTED",FreeStatus.KNOWN,CapacityAuthority.LOCAL_ESTIMATE,ready?"CLOSED":"QUOTA_PAUSED",ready?null:reset(),Map.of("neuronLimit",limit,"neuronsUsed",used.get(),"neuronsRemaining",remaining));}
  public Response execute(Request r){var a=availability(r);if(!a.eligible())throw new AiProviderException("AI_FREE_QUOTA_PAUSED",false,"Cloudflare free neuron allocation is unavailable");long estimate=Math.max(1,(r.prompt().length()+r.systemInstruction().length())/1000);try{var body=Map.of("messages",List.of(Map.of("role","system","content",r.systemInstruction()),Map.of("role","user","content",r.prompt())),"response_format",Map.of("type","json_schema","json_schema",r.jsonSchema()),"max_tokens",r.maximumOutputTokens(),"temperature",r.temperature());var request=HttpRequest.newBuilder(URI.create(base+"/accounts/"+URLEncoder.encode(account,StandardCharsets.UTF_8)+"/ai/run/"+model)).timeout(timeout).header("Authorization","Bearer "+key).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(mapper.writeValueAsString(body))).build();long start=System.nanoTime();var response=http.send(request,HttpResponse.BodyHandlers.ofString());if(response.statusCode()==429)throw new AiProviderException("AI_PROVIDER_TEMPORARILY_RATE_LIMITED",true,"Cloudflare free allocation is rate limited");if(response.statusCode()/100!=2)throw new AiProviderException(response.statusCode()>=500?"AI_PROVIDER_UNAVAILABLE":"AI_PROVIDER_RESPONSE_INVALID",response.statusCode()>=500,"Cloudflare rejected the request");JsonNode root=mapper.readTree(response.body()),result=root.path("result");String text=result.path("response").asText(result.path("text").asText());JsonNode structured=mapper.readTree(text);long neurons=result.path("usage").path("neurons").asLong(estimate);used.addAndGet(neurons);Integer input=intOrNull(result.path("usage"),"prompt_tokens"),output=intOrNull(result.path("usage"),"completion_tokens");return new Response(structured,provider(),model,model,response.headers().firstValue("cf-ray").orElse(null),input,output,(System.nanoTime()-start)/1_000_000,result.path("finish_reason").asText(null),Map.of(),Map.of("neurons",neurons),null,"HTTP_200",true);}catch(AiProviderException e){throw e;}catch(java.net.http.HttpTimeoutException e){throw new AiProviderException("AI_REQUEST_TIMEOUT",true,"Cloudflare request timed out");}catch(InterruptedException e){Thread.currentThread().interrupt();throw new AiProviderException("AI_REQUEST_CANCELLED",false,"Cloudflare request was cancelled");}catch(Exception e){throw new AiProviderException("AI_PROVIDER_RESPONSE_INVALID",false,"Cloudflare returned invalid structured JSON");}}
  private synchronized void load(){if(loaded)return;loaded=true;var rows=jdbc.sql("SELECT neurons_used FROM ai_provider_capacity_snapshot WHERE provider='CLOUDFLARE_WORKERS_AI' AND model=:model AND refreshed_at>=date_trunc('day',now() AT TIME ZONE 'UTC') ORDER BY refreshed_at DESC LIMIT 1").param("model",model).query().listOfRows();if(!rows.isEmpty()&&rows.getFirst().get("neurons_used") instanceof Number n)used.set(n.longValue());}private void resetIfNeeded(){var today=java.time.LocalDate.now(ZoneOffset.UTC);var previous=usageDay.get();if(!today.equals(previous)&&usageDay.compareAndSet(previous,today)){used.set(0);loaded=true;}}private OffsetDateTime reset(){return OffsetDateTime.now(ZoneOffset.UTC).toLocalDate().plusDays(1).atStartOfDay().atOffset(ZoneOffset.UTC);}private Availability no(String r,FreeStatus s){return new Availability(false,r,s,CapacityAuthority.CONFIGURATION,"UNKNOWN",null,Map.of());}private Integer intOrNull(JsonNode n,String k){return n.has(k)?n.get(k).asInt():null;}private String official(String v){URI u=URI.create(v);if(!"https".equalsIgnoreCase(u.getScheme())||!"api.cloudflare.com".equalsIgnoreCase(u.getHost())||u.getUserInfo()!=null)throw new IllegalArgumentException("Cloudflare base URL must be official HTTPS");return v.replaceAll("/+$","");}
}
