package se.medbo.examplatform.ai.provider;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

@Component
final class GeminiStructuredProvider implements StructuredAiProvider {
  private final ObjectMapper mapper;private final GeminiQuotaService quota;private final HttpClient http;
  private final String key,model,base,version;private final boolean enabled,freeOnly;private final Duration timeout;
  GeminiStructuredProvider(ObjectMapper mapper,GeminiQuotaService quota,
      @Value("${ai.gemini.api-key:}")String key,@Value("${ai.editorial.model:gemini-3.1-flash-lite}")String model,
      @Value("${ai.gemini.base-url:https://generativelanguage.googleapis.com}")String base,
      @Value("${ai.gemini.api-version:v1beta}")String version,@Value("${ai.gemini.timeout-seconds:60}")long seconds,
      @Value("${ai.gemini.enabled:true}")boolean enabled,@Value("${ai.gemini.free-only:true}")boolean freeOnly){this.mapper=mapper;this.quota=quota;this.key=key;this.model=model;this.base=official(base,"generativelanguage.googleapis.com");this.version=version;this.timeout=Duration.ofSeconds(Math.max(1,seconds));this.http=HttpClient.newBuilder().connectTimeout(timeout).build();this.enabled=enabled;this.freeOnly=freeOnly;}
  public String provider(){return "GEMINI";}public String model(){return model;}public int priority(){return 1;}public boolean enabled(){return enabled;}public boolean credentialsConfigured(){return !key.isBlank();}
  public Capabilities capabilities(){return new Capabilities(true,true,true,true,true,true,1_000_000,4096,true,true,true);}
  public Availability availability(Request request){if(!enabled)return unavailable("DISABLED",FreeStatus.UNKNOWN,null);if(key.isBlank())return unavailable("MISSING_CREDENTIALS",FreeStatus.UNKNOWN,null);if(!freeOnly)return unavailable("FREE_STATUS_UNVERIFIED",FreeStatus.UNKNOWN,null);try{var s=quota.status();String state=String.valueOf(s.get("state"));OffsetDateTime retry=date(s.get("pausedUntil"));boolean ready=List.of("CLOSED","WARNING","CRITICAL").contains(state);return new Availability(ready,ready?"READY":state.equals("QUOTA_PAUSED")?"FREE_QUOTA_EXHAUSTED":"CIRCUIT_OPEN",FreeStatus.KNOWN,CapacityAuthority.LOCAL_ESTIMATE,state,retry,map(s.get("usage")));}catch(Exception e){return unavailable("PROVIDER_UNHEALTHY",FreeStatus.UNKNOWN,null);}}
  public Response execute(Request r){int estimate=Math.max(1,(r.systemInstruction().length()+r.prompt().length()+3)/4);GeminiQuotaService.Reservation reservation;try{reservation=quota.reserve(estimate,r.jobId(),r.operation(),r.requester(),r.retryAttempt());}catch(RuntimeException e){throw mapped(e);}long start=System.nanoTime();try{var body=Map.of("system_instruction",Map.of("parts",List.of(Map.of("text",r.systemInstruction()))),"contents",List.of(Map.of("role","user","parts",List.of(Map.of("text",r.prompt())))),"generationConfig",Map.of("responseMimeType","application/json","responseJsonSchema",r.jsonSchema(),"maxOutputTokens",r.maximumOutputTokens(),"temperature",r.temperature()));var request=HttpRequest.newBuilder(URI.create(base+"/"+version+"/models/"+URLEncoder.encode(model,StandardCharsets.UTF_8)+":generateContent")).timeout(timeout).header("Content-Type","application/json").header("x-goog-api-key",key).POST(HttpRequest.BodyPublishers.ofString(mapper.writeValueAsString(body))).build();var response=http.send(request,HttpResponse.BodyHandlers.ofString());String requestId=response.headers().firstValue("x-goog-request-id").orElse(response.headers().firstValue("x-request-id").orElse(null));if(response.statusCode()/100!=2){error(reservation,response.statusCode(),response.body());}JsonNode root=mapper.readTree(response.body()),parts=root.path("candidates").path(0).path("content").path("parts");if(!parts.isArray()||parts.isEmpty())throw new AiProviderException("AI_PROVIDER_RESPONSE_INVALID",false,"Gemini returned no structured candidate");JsonNode structured=mapper.readTree(parts.path(0).path("text").asText());JsonNode usage=root.path("usageMetadata");Integer input=integer(usage,"promptTokenCount"),output=integer(usage,"candidatesTokenCount");quota.success(reservation,input,output,requestId);return new Response(structured,provider(),model,model,requestId,input,output,(System.nanoTime()-start)/1_000_000,root.path("candidates").path(0).path("finishReason").asText(null),Map.of(),Map.of(),null,"HTTP_200",true);
    }catch(AiProviderException e){throw e;}catch(java.net.http.HttpTimeoutException e){quota.failure(reservation,"TIMEOUT",false);throw new AiProviderException("AI_REQUEST_TIMEOUT",true,"Gemini request timed out");}catch(InterruptedException e){Thread.currentThread().interrupt();quota.failure(reservation,"CANCELLED",false);throw new AiProviderException("AI_REQUEST_CANCELLED",false,"Gemini request was cancelled");}catch(Exception e){quota.failure(reservation,"CLIENT_FAILURE",false);throw new AiProviderException("AI_PROVIDER_RESPONSE_INVALID",false,"Gemini returned an invalid response");}}
  private void error(GeminiQuotaService.Reservation r,int status,String body){String lower=body==null?"":body.toLowerCase();if(status==429){boolean daily=lower.contains("per day")||lower.contains("daily");String code=daily?"AI_PROVIDER_DAILY_QUOTA_EXHAUSTED":"AI_PROVIDER_TEMPORARILY_RATE_LIMITED";quota.rateLimited(r,code,daily);throw new AiProviderException(code,!daily,"Gemini free quota is unavailable");}quota.failure(r,"HTTP_"+status,status==401||status==403||status==404);if(status==404)throw new AiProviderException("AI_PROVIDER_MODEL_UNAVAILABLE",false,"Gemini model is unavailable");if(status==408||status>=500)throw new AiProviderException("AI_PROVIDER_UNAVAILABLE",true,"Gemini is unavailable");throw new AiProviderException("AI_PROVIDER_RESPONSE_INVALID",false,"Gemini rejected the request");}
  private AiProviderException mapped(RuntimeException e){return new AiProviderException(e instanceof se.medbo.examplatform.ai.generation.AiApiException a?a.code():"AI_QUOTA_RESERVATION_FAILED",false,e.getMessage());}private Availability unavailable(String reason,FreeStatus status,OffsetDateTime retry){return new Availability(false,reason,status,CapacityAuthority.CONFIGURATION,"UNKNOWN",retry,Map.of());}@SuppressWarnings("unchecked")private Map<String,Object> map(Object v){return v instanceof Map<?,?> m?(Map<String,Object>)m:Map.of();}private Integer integer(JsonNode n,String k){return n.has(k)&&n.get(k).canConvertToInt()?n.get(k).asInt():null;}private OffsetDateTime date(Object v){if(v==null)return null;try{return v instanceof OffsetDateTime d?d:OffsetDateTime.parse(String.valueOf(v));}catch(Exception e){return null;}}private String official(String value,String host){URI uri=URI.create(value);if(!"https".equalsIgnoreCase(uri.getScheme())||!host.equalsIgnoreCase(uri.getHost())||uri.getUserInfo()!=null)throw new IllegalArgumentException("Provider base URL must be the official HTTPS endpoint");return value.replaceAll("/+$","");}
}
