package se.medbo.examplatform.ai.provider;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

abstract class OpenAiCompatibleFreeProvider implements StructuredAiProvider {
  final ObjectMapper mapper;final HttpClient http;final String key,model,base;final boolean enabled,freeOnly;final Duration timeout;
  OpenAiCompatibleFreeProvider(ObjectMapper mapper,String key,String model,String base,String officialHost,boolean enabled,boolean freeOnly,long timeoutSeconds){this.mapper=mapper;this.key=key;this.model=model;this.base=official(base,officialHost);this.enabled=enabled;this.freeOnly=freeOnly;this.timeout=Duration.ofSeconds(Math.max(1,timeoutSeconds));this.http=HttpClient.newBuilder().connectTimeout(timeout).build();}
  public String model(){return model;}public boolean enabled(){return enabled;}public boolean credentialsConfigured(){return !key.isBlank()&&!model.isBlank();}public Capabilities capabilities(){return new Capabilities(true,true,true,true,true,true,128_000,4096,true,true,true);}
  public Response execute(Request r){long start=System.nanoTime();try{var response=http.send(build(r),HttpResponse.BodyHandlers.ofString());var limits=rateLimits(response);if(response.statusCode()/100!=2)throw classify(response.statusCode(),response.body(),limits);JsonNode root=mapper.readTree(response.body());String content=root.path("choices").path(0).path("message").path("content").asText();JsonNode structured=mapper.readTree(content);JsonNode usage=root.path("usage");String actual=root.path("model").asText(model);if(!responseConfirmedFree(root,actual))throw new AiProviderException("AI_PROVIDER_FREE_STATUS_UNVERIFIED",false,"Provider response did not confirm a zero-cost route");observed(limits,usage);return new Response(structured,provider(),model,actual,response.headers().firstValue("x-request-id").orElse(root.path("id").asText(null)),integer(usage,"prompt_tokens"),integer(usage,"completion_tokens"),(System.nanoTime()-start)/1_000_000,root.path("choices").path(0).path("finish_reason").asText(null),limits,Map.of(),retry(limits),"HTTP_"+response.statusCode(),true);}catch(AiProviderException e){throw e;}catch(java.net.http.HttpTimeoutException e){throw new AiProviderException("AI_REQUEST_TIMEOUT",true,provider()+" request timed out");}catch(InterruptedException e){Thread.currentThread().interrupt();throw new AiProviderException("AI_REQUEST_CANCELLED",false,provider()+" request was cancelled");}catch(Exception e){throw new AiProviderException("AI_PROVIDER_RESPONSE_INVALID",false,provider()+" returned invalid structured JSON");}}
  HttpRequest build(Request r)throws Exception{var format=Map.of("type","json_schema","json_schema",Map.of("name","editorial_response","strict",strictSchema(),"schema",r.jsonSchema()));var body=new LinkedHashMap<String,Object>();body.put("model",model);body.put("messages",List.of(Map.of("role","system","content",r.systemInstruction()),Map.of("role","user","content",r.prompt())));body.put("response_format",format);body.put("temperature",r.temperature());body.put("max_tokens",r.maximumOutputTokens());var builder=HttpRequest.newBuilder(URI.create(base+"/chat/completions")).timeout(timeout).header("Authorization","Bearer "+key).header("Content-Type","application/json");extraHeaders(builder);return builder.POST(HttpRequest.BodyPublishers.ofString(mapper.writeValueAsString(body))).build();}
  void extraHeaders(HttpRequest.Builder builder){}boolean strictSchema(){return true;}void observed(Map<String,Object> limits,JsonNode usage){}boolean responseConfirmedFree(JsonNode root,String actual){return freeOnly;}abstract Map<String,Object> rateLimits(HttpResponse<?> response);
  AiProviderException classify(int status,String body,Map<String,Object> limits){if(status==429)throw new AiProviderException("AI_PROVIDER_TEMPORARILY_RATE_LIMITED",true,provider()+" free capacity is rate limited");if(status==401||status==403)throw new AiProviderException("AI_PROVIDER_AUTHENTICATION_FAILED",false,provider()+" authentication failed");if(status==404)throw new AiProviderException("AI_PROVIDER_MODEL_UNAVAILABLE",false,provider()+" model is unavailable");if(status==408||status>=500)throw new AiProviderException("AI_PROVIDER_UNAVAILABLE",true,provider()+" is unavailable");return new AiProviderException("AI_PROVIDER_RESPONSE_INVALID",false,provider()+" rejected the request");}
  OffsetDateTime retry(Map<String,Object> limits){Object v=limits.get("retryAfterSeconds");return v instanceof Number n?OffsetDateTime.now(ZoneOffset.UTC).plusSeconds(n.longValue()):null;}Integer integer(JsonNode n,String k){return n.has(k)&&n.get(k).canConvertToInt()?n.get(k).asInt():null;}long number(String v,long fallback){try{return Long.parseLong(v);}catch(Exception e){return fallback;}}private String official(String value,String host){URI u=URI.create(value);if(!"https".equalsIgnoreCase(u.getScheme())||!host.equalsIgnoreCase(u.getHost())||u.getUserInfo()!=null||u.getPort()!=-1)throw new IllegalArgumentException("Provider base URL must be the official HTTPS endpoint");return value.replaceAll("/+$","");}
}
