package se.medbo.examplatform.content.release;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Types;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.slf4j.Logger;import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import se.medbo.examplatform.content.shared.DomainException;

@Service
public class ReleaseService {
    private static final Logger LOG=LoggerFactory.getLogger(ReleaseService.class);
    private static final String FIELDS="r.id,r.exam_id AS \"examId\",r.exam_version_id AS \"examVersionId\",r.release_number AS \"releaseNumber\",r.display_name AS \"displayName\",r.description,r.status,r.created_by AS \"createdBy\",r.created_at AS \"createdAt\",r.updated_at AS \"updatedAt\",r.validated_at AS \"validatedAt\",r.validated_by AS \"validatedBy\",r.published_at AS \"publishedAt\",r.published_by AS \"publishedBy\",r.delivered_at AS \"deliveredAt\",r.activated_at AS \"activatedAt\",r.retired_at AS \"retiredAt\",r.checksum,r.snapshot_schema_version AS \"snapshotSchemaVersion\",r.knowledge_fact_count AS \"knowledgeFactCount\",r.question_count AS \"questionCount\",r.last_validated_version AS \"lastValidatedVersion\",r.previous_release_id AS \"previousReleaseId\",r.version,e.name AS \"examName\",e.code AS \"examCode\",ev.display_name AS \"examVersionName\",ev.version_code AS \"examVersionCode\"";
    private final JdbcClient jdbc;private final ObjectMapper mapper;private final ReleaseSnapshotService snapshots;
    public ReleaseService(JdbcClient jdbc,ObjectMapper mapper,ReleaseSnapshotService snapshots){this.jdbc=jdbc;this.mapper=mapper;this.snapshots=snapshots;}
    public record ReleaseInput(UUID examVersionId,String releaseNumber,String displayName,String description,Long version){}
    public record SelectionInput(List<UUID> questionIds,List<UUID> factIds,Long version){}

    public Map<String,Object> list(int page,int size,String search,UUID examId,UUID examVersionId,String status,Boolean activeOnly){page=Math.max(0,page);size=Math.min(100,Math.max(1,size));var where=" WHERE (CAST(:search AS text) IS NULL OR lower(r.release_number) LIKE lower('%'||:search||'%') OR lower(r.display_name) LIKE lower('%'||:search||'%') OR lower(e.name) LIKE lower('%'||:search||'%')) AND (CAST(:exam AS uuid) IS NULL OR r.exam_id=:exam) AND (CAST(:examVersion AS uuid) IS NULL OR r.exam_version_id=:examVersion) AND (CAST(:status AS text) IS NULL OR r.status=:status) AND (:active=false OR r.status='ACTIVE') ";var count=jdbc.sql("SELECT count(*) FROM content_release r JOIN exam e ON e.id=r.exam_id"+where).param("search",blank(search)).param("exam",examId).param("examVersion",examVersionId).param("status",blank(status)).param("active",Boolean.TRUE.equals(activeOnly)).query(Long.class).single();var items=jdbc.sql("SELECT "+FIELDS+" FROM content_release r JOIN exam e ON e.id=r.exam_id JOIN exam_version ev ON ev.id=r.exam_version_id"+where+" ORDER BY r.updated_at DESC,r.id LIMIT :size OFFSET :offset").param("search",blank(search)).param("exam",examId).param("examVersion",examVersionId).param("status",blank(status)).param("active",Boolean.TRUE.equals(activeOnly)).param("size",size).param("offset",page*size).query().listOfRows();return Map.of("items",items,"page",page,"size",size,"totalItems",count,"totalPages",(count+size-1)/size);}
    public Map<String,Object> get(UUID id){var rows=jdbc.sql("SELECT "+FIELDS+" FROM content_release r JOIN exam e ON e.id=r.exam_id JOIN exam_version ev ON ev.id=r.exam_version_id WHERE r.id=:id").param("id",id).query().listOfRows();if(rows.isEmpty())throw notFound();var result=rows.getFirst();result.put("items",items(id));result.put("coverage",snapshots.coverage(id));result.put("validation",latestValidation(id));result.put("deliveryAttempts",deliveryAttempts(id));result.put("diff",diff(id));return result;}
    @Transactional public Map<String,Object> create(ReleaseInput in){validateInput(in);var exam=jdbc.sql("SELECT exam_id FROM exam_version WHERE id=:id").param("id",in.examVersionId()).query(UUID.class).optional().orElseThrow(()->new DomainException(HttpStatus.NOT_FOUND,"EXAM_VERSION_NOT_FOUND","Exam version was not found"));var id=UUID.randomUUID();var now=now();var previous=jdbc.sql("SELECT id FROM content_release WHERE exam_id=:exam AND status IN ('PUBLISHED','DELIVERED','ACTIVE','RETIRED') ORDER BY published_at DESC NULLS LAST LIMIT 1").param("exam",exam).query(UUID.class).optional().orElse(null);try{jdbc.sql("INSERT INTO content_release(id,exam_id,exam_version_id,release_number,display_name,description,status,created_by,created_at,updated_at,previous_release_id) VALUES(:id,:exam,:examVersion,:number,:name,:description,'DRAFT',:actor,:now,:now,:previous)").param("id",id).param("exam",exam).param("examVersion",in.examVersionId()).param("number",in.releaseNumber().trim()).param("name",in.displayName().trim()).param("description",blank(in.description()),Types.VARCHAR).param("actor",actor()).param("now",now).param("previous",previous,Types.OTHER).update();}catch(org.springframework.dao.DuplicateKeyException e){throw conflict("RELEASE_NUMBER_ALREADY_EXISTS","Release number already exists for this exam");}log("release.created",id);return get(id);}
    @Transactional public Map<String,Object> update(UUID id,ReleaseInput in){validateInput(in);expect(in.version());var current=get(id);editable(current);if(!in.examVersionId().equals(current.get("examVersionId")))throw validation("A release cannot move to another exam version");int changed=jdbc.sql("UPDATE content_release SET release_number=:number,display_name=:name,description=:description,status='DRAFT',validated_at=NULL,validated_by=NULL,last_validated_version=NULL,updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND status IN ('DRAFT','VALIDATED')").param("number",in.releaseNumber().trim()).param("name",in.displayName().trim()).param("description",blank(in.description()),Types.VARCHAR).param("now",now()).param("id",id).param("version",in.version()).update();changed(changed,id);return get(id);}
    @Transactional public Map<String,Object> selection(UUID id,SelectionInput in){expect(in.version());var release=get(id);editable(release);var questions=in.questionIds()==null?List.<UUID>of():in.questionIds().stream().distinct().toList();var facts=in.factIds()==null?List.<UUID>of():in.factIds().stream().distinct().toList();UUID examVersion=(UUID)release.get("examVersionId");var selections=new ArrayList<Selection>();int order=0;for(UUID q:questions){var row=eligibleQuestion(q,examVersion);UUID version=(UUID)row.get("versionId");selections.add(new Selection("QUESTION",q,version,(String)row.get("code"),order++,false));var dependencies=jdbc.sql("SELECT f.id,kfv.id AS \"versionId\" FROM question_knowledge_fact qkf JOIN knowledge_fact_version kfv ON kfv.id=qkf.knowledge_fact_version_id JOIN knowledge_fact f ON f.id=kfv.knowledge_fact_id WHERE qkf.question_version_id=:id ORDER BY f.id").param("id",version).query().listOfRows();for(var dependency:dependencies)if(selections.stream().noneMatch(s->s.versionId().equals(dependency.get("versionId"))))selections.add(new Selection("KNOWLEDGE_FACT",(UUID)dependency.get("id"),(UUID)dependency.get("versionId"),null,selections.stream().filter(s->"KNOWLEDGE_FACT".equals(s.type())).toList().size(),true));}
        for(UUID f:facts){var row=eligibleFact(f,examVersion);if(selections.stream().noneMatch(s->s.versionId().equals(row.get("versionId"))))selections.add(new Selection("KNOWLEDGE_FACT",f,(UUID)row.get("versionId"),null,selections.stream().filter(s->"KNOWLEDGE_FACT".equals(s.type())).toList().size(),false));}
        jdbc.sql("DELETE FROM content_release_item WHERE release_id=:id").param("id",id).update();var included=now();for(var s:selections)jdbc.sql("INSERT INTO content_release_item(id,release_id,content_type,content_id,content_version_id,content_code,display_order,automatic_dependency,included_at) VALUES(:id,:release,:type,:content,:contentVersion,:code,:order,:automatic,:now)").param("id",UUID.randomUUID()).param("release",id).param("type",s.type()).param("content",s.contentId()).param("contentVersion",s.versionId()).param("code",s.code(),Types.VARCHAR).param("order",s.order()).param("automatic",s.automatic()).param("now",included).update();long qc=selections.stream().filter(s->"QUESTION".equals(s.type())).count(),fc=selections.stream().filter(s->"KNOWLEDGE_FACT".equals(s.type())).count();int changed=jdbc.sql("UPDATE content_release SET status='DRAFT',question_count=:qc,knowledge_fact_count=:fc,validated_at=NULL,validated_by=NULL,last_validated_version=NULL,updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND status IN ('DRAFT','VALIDATED')").param("qc",qc).param("fc",fc).param("now",included).param("id",id).param("version",in.version()).update();changed(changed,id);log("release.selection_updated",id);return get(id);}
    public Map<String,Object> eligible(UUID id,String type,String search,UUID subject,UUID topic,UUID objective){var release=get(id);UUID ev=(UUID)release.get("examVersionId");String table="QUESTION".equals(type)?"question q JOIN question_version v ON v.id=q.current_version_id":"knowledge_fact q JOIN knowledge_fact_version v ON v.id=q.current_version_id";String text="QUESTION".equals(type)?"q.question_text":"q.canonical_statement";String code="QUESTION".equals(type)?"q.code":"NULL";return Map.of("items",jdbc.sql("SELECT q.id,v.id AS \"versionId\","+code+" AS code,"+text+" AS text,lo.id AS \"learningObjectiveId\",lo.title AS \"learningObjectiveTitle\",t.id AS \"topicId\",t.name AS \"topicName\",s.id AS \"subjectId\",s.name AS \"subjectName\" FROM "+table+" JOIN learning_objective lo ON lo.id=q.learning_objective_id JOIN topic t ON t.id=lo.topic_id JOIN subject s ON s.id=t.subject_id WHERE s.exam_version_id=:ev AND q.review_status='APPROVED' AND q.status='ACTIVE' AND (CAST(:search AS text) IS NULL OR lower("+text+") LIKE lower('%'||:search||'%')"+("QUESTION".equals(type)?" OR lower(q.code) LIKE lower('%'||:search||'%')":"")+") AND (CAST(:subject AS uuid) IS NULL OR s.id=:subject) AND (CAST(:topic AS uuid) IS NULL OR t.id=:topic) AND (CAST(:objective AS uuid) IS NULL OR lo.id=:objective) ORDER BY s.sort_order,t.sort_order,lo.title,"+text).param("ev",ev).param("search",blank(search)).param("subject",subject).param("topic",topic).param("objective",objective).query().listOfRows());}
    @Transactional public Map<String,Object> validate(UUID id,long version){var release=get(id);editable(release);if(((Number)release.get("version")).longValue()!=version)throw stale();var issues=new ArrayList<Map<String,Object>>();var selected=items(id);long questions=selected.stream().filter(i->"QUESTION".equals(i.get("contentType"))).count();if(questions==0)issues.add(issue("RELEASE_EMPTY","ERROR","Release must contain at least one question",null,null));for(var item:selected){if("QUESTION".equals(item.get("contentType")))validateQuestion(item,issues);else validateFact(item,issues);}var coverage=snapshots.coverage(id);if(questions<5)issues.add(issue("VERY_SMALL_RELEASE","WARNING","Release contains fewer than five questions",null,null));long errors=issues.stream().filter(i->"ERROR".equals(i.get("severity"))).count(),warnings=issues.stream().filter(i->"WARNING".equals(i.get("severity"))).count();boolean valid=errors==0;var report=Map.of("valid",valid,"errors",issues.stream().filter(i->"ERROR".equals(i.get("severity"))).toList(),"warnings",issues.stream().filter(i->"WARNING".equals(i.get("severity"))).toList(),"summary",coverage);var now=now();UUID run=UUID.randomUUID();try{jdbc.sql("INSERT INTO release_validation_run(id,release_id,valid,error_count,warning_count,validated_by,validated_at,release_version,report_json) VALUES(:id,:release,:valid,:errors,:warnings,:actor,:now,:version,CAST(:report AS jsonb))").param("id",run).param("release",id).param("valid",valid).param("errors",errors).param("warnings",warnings).param("actor",actor()).param("now",now).param("version",version).param("report",mapper.writeValueAsString(report)).update();}catch(Exception e){throw new IllegalStateException("Cannot persist validation report",e);}if(valid)jdbc.sql("UPDATE content_release SET status='VALIDATED',validated_at=:now,validated_by=:actor,last_validated_version=version+1,updated_at=:now,version=version+1 WHERE id=:id AND version=:version").param("now",now).param("actor",actor()).param("id",id).param("version",version).update();else jdbc.sql("UPDATE content_release SET status='DRAFT',validated_at=:now,validated_by=:actor,last_validated_version=NULL,updated_at=:now WHERE id=:id AND version=:version").param("now",now).param("actor",actor()).param("id",id).param("version",version).update();log(valid?"release.validation_succeeded":"release.validation_failed",id);return report;}
    @Transactional public Map<String,Object> publish(UUID id,long version){var release=get(id);if("PUBLISHED".equals(release.get("status"))||List.of("DELIVERED","ACTIVE","RETIRED","DELIVERY_FAILED").contains(release.get("status")))return release;if(!"VALIDATED".equals(release.get("status")))throw conflict("RELEASE_NOT_VALIDATED","Release must be validated before publication");if(((Number)release.get("version")).longValue()!=version)throw stale();if(!Long.valueOf(version).equals(((Number)release.get("lastValidatedVersion")).longValue()))throw conflict("RELEASE_VALIDATION_STALE","Release validation is stale");var publishedAt=now();var snapshot=snapshots.generate(id,publishedAt.toInstant());try{jdbc.sql("INSERT INTO published_release_snapshot(release_id,schema_version,checksum,snapshot_json,created_at,size_bytes) VALUES(:id,:schemaVersion,:checksum,CAST(:json AS jsonb),:now,:size)").param("id",id).param("schemaVersion",snapshot.snapshot().schemaVersion()).param("checksum",snapshot.checksum()).param("json",snapshot.json()).param("now",publishedAt).param("size",snapshot.sizeBytes()).update();}catch(org.springframework.dao.DuplicateKeyException e){return get(id);}int changed=jdbc.sql("UPDATE content_release SET status='PUBLISHED',published_at=:now,published_by=:actor,checksum=:checksum,snapshot_schema_version=:schemaVersion,updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND status='VALIDATED'").param("now",publishedAt).param("actor",actor()).param("checksum",snapshot.checksum()).param("schemaVersion",snapshot.snapshot().schemaVersion()).param("id",id).param("version",version).update();changed(changed,id);log("release.published",id);return get(id);}
    public Map<String,Object> snapshot(UUID id){get(id);var rows=jdbc.sql("SELECT snapshot_json::text AS snapshot,checksum,schema_version AS \"schemaVersion\",size_bytes AS \"sizeBytes\",created_at AS \"createdAt\" FROM published_release_snapshot WHERE release_id=:id").param("id",id).query().listOfRows();if(rows.isEmpty())throw conflict("RELEASE_NOT_PUBLISHED","Published snapshot is unavailable");var result=rows.getFirst();try{result.put("snapshot",mapper.readValue((String)result.get("snapshot"),Object.class));return result;}catch(Exception e){throw new IllegalStateException("Cannot read published snapshot",e);}}
    public Map<String,Object> preview(UUID id){var release=get(id);if(List.of("PUBLISHED","DELIVERY_FAILED","DELIVERED","ACTIVE","RETIRED").contains(release.get("status")))return snapshot(id);return snapshots.preview(id);}
    public List<Map<String,Object>> deliveryAttempts(UUID id){return jdbc.sql("SELECT id,attempt_number AS \"attemptNumber\",status,started_at AS \"startedAt\",completed_at AS \"completedAt\",target_service AS \"targetService\",response_code AS \"responseCode\",error_code AS \"errorCode\",error_message AS \"errorMessage\",checksum,requested_by AS \"requestedBy\" FROM release_delivery_attempt WHERE release_id=:id ORDER BY attempt_number DESC").param("id",id).query().listOfRows();}
    @Transactional public Map<String,Object> markDelivered(UUID id){jdbc.sql("UPDATE content_release SET status='DELIVERED',delivered_at=:now,updated_at=:now,version=version+1 WHERE id=:id AND status IN ('PUBLISHED','DELIVERY_FAILED')").param("now",now()).param("id",id).update();return get(id);}
    @Transactional public Map<String,Object> markDeliveryFailed(UUID id){jdbc.sql("UPDATE content_release SET status='DELIVERY_FAILED',updated_at=:now,version=version+1 WHERE id=:id AND status IN ('PUBLISHED','DELIVERY_FAILED')").param("now",now()).param("id",id).update();return get(id);}
    @Transactional public Map<String,Object> markActive(UUID id){var target=get(id);if("ACTIVE".equals(target.get("status")))return target;if(!"DELIVERED".equals(target.get("status")))throw conflict("RELEASE_NOT_DELIVERED","Only a delivered release can be activated");UUID exam=(UUID)target.get("examId");var previous=jdbc.sql("SELECT id FROM content_release WHERE exam_id=:exam AND status='ACTIVE' FOR UPDATE").param("exam",exam).query(UUID.class).optional();jdbc.sql("UPDATE content_release SET status='DELIVERED',updated_at=:now,version=version+1 WHERE exam_id=:exam AND status='ACTIVE'").param("now",now()).param("exam",exam).update();var now=now();jdbc.sql("UPDATE content_release SET status='ACTIVE',activated_at=:now,updated_at=:now,version=version+1 WHERE id=:id").param("now",now).param("id",id).update();var p=new java.util.HashMap<String,Object>();p.put("id",UUID.randomUUID());p.put("release",id);p.put("previous",previous.orElse(null));p.put("actor",actor());p.put("now",now);jdbc.sql("INSERT INTO release_activation_history(id,release_id,previous_active_release_id,activated_by,activated_at) VALUES(:id,:release,:previous,:actor,:now)").params(p).update();log(previous.isPresent()?"release.rollback_or_switch_activated":"release.activated",id);return get(id);}
    @Transactional public Map<String,Object> retire(UUID id,long version){var release=get(id);if("ACTIVE".equals(release.get("status")))throw conflict("ACTIVE_RELEASE_REQUIRED","Activate another release before retiring the active release");if(!List.of("PUBLISHED","DELIVERY_FAILED","DELIVERED").contains(release.get("status")))throw conflict("RELEASE_NOT_RETIRABLE","Release cannot be retired");int c=jdbc.sql("UPDATE content_release SET status='RETIRED',retired_at=:now,updated_at=:now,version=version+1 WHERE id=:id AND version=:version").param("now",now()).param("id",id).param("version",version).update();changed(c,id);return get(id);}
    public Map<String,Object> diff(UUID id){var release=jdbc.sql("SELECT previous_release_id FROM content_release WHERE id=:id").param("id",id).query(UUID.class).optional().orElse(null);if(release==null)return Map.of("questionsAdded",0,"questionsRemoved",0,"questionVersionsChanged",0,"factsAdded",0,"factsRemoved",0,"factVersionsChanged",0);return jdbc.sql("SELECT count(*) FILTER(WHERE current.content_type='QUESTION' AND previous.content_id IS NULL) AS \"questionsAdded\",count(*) FILTER(WHERE previous.content_type='QUESTION' AND current.content_id IS NULL) AS \"questionsRemoved\",count(*) FILTER(WHERE current.content_type='QUESTION' AND previous.content_version_id<>current.content_version_id) AS \"questionVersionsChanged\",count(*) FILTER(WHERE current.content_type='KNOWLEDGE_FACT' AND previous.content_id IS NULL) AS \"factsAdded\",count(*) FILTER(WHERE previous.content_type='KNOWLEDGE_FACT' AND current.content_id IS NULL) AS \"factsRemoved\",count(*) FILTER(WHERE current.content_type='KNOWLEDGE_FACT' AND previous.content_version_id<>current.content_version_id) AS \"factVersionsChanged\" FROM content_release_item current FULL JOIN content_release_item previous ON previous.release_id=:previous AND previous.content_type=current.content_type AND previous.content_id=current.content_id WHERE current.release_id=:current OR previous.release_id=:previous").param("previous",release).param("current",id).query().singleRow();}
    private Map<String,Object> eligibleQuestion(UUID id,UUID ev){var rows=jdbc.sql("SELECT q.current_version_id AS \"versionId\",q.code FROM question q JOIN learning_objective lo ON lo.id=q.learning_objective_id JOIN topic t ON t.id=lo.topic_id JOIN subject s ON s.id=t.subject_id WHERE q.id=:id AND s.exam_version_id=:ev AND q.review_status='APPROVED' AND q.status='ACTIVE'").param("id",id).param("ev",ev).query().listOfRows();if(rows.isEmpty())throw conflict("RELEASE_ITEM_INELIGIBLE","Question is not approved, active, or from this exam version");return rows.getFirst();}
    private Map<String,Object> eligibleFact(UUID id,UUID ev){var rows=jdbc.sql("SELECT f.current_version_id AS \"versionId\" FROM knowledge_fact f JOIN learning_objective lo ON lo.id=f.learning_objective_id JOIN topic t ON t.id=lo.topic_id JOIN subject s ON s.id=t.subject_id WHERE f.id=:id AND s.exam_version_id=:ev AND f.review_status='APPROVED' AND f.status='ACTIVE' AND (f.valid_from IS NULL OR f.valid_from<=CURRENT_DATE) AND (f.valid_to IS NULL OR f.valid_to>=CURRENT_DATE)").param("id",id).param("ev",ev).query().listOfRows();if(rows.isEmpty())throw conflict("RELEASE_ITEM_INELIGIBLE","Knowledge fact is not eligible for this release");return rows.getFirst();}
    private void validateQuestion(Map<String,Object> item,List<Map<String,Object>> issues){UUID version=(UUID)item.get("contentVersionId");var q=jdbc.sql("SELECT q.status,qv.review_status,qv.question_type,qv.explanation,(SELECT count(*) FROM question_option o WHERE o.question_version_id=qv.id) AS options,(SELECT count(*) FROM question_option o WHERE o.question_version_id=qv.id AND o.correct) AS correct FROM question_version qv JOIN question q ON q.id=qv.question_id WHERE qv.id=:id").param("id",version).query().singleRow();if("RETIRED".equals(q.get("status"))||!"APPROVED".equals(q.get("review_status")))issues.add(issue("CONTENT_VERSION_NOT_APPROVED","ERROR","Question version is not release eligible","QUESTION",version));String type=(String)q.get("question_type");if(!java.util.Set.of("SINGLE_CHOICE","MULTIPLE_CHOICE","TRUE_FALSE").contains(type))issues.add(issue("UNSUPPORTED_QUESTION_TYPE","ERROR","Question type is not supported by learner delivery","QUESTION",version));if(q.get("explanation")==null||((String)q.get("explanation")).isBlank())issues.add(issue("MISSING_EXPLANATION","ERROR","Question explanation is required","QUESTION",version));int options=((Number)q.get("options")).intValue(),correct=((Number)q.get("correct")).intValue();boolean invalid=options<2||options>6||("MULTIPLE_CHOICE".equals(type)?correct<1:correct!=1);if(invalid)issues.add(issue("INVALID_ANSWERS","ERROR","Question answer structure is invalid for "+type,"QUESTION",version));long missing=jdbc.sql("SELECT count(*) FROM question_knowledge_fact qkf WHERE qkf.question_version_id=:id AND NOT EXISTS(SELECT 1 FROM content_release_item ri WHERE ri.release_id=:release AND ri.content_type='KNOWLEDGE_FACT' AND ri.content_version_id=qkf.knowledge_fact_version_id)").param("id",version).param("release",item.get("releaseId")).query(Long.class).single();if(missing>0)issues.add(issue("RELEASE_DEPENDENCY_MISSING","ERROR","Linked fact version is missing","QUESTION",version));}
    private void validateFact(Map<String,Object> item,List<Map<String,Object>> issues){UUID version=(UUID)item.get("contentVersionId");var f=jdbc.sql("SELECT f.status,v.review_status,v.valid_from,v.valid_to,(SELECT count(*) FROM knowledge_fact_source kfs JOIN source_reference sr ON sr.id=kfs.source_reference_id WHERE kfs.knowledge_fact_version_id=v.id AND sr.status='ACTIVE') AS sources FROM knowledge_fact_version v JOIN knowledge_fact f ON f.id=v.knowledge_fact_id WHERE v.id=:id").param("id",version).query().singleRow();if("RETIRED".equals(f.get("status"))||!"APPROVED".equals(f.get("review_status")))issues.add(issue("CONTENT_VERSION_NOT_APPROVED","ERROR","Fact version is not release eligible","KNOWLEDGE_FACT",version));if(((Number)f.get("sources")).intValue()==0)issues.add(issue("INVALID_SOURCE_DEPENDENCY","ERROR","Fact has no active source","KNOWLEDGE_FACT",version));}
    private List<Map<String,Object>> items(UUID id){var rows=jdbc.sql("SELECT id,release_id AS \"releaseId\",content_type AS \"contentType\",content_id AS \"contentId\",content_version_id AS \"contentVersionId\",content_code AS \"contentCode\",display_order AS \"displayOrder\",automatic_dependency AS \"automaticDependency\",included_at AS \"includedAt\" FROM content_release_item WHERE release_id=:id ORDER BY content_type,display_order").param("id",id).query().listOfRows();return rows;}
    private Map<String,Object> latestValidation(UUID id){var rows=jdbc.sql("SELECT id,valid,error_count AS \"errorCount\",warning_count AS \"warningCount\",validated_by AS \"validatedBy\",validated_at AS \"validatedAt\",release_version AS \"releaseVersion\",report_json::text AS report FROM release_validation_run WHERE release_id=:id ORDER BY validated_at DESC LIMIT 1").param("id",id).query().listOfRows();if(rows.isEmpty())return null;var result=rows.getFirst();try{result.put("report",mapper.readValue((String)result.get("report"),Object.class));return result;}catch(Exception e){throw new IllegalStateException("Cannot read release validation",e);}}
    private Map<String,Object> issue(String code,String severity,String message,String type,UUID version){var m=new java.util.LinkedHashMap<String,Object>();m.put("code",code);m.put("severity",severity);m.put("message",message);m.put("contentType",type);m.put("contentVersionId",version);return m;}
    private void validateInput(ReleaseInput in){if(in.examVersionId()==null)throw validation("examVersionId is required");if(in.releaseNumber()==null||in.releaseNumber().isBlank())throw validation("releaseNumber is required");if(in.displayName()==null||in.displayName().isBlank())throw validation("displayName is required");}
    private void editable(Map<String,Object> r){if(!List.of("DRAFT","VALIDATED").contains(r.get("status")))throw conflict("RELEASE_NOT_EDITABLE","Only a draft release can be edited");}
    private void expect(Long v){if(v==null||v<0)throw validation("version is required");}
    private void changed(int c,UUID id){if(c==0){get(id);throw stale();}}
    private String blank(String v){return v==null||v.isBlank()?null:v.trim();}
    private OffsetDateTime now(){return OffsetDateTime.now(ZoneOffset.UTC);}
    private String actor(){return SecurityContextHolder.getContext().getAuthentication().getName();}
    private DomainException notFound(){return new DomainException(HttpStatus.NOT_FOUND,"RELEASE_NOT_FOUND","Release was not found");}
    private DomainException validation(String m){return new DomainException(HttpStatus.UNPROCESSABLE_ENTITY,"RELEASE_VALIDATION_FAILED",m);}
    private DomainException stale(){return conflict("STALE_RELEASE_VERSION","Release changed; reload and try again");}
    private DomainException conflict(String code,String m){return new DomainException(HttpStatus.CONFLICT,code,m);}
    private void log(String action,UUID id){LOG.info("content_action={} actor={} release_id={}",action,actor(),id);}
    private record Selection(String type,UUID contentId,UUID versionId,String code,int order,boolean automatic){}
}
