package se.medbo.examplatform.ai.provider;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.RETURNS_DEEP_STUBS;
import static org.mockito.Mockito.mock;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.simple.JdbcClient;

class FreeOnlyProviderRouterTest {
  private final ObjectMapper mapper=new ObjectMapper();
  @Test void selectsGeminiWhenReady(){assertThat(router(ready("GEMINI"),ready("GROQ")).execute(request()).provider()).isEqualTo("GEMINI");}
  @Test void fallsBackInConfiguredOrder(){assertThat(router(blocked("GEMINI","FREE_QUOTA_EXHAUSTED"),ready("GROQ"),ready("CLOUDFLARE_WORKERS_AI")).execute(request()).provider()).isEqualTo("GROQ");assertThat(router(blocked("GEMINI","FREE_QUOTA_EXHAUSTED"),blocked("GROQ","RATE_LIMITED"),ready("CLOUDFLARE_WORKERS_AI")).execute(request()).provider()).isEqualTo("CLOUDFLARE_WORKERS_AI");}
  @Test void usesOpenRouterOnlyAfterEarlierProviders(){assertThat(router(blocked("GEMINI","CIRCUIT_OPEN"),blocked("GROQ","RATE_LIMITED"),blocked("CLOUDFLARE_WORKERS_AI","FREE_QUOTA_EXHAUSTED"),ready("OPENROUTER_FREE")).execute(request()).provider()).isEqualTo("OPENROUTER_FREE");}
  @Test void paidOpenRouterIsUsedOnlyAfterEveryFreeRoute(){var provider=paidReady();var router=new FreeOnlyProviderRouter(List.of(blocked("GEMINI","CIRCUIT_OPEN"),blocked("GROQ","RATE_LIMITED"),blocked("OPENROUTER_FREE","FREE_QUOTA_EXHAUSTED"),provider),mock(JdbcClient.class,RETURNS_DEEP_STUBS),mapper,new ProviderExecutionDeadline(5,1),"GEMINI,GROQ,OPENROUTER_FREE,OPENROUTER_PAID",4,"FREE_ONLY",false,true,false,true);assertThat(router.execute(request()).provider()).isEqualTo("OPENROUTER_PAID");}
  @Test void skipsUnknownFreeStatusAndPausesWhenAllUnavailable(){assertThatThrownBy(()->router(unknown("GEMINI"),unknown("GROQ")).execute(request())).isInstanceOfSatisfying(AiProviderException.class,e->assertThat(e.code()).isEqualTo("AI_ALL_FREE_PROVIDERS_UNAVAILABLE"));}
  @Test void skipsMissingCredentialsAndUnsupportedCapabilities(){assertThat(router(ineligible("GEMINI",false,true),ineligible("GROQ",true,false),ready("CLOUDFLARE_WORKERS_AI")).execute(request()).provider()).isEqualTo("CLOUDFLARE_WORKERS_AI");}
  @Test void respectsConfiguredPriority(){var router=new FreeOnlyProviderRouter(List.of(ready("GEMINI"),ready("GROQ")),mock(JdbcClient.class,RETURNS_DEEP_STUBS),mapper,new ProviderExecutionDeadline(5,1),"GROQ,GEMINI",2,"FREE_ONLY",false,true,false,false);assertThat(router.execute(request()).provider()).isEqualTo("GROQ");}
  @Test void rejectsAResponseThatIsNotConfirmedFree(){assertThatThrownBy(()->router(paidResponse("GEMINI")).execute(request())).isInstanceOfSatisfying(AiProviderException.class,e->assertThat(e.code()).isEqualTo("AI_PROVIDER_FREE_STATUS_UNVERIFIED"));}
  @Test void rejectsUnboundedGlobalPaidFallback(){assertThatThrownBy(()->new FreeOnlyProviderRouter(List.of(),mock(JdbcClient.class),mapper,new ProviderExecutionDeadline(5,1),"GEMINI",1,"FREE_ONLY",true,true,false,false)).isInstanceOf(IllegalStateException.class);}
  private FreeOnlyProviderRouter router(StructuredAiProvider...p){return new FreeOnlyProviderRouter(List.of(p),mock(JdbcClient.class,RETURNS_DEEP_STUBS),mapper,new ProviderExecutionDeadline(5,1),"GEMINI,GROQ,CLOUDFLARE_WORKERS_AI,OPENROUTER_FREE",4,"FREE_ONLY",false,true,false,false);}
  private StructuredAiProvider ready(String name){return provider(name,new StructuredAiProvider.Availability(true,"READY",StructuredAiProvider.FreeStatus.KNOWN,StructuredAiProvider.CapacityAuthority.CONFIGURATION,"CLOSED",null,Map.of()));}
  private StructuredAiProvider blocked(String name,String reason){return provider(name,new StructuredAiProvider.Availability(false,reason,StructuredAiProvider.FreeStatus.KNOWN,StructuredAiProvider.CapacityAuthority.LOCAL_ESTIMATE,"QUOTA_PAUSED",null,Map.of()));}
  private StructuredAiProvider unknown(String name){return provider(name,new StructuredAiProvider.Availability(false,"FREE_STATUS_UNVERIFIED",StructuredAiProvider.FreeStatus.UNKNOWN,StructuredAiProvider.CapacityAuthority.CONFIGURATION,"UNKNOWN",null,Map.of()));}
  private StructuredAiProvider ineligible(String name,boolean credentials,boolean capabilities){var delegate=ready(name);return new StructuredAiProvider(){public String provider(){return name;}public String model(){return delegate.model();}public int priority(){return 1;}public boolean enabled(){return true;}public boolean credentialsConfigured(){return credentials;}public Capabilities capabilities(){return capabilities?delegate.capabilities():new Capabilities(true,false,false,true,true,true,10000,4096,true,true,true);}public Availability availability(Request r){return delegate.availability(r);}public Response execute(Request r){return delegate.execute(r);}};}
  private StructuredAiProvider paidResponse(String name){return new StructuredAiProvider(){public String provider(){return name;}public String model(){return "paid";}public int priority(){return 1;}public boolean enabled(){return true;}public boolean credentialsConfigured(){return true;}public Capabilities capabilities(){return new Capabilities(true,true,true,true,true,true,10000,4096,true,true,true);}public Availability availability(Request r){return new Availability(true,"READY",FreeStatus.KNOWN,CapacityAuthority.PROVIDER_API,"CLOSED",null,Map.of());}public Response execute(Request r){return new Response(mapper.createObjectNode(),name,model(),model(),"request",1,1,1L,"stop",Map.of(),Map.of(),null,"HTTP_200",false);}};}
  private StructuredAiProvider paidReady(){return new StructuredAiProvider(){public String provider(){return "OPENROUTER_PAID";}public String model(){return "paid-model";}public int priority(){return 4;}public boolean enabled(){return true;}public boolean credentialsConfigured(){return true;}public Capabilities capabilities(){return new Capabilities(true,true,true,true,true,true,10000,4096,true,true,true);}public Availability availability(Request r){return new Availability(true,"READY",FreeStatus.UNKNOWN,CapacityAuthority.PROVIDER_API,"CLOSED",null,Map.of());}public Response execute(Request r){return new Response(mapper.createObjectNode(),provider(),model(),model(),"request",1,1,1L,"stop",Map.of(),Map.of(),null,"HTTP_200",false);}};}
  private StructuredAiProvider provider(String name,StructuredAiProvider.Availability a){return new StructuredAiProvider(){public String provider(){return name;}public String model(){return "free-model";}public int priority(){return 1;}public boolean enabled(){return true;}public boolean credentialsConfigured(){return true;}public Capabilities capabilities(){return new Capabilities(true,true,true,true,true,true,10000,4096,true,true,true);}public Availability availability(Request r){return a;}public Response execute(Request r){return new Response(mapper.createObjectNode(),name,model(),model(),"request",1,1,1L,"stop",Map.of(),Map.of(),null,"HTTP_200",true);}};}
  private StructuredAiProvider.Request request(){return new StructuredAiProvider.Request("TEST","system","prompt",Map.of("type","object"),100,0,null,"test",0,"correlation","idempotency");}
}
