package se.medbo.examplatform.ai.question;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.micrometer.core.instrument.MeterRegistry;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Types;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import se.medbo.examplatform.ai.generation.AiApiException;
import se.medbo.examplatform.ai.provider.AiProviderException;

@Service
public class QuestionGenerationJobService {
  private static final String OPERATION="GENERATE_QUESTIONS_FROM_FACT";
  private final JdbcClient jdbc;private final ObjectMapper mapper;private final QuestionGenerationProviderClient provider;private final QuestionProposalValidator validator;private final QuestionIntelligenceEngine intelligence;private final MeterRegistry metrics;private final TransactionTemplate transactions;private final boolean enabled;private final int hourlyLimit,maxRetries;
  QuestionGenerationJobService(JdbcClient jdbc,ObjectMapper mapper,QuestionGenerationProviderClient provider,QuestionProposalValidator validator,QuestionIntelligenceEngine intelligence,MeterRegistry metrics,
      PlatformTransactionManager transactionManager,@Value("${ai.jobs.enabled:true}")boolean enabled,@Value("${ai.generation.rate-limit-per-hour:20}")int hourlyLimit,@Value("${ai.generation.max-retries:2}")int maxRetries){this.jdbc=jdbc;this.mapper=mapper;this.provider=provider;this.validator=validator;this.intelligence=intelligence;this.metrics=metrics;this.transactions=new TransactionTemplate(transactionManager);this.enabled=enabled;this.hourlyLimit=hourlyLimit;this.maxRetries=maxRetries;}

  private record AssessedProposal(QuestionGenerationProviderClient.Proposal proposal,QuestionIntelligenceAssessment assessment){}

  private void insertProposal(UUID job,Map<String,Object> row,QuestionGenerationProviderClient.Request request,
      QuestionGenerationProviderClient.Proposal proposal,QuestionIntelligenceAssessment assessment,int order,
      String outputChecksum,QuestionGenerationProviderClient.Usage usage) {
    insertProposal(job,row,request,proposal,order,outputChecksum,usage);
    UUID proposalId=jdbc.sql("SELECT id FROM ai_question_proposal WHERE generation_job_id=:job AND proposal_order=:order")
        .param("job",job).param("order",order).query(UUID.class).single();
    var metadata=assessment.metadata();
    jdbc.sql("UPDATE ai_question_proposal SET intelligence_evaluation_status='EVALUATED',difficulty=:difficulty,blooms_level=:bloom,complexity=:complexity,generation_intent=:intent,estimated_reading_seconds=:reading,overall_quality_score=:score,quality_level=:level,passed_intelligence_validation=:passed,intelligence_engine_version=:engine,quality_rationale=:rationale,provider_pedagogical_metadata=CAST(:providerMetadata AS jsonb),intelligence_evaluated_at=:evaluated,status=CASE WHEN :passed THEN status ELSE 'REJECTED' END,rejection_reason=CASE WHEN :passed THEN rejection_reason ELSE 'Blocked by Question Intelligence' END,rejected_by=CASE WHEN :passed THEN rejected_by ELSE 'question-intelligence-engine' END,rejected_at=CASE WHEN :passed THEN rejected_at ELSE :evaluated END WHERE id=:id")
        .param("difficulty",metadata.difficulty().name()).param("bloom",metadata.bloomsLevel().name())
        .param("complexity",metadata.complexity().name()).param("intent",metadata.intent().name())
        .param("reading",metadata.estimatedReadingSeconds()).param("score",assessment.overallScore())
        .param("level",assessment.qualityLevel().name()).param("passed",assessment.passedValidation())
        .param("engine",assessment.engineVersion()).param("rationale",blank(assessment.qualityRationale()),Types.VARCHAR)
        .param("providerMetadata",json(proposal.metadata())).param("evaluated",assessment.evaluatedAt()).param("id",proposalId).update();
    int display=0;
    for(var finding:allFindings(assessment)) jdbc.sql("INSERT INTO ai_question_intelligence_finding(id,proposal_id,display_order,code,severity,category,message,field_path,blocking,details,validator_name,validator_version) VALUES(:id,:proposal,:display,:code,:severity,:category,:message,:field,:blocking,CAST(:details AS jsonb),:validator,:validatorVersion)")
        .param("id",UUID.randomUUID()).param("proposal",proposalId).param("display",display++)
        .param("code",finding.code()).param("severity",finding.severity().name()).param("category",finding.category().name())
        .param("message",finding.message()).param("field",finding.field(),Types.VARCHAR).param("blocking",finding.blocking())
        .param("details",json(finding.details())).param("validator",finding.validatorName()).param("validatorVersion",finding.validatorVersion()).update();
    for(var score:assessment.componentScores().entrySet()) jdbc.sql("INSERT INTO ai_question_intelligence_component_score(proposal_id,component,score) VALUES(:proposal,:component,:score)")
        .param("proposal",proposalId).param("component",score.getKey().name()).param("score",score.getValue()).update();
  }

  private List<QuestionIntelligenceAssessment.Finding> allFindings(QuestionIntelligenceAssessment assessment) {
    var findings=new ArrayList<QuestionIntelligenceAssessment.Finding>();
    findings.addAll(assessment.blockingIssues());findings.addAll(assessment.warnings());findings.addAll(assessment.informationalFindings());
    return findings;
  }

  Map<String,Object> withIntelligence(Map<String,Object> proposal) {
    UUID id=(UUID)proposal.get("id");
    var rows=jdbc.sql("SELECT intelligence_evaluation_status AS \"evaluationStatus\",difficulty,blooms_level AS \"bloomsLevel\",complexity,generation_intent AS \"generationIntent\",estimated_reading_seconds AS \"estimatedReadingSeconds\",overall_quality_score AS \"overallQualityScore\",quality_level AS \"qualityLevel\",passed_intelligence_validation AS \"passedValidation\",intelligence_engine_version AS \"engineVersion\",quality_rationale AS \"qualityRationale\",intelligence_evaluated_at AS \"evaluatedAt\" FROM ai_question_proposal WHERE id=:id")
        .param("id",id).query().listOfRows();
    var assessment=new java.util.LinkedHashMap<String,Object>(rows.getFirst());
    assessment.put("findings",jdbc.sql("SELECT code,severity,category,message,field_path AS field,blocking,details::text AS details,validator_name AS \"validatorName\",validator_version AS \"validatorVersion\" FROM ai_question_intelligence_finding WHERE proposal_id=:id ORDER BY display_order").param("id",id).query().listOfRows().stream().peek(f->f.put("details",read((String)f.get("details")))).toList());
    var scores=new java.util.LinkedHashMap<String,Integer>();
    jdbc.sql("SELECT component,score FROM ai_question_intelligence_component_score WHERE proposal_id=:id ORDER BY component").param("id",id).query().listOfRows().forEach(s->scores.put((String)s.get("component"),(Integer)s.get("score")));
    assessment.put("componentScores",scores);proposal.put("intelligenceAssessment",assessment);
    var acceptance=jdbc.sql("SELECT accepted_question_id AS \"acceptedQuestionId\",accepted_by AS \"acceptedBy\",accepted_at AS \"acceptedAt\" FROM ai_question_proposal WHERE id=:id").param("id",id).query().singleRow();
    proposal.putAll(acceptance);return proposal;
  }

  Map<String,Object> revalidate(UUID id) {
    var stored=proposal(id);
    if(!"PROPOSED".equals(stored.get("status")))throw error(HttpStatus.CONFLICT,"AI_QUESTION_PROPOSAL_NOT_ACCEPTABLE","Only a proposed question can be accepted");
    var job=jdbc.sql("SELECT target_context FROM ai_generation_job WHERE id=:id").param("id",stored.get("generationJobId")).query(String.class).optional()
        .orElseThrow(()->error(HttpStatus.NOT_FOUND,"AI_JOB_NOT_FOUND","Question generation job was not found"));
    try {
      var request=mapper.readValue(job,QuestionGenerationProviderClient.Request.class);
      verifySnapshot(request);
      var options=((List<Map<String,Object>>)stored.get("answerOptions")).stream().map(o->new QuestionGenerationProviderClient.Option(
          String.valueOf(o.get("optionKey")),String.valueOf(o.get("text")),Boolean.TRUE.equals(o.get("correct")),(String)o.get("rationale"))).toList();
      var evidence=(List<Map<String,Object>>)stored.get("evidence");
      String supportedClaim=evidence.stream().filter(e->"KNOWLEDGE_FACT".equals(e.get("evidenceType"))).map(e->String.valueOf(e.get("supportedClaim"))).findFirst().orElse(request.target().text());
      var sources=evidence.stream().filter(e->"SOURCE".equals(e.get("evidenceType"))).map(e->new QuestionGenerationProviderClient.SourceEvidence(
          (UUID)e.get("sourceId"),String.valueOf(e.get("sourceTitle")),String.valueOf(e.get("sourceChecksum")),String.valueOf(e.get("quote")))).toList();
      var details=jdbc.sql("SELECT provider_pedagogical_metadata::text AS metadata,quality_rationale FROM ai_question_proposal WHERE id=:id").param("id",id).query().singleRow();
      QuestionGenerationProviderClient.PedagogicalMetadata metadata=details.get("metadata")==null?null:mapper.readValue(String.valueOf(details.get("metadata")),QuestionGenerationProviderClient.PedagogicalMetadata.class);
      var candidate=new QuestionGenerationProviderClient.Proposal(String.valueOf(stored.get("questionType")),String.valueOf(stored.get("questionText")),String.valueOf(stored.get("language")),options,
          String.valueOf(stored.get("explanation")),String.valueOf(stored.get("rationale")),new QuestionGenerationProviderClient.FactEvidence(
          (UUID)stored.get("targetKnowledgeFactId"),((Number)stored.get("targetVersion")).longValue(),String.valueOf(stored.get("targetChecksum")),supportedClaim),
          sources,(String)stored.get("confidence"),((List<?>)stored.get("warnings")).stream().map(String::valueOf).toList(),metadata,(String)details.get("quality_rationale"));
      validator.validateProposal(request,candidate);
      String persistedTextChecksum=jdbc.sql("SELECT proposal_text_checksum FROM ai_question_proposal WHERE id=:id").param("id",id).query(String.class).single();
      if(!sha(candidate.questionText()).equals(persistedTextChecksum))throw new AiProviderException("AI_QUESTION_PROPOSAL_CHECKSUM_MISMATCH",false,"Question proposal checksum changed");
      var assessment=intelligence.assess(candidate,new QuestionIntelligenceEngine.Context(true,now(),request.target().language(),QuestionIntelligenceAssessment.GenerationIntent.PRACTICE));
      if(!assessment.passedValidation())throw new AiProviderException("AI_QUESTION_INTELLIGENCE_REJECTED",false,"Question Intelligence validation no longer passes");
      String validationChecksum=checksum(Map.of("proposal",candidate,"overallScore",assessment.overallScore(),"qualityLevel",assessment.qualityLevel(),
          "metadata",assessment.metadata(),"componentScores",assessment.componentScores(),"findings",allFindings(assessment),
          "engineVersion",assessment.engineVersion(),"targetChecksum",request.target().checksum()));
      var response=new java.util.LinkedHashMap<String,Object>();
      response.put("valid",true);response.put("proposalChecksum",checksum(candidate));response.put("validationChecksum",validationChecksum);response.put("intelligenceEngineVersion",assessment.engineVersion());response.put("evaluatedAt",assessment.evaluatedAt());
      response.put("sourceChecksums",request.context().sources().stream().map(s->Map.of("sourceId",s.sourceId(),"checksum",s.checksum())).toList());
      return response;
    } catch(AiProviderException e) { throw error(HttpStatus.CONFLICT,e.code(),e.getMessage()); }
    catch(AiApiException e){throw e;}
    catch(Exception e){throw error(HttpStatus.CONFLICT,"AI_QUESTION_PROPOSAL_REVALIDATION_FAILED","Question proposal could not be revalidated");}
  }

  @Transactional Map<String,Object> accept(UUID id,UUID questionId,String actor,long version,String validationChecksum) {
    var validation=revalidate(id);
    if(!validationChecksum.equals(validation.get("validationChecksum")))throw error(HttpStatus.CONFLICT,"AI_QUESTION_ACCEPTANCE_VALIDATION_STALE","Acceptance validation changed");
    int changed=jdbc.sql("UPDATE ai_question_proposal SET status='ACCEPTED',accepted_question_id=:question,accepted_by=:actor,accepted_at=:now,acceptance_validation_checksum=:checksum,updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND status='PROPOSED' AND passed_intelligence_validation=true")
        .param("question",questionId).param("actor",actor).param("now",now()).param("checksum",validationChecksum).param("id",id).param("version",version).update();
    if(changed==0){var current=withIntelligence(proposal(id));if("ACCEPTED".equals(current.get("status"))&&questionId.equals(current.get("acceptedQuestionId")))return current;throw error(HttpStatus.CONFLICT,"AI_QUESTION_PROPOSAL_STALE","Proposal changed and could not be accepted");}
    metrics.counter("ai.question_generation.proposals","result","accepted").increment();
    return proposal(id);
  }

  @Transactional public Map<String,Object> create(QuestionGenerationProviderClient.Request request,String actor,String key,String providerName,String model){
    validateRequest(request);long recent=jdbc.sql("SELECT count(*) FROM ai_generation_job WHERE requested_by=:actor AND created_at>now()-interval '1 hour'").param("actor",actor).query(Long.class).single();if(recent>=hourlyLimit)throw error(HttpStatus.TOO_MANY_REQUESTS,"AI_RATE_LIMIT_EXCEEDED","The hourly AI generation limit was reached");
    var existing=jdbc.sql("SELECT id FROM ai_generation_job WHERE requested_by=:actor AND idempotency_key=:key").param("actor",actor).param("key",key).query(UUID.class).list();if(!existing.isEmpty())return get(existing.getFirst());
    UUID id=UUID.randomUUID();OffsetDateTime now=now();String context=json(request);var first=request.context().sources().isEmpty()?null:request.context().sources().getFirst();
    jdbc.sql("INSERT INTO ai_generation_job(id,job_type,operation_type,source_id,source_title,source_content,source_content_checksum,learning_objective_id,learning_objective_title,requested_by,requested_count,language,idempotency_key,status,provider,model,prompt_version,created_at,next_attempt_at,input_character_count,target_context,target_content_checksum) VALUES(:id,'QUESTION_GENERATION',:operation,:source,:sourceTitle,:sourceContent,:sourceChecksum,:objective,:objectiveTitle,:actor,:count,:language,:key,'QUEUED',:provider,:model,:prompt,:now,:now,:characters,CAST(:context AS jsonb),:checksum)")
      .param("id",id).param("operation",OPERATION).param("source",first==null?null:first.sourceId(),Types.OTHER).param("sourceTitle",first==null?null:first.title(),Types.VARCHAR).param("sourceContent",first==null?null:first.contentExcerpt(),Types.VARCHAR).param("sourceChecksum",first==null?null:first.checksum(),Types.CHAR).param("objective",request.context().learningObjectiveId()).param("objectiveTitle",request.context().learningObjectiveTitle()).param("actor",actor).param("count",request.proposalCount()).param("language",request.target().language()).param("key",key).param("provider",providerName).param("model",model).param("prompt",request.promptVersion()).param("now",now).param("characters",inputSize(request)).param("context",context).param("checksum",request.target().checksum()).update();
    var t=request.target();var c=request.context();jdbc.sql("INSERT INTO ai_question_generation_detail(generation_job_id,target_fact_id,target_fact_version_id,target_version,target_fact_checksum,target_fact_snapshot,learning_objective_id,topic_id,subject_id,exam_id,exam_version_id,requested_question_type,context_snapshot) VALUES(:job,:fact,:factVersion,:version,:checksum,:snapshot,:objective,:topic,:subject,:exam,:examVersion,:type,CAST(:context AS jsonb))")
      .param("job",id).param("fact",t.knowledgeFactId()).param("factVersion",t.knowledgeFactVersionId()).param("version",t.version()).param("checksum",t.checksum()).param("snapshot",t.text()).param("objective",c.learningObjectiveId()).param("topic",c.topicId()).param("subject",c.subjectId()).param("exam",c.examId()).param("examVersion",c.examVersionId()).param("type",request.questionType(),Types.VARCHAR).param("context",context).update();
    int order=0;for(var source:c.sources())jdbc.sql("INSERT INTO ai_question_generation_source(generation_job_id,source_id,source_title,source_checksum,content_excerpt,display_order) VALUES(:job,:source,:title,:checksum,:excerpt,:display)").param("job",id).param("source",source.sourceId()).param("title",source.title()).param("checksum",source.checksum()).param("excerpt",source.contentExcerpt()).param("display",order++).update();
    metrics.counter("ai.question_generation.jobs","result","requested").increment();return get(id);
  }
  public Map<String,Object> get(UUID id){var rows=jdbc.sql("SELECT j.id,j.operation_type AS \"operationType\",j.result_type AS \"resultType\",j.requested_by AS \"requestedBy\",j.requested_count AS \"requestedCount\",d.requested_question_type AS \"requestedQuestionType\",d.target_fact_id AS \"targetKnowledgeFactId\",d.target_fact_version_id AS \"targetKnowledgeFactVersionId\",d.target_version AS \"targetVersion\",d.target_fact_checksum AS \"targetChecksum\",j.status,j.provider,j.model,j.prompt_version AS \"promptVersion\",j.created_at AS \"createdAt\",j.started_at AS \"startedAt\",j.completed_at AS \"completedAt\",j.failed_at AS \"failedAt\",j.cancelled_at AS \"cancelledAt\",j.retry_count AS \"retryCount\",j.input_tokens AS \"inputTokens\",j.output_tokens AS \"outputTokens\",j.total_tokens AS \"totalTokens\",j.provider_request_id AS \"providerRequestId\",j.error_code AS \"errorCode\",j.error_message AS \"errorMessage\",j.version,(SELECT count(*) FROM ai_question_proposal p WHERE p.generation_job_id=j.id) AS \"proposalCount\" FROM ai_generation_job j JOIN ai_question_generation_detail d ON d.generation_job_id=j.id WHERE j.id=:id AND j.job_type='QUESTION_GENERATION'").param("id",id).query().listOfRows();if(rows.isEmpty())throw error(HttpStatus.NOT_FOUND,"AI_JOB_NOT_FOUND","Question generation job was not found");return rows.getFirst();}
  public List<Map<String,Object>> history(UUID factId,int limit){return jdbc.sql("SELECT j.id FROM ai_generation_job j JOIN ai_question_generation_detail d ON d.generation_job_id=j.id WHERE j.job_type='QUESTION_GENERATION' AND d.target_fact_id=:fact ORDER BY CASE WHEN j.status IN ('QUEUED','RUNNING') THEN 0 ELSE 1 END,j.created_at DESC,j.id DESC LIMIT :limit").param("fact",factId).param("limit",limit).query(UUID.class).list().stream().map(this::get).toList();}
  public List<Map<String,Object>> proposals(UUID job){get(job);return jdbc.sql("SELECT id FROM ai_question_proposal WHERE generation_job_id=:job ORDER BY proposal_order").param("job",job).query(UUID.class).list().stream().map(this::proposal).toList();}
  public Map<String,Object> proposal(UUID id){var rows=jdbc.sql("SELECT p.id,p.generation_job_id AS \"generationJobId\",p.proposal_order AS \"proposalOrder\",p.operation_type AS \"operationType\",p.question_type AS \"questionType\",p.question_text AS \"questionText\",p.language,p.explanation,p.rationale,p.target_fact_id AS \"targetKnowledgeFactId\",p.target_fact_version_id AS \"targetKnowledgeFactVersionId\",p.target_fact_version AS \"targetVersion\",p.target_fact_checksum AS \"targetChecksum\",p.learning_objective_id AS \"learningObjectiveId\",p.warnings::text AS warnings,p.confidence,p.validation_status AS \"validationStatus\",p.status,p.rejection_reason AS \"rejectionReason\",p.rejection_reason_code AS \"rejectionReasonCode\",p.reviewer_comment AS \"reviewerComment\",p.rejected_by AS \"rejectedBy\",p.rejected_at AS \"rejectedAt\",p.root_proposal_id AS \"rootProposalId\",p.parent_proposal_id AS \"parentProposalId\",p.superseded_by_proposal_id AS \"supersededByProposalId\",p.generation_attempt AS \"generationAttempt\",p.regenerated_by AS \"regeneratedBy\",p.regenerated_at AS \"regeneratedAt\",p.regeneration_feedback AS \"regenerationFeedback\",p.provider,p.model,p.prompt_version AS \"promptVersion\",p.provider_request_id AS \"providerRequestId\",p.input_tokens AS \"inputTokens\",p.output_tokens AS \"outputTokens\",p.total_tokens AS \"totalTokens\",p.created_at AS \"createdAt\",p.updated_at AS \"updatedAt\",p.version FROM ai_question_proposal p WHERE p.id=:id").param("id",id).query().listOfRows();if(rows.isEmpty())throw error(HttpStatus.NOT_FOUND,"AI_QUESTION_PROPOSAL_NOT_FOUND","Question proposal was not found");var row=rows.getFirst();if(row.get("rootProposalId")==null)row.put("rootProposalId",id);row.put("active",List.of("PROPOSED","REJECTED").contains(row.get("status"))&&row.get("supersededByProposalId")==null);row.put("warnings",read((String)row.get("warnings")));row.put("answerOptions",jdbc.sql("SELECT id,option_key AS \"optionKey\",display_order AS \"displayOrder\",text,correct,rationale FROM ai_question_proposal_option WHERE proposal_id=:id ORDER BY display_order").param("id",id).query().listOfRows());row.put("evidence",jdbc.sql("SELECT id,evidence_type AS \"evidenceType\",source_id AS \"sourceId\",source_title AS \"sourceTitle\",source_checksum AS \"sourceChecksum\",supported_claim AS \"supportedClaim\",quote,display_order AS \"displayOrder\" FROM ai_question_proposal_evidence WHERE proposal_id=:id ORDER BY display_order").param("id",id).query().listOfRows());return row;}
  @Transactional public Map<String,Object> reject(UUID id,String reasonCode,String comment,String actor,long version){validateRejection(reasonCode,comment);int changed=jdbc.sql("UPDATE ai_question_proposal SET status='REJECTED',rejection_reason=:comment,rejection_reason_code=:code,reviewer_comment=:comment,rejected_by=:actor,rejected_at=:now,updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND status='PROPOSED' AND superseded_by_proposal_id IS NULL").param("comment",blank(comment),Types.VARCHAR).param("code",reasonCode).param("actor",actor).param("now",now()).param("id",id).param("version",version).update();if(changed==0)throw stateConflict(proposal(id),"rejected");audit(actor,"AI_PROPOSAL_REJECTION_REQUESTED",id,Map.of("reasonCode",reasonCode));audit(actor,"AI_PROPOSAL_REJECTED",id,Map.of("reasonCode",reasonCode));metrics.counter("ai.question_generation.proposals","result","user_rejected").increment();return proposal(id);}
  @Transactional public Map<String,Object> regenerate(UUID id,String feedback,String actor,long version,String key,String providerName,String model){
    if(feedback==null||feedback.isBlank()||feedback.trim().length()>1000)throw error(HttpStatus.UNPROCESSABLE_ENTITY,"AI_QUESTION_REGENERATION_FEEDBACK_INVALID","Concrete reviewer feedback is required");
    var original=proposal(id);String status=String.valueOf(original.get("status"));if(!List.of("PROPOSED","REJECTED").contains(status)||original.get("supersededByProposalId")!=null)throw stateConflict(original,"regenerated");
    if(((Number)original.get("version")).longValue()!=version)throw error(HttpStatus.CONFLICT,"AI_QUESTION_PROPOSAL_STALE","The proposal changed while regeneration was requested");
    var existing=jdbc.sql("SELECT generation_job_id FROM ai_question_generation_detail WHERE regeneration_parent_proposal_id=:id").param("id",id).query(UUID.class).optional();if(existing.isPresent())return regenerationResult(existing.get(),id);
    String stored=jdbc.sql("SELECT j.target_context::text FROM ai_generation_job j WHERE j.id=:id").param("id",original.get("generationJobId")).query(String.class).single();
    try{
      var base=mapper.readValue(stored,QuestionGenerationProviderClient.Request.class);
      var oldOptions=((List<Map<String,Object>>)original.get("answerOptions")).stream().map(o->new QuestionGenerationProviderClient.Option(String.valueOf(o.get("optionKey")),String.valueOf(o.get("text")),Boolean.TRUE.equals(o.get("correct")),(String)o.get("rationale"))).toList();
      int attempt=((Number)original.get("generationAttempt")).intValue()+1;
      var regeneration=new QuestionGenerationProviderClient.Regeneration(id,(String)original.get("rejectionReasonCode"),feedback.trim(),String.valueOf(original.get("questionText")),oldOptions,attempt);
      var request=new QuestionGenerationProviderClient.Request(base.target(),base.context(),1,String.valueOf(original.get("questionType")),"question-regeneration-v1",null,null,0,regeneration);
      String scopedKey="regenerate:"+id+":"+sha(key).substring(0,32);
      var created=create(request,actor,scopedKey,providerName,model);UUID job=(UUID)created.get("id");UUID root=(UUID)original.get("rootProposalId");
      jdbc.sql("UPDATE ai_question_generation_detail SET regeneration_parent_proposal_id=:parent,regeneration_root_proposal_id=:root,regeneration_feedback=:feedback,regeneration_reason_code=:reason,regenerated_by=:actor WHERE generation_job_id=:job")
          .param("parent",id).param("root",root).param("feedback",feedback.trim()).param("reason",original.get("rejectionReasonCode"),Types.VARCHAR).param("actor",actor).param("job",job).update();
      audit(actor,"AI_PROPOSAL_REGENERATION_REQUESTED",id,Map.of("jobId",job,"rootProposalId",root,"generationAttempt",attempt));return regenerationResult(job,id);
    }catch(org.springframework.dao.DuplicateKeyException e){var job=jdbc.sql("SELECT generation_job_id FROM ai_question_generation_detail WHERE regeneration_parent_proposal_id=:id").param("id",id).query(UUID.class).optional();if(job.isPresent())return regenerationResult(job.get(),id);throw error(HttpStatus.CONFLICT,"ACTIVE_SUCCESSOR_ALREADY_EXISTS","This proposal already has an active regeneration");}
    catch(AiApiException e){throw e;}catch(Exception e){throw error(HttpStatus.CONFLICT,"AI_QUESTION_PROPOSAL_NOT_REGENERATABLE","The proposal could not be regenerated");}
  }
  public List<Map<String,Object>> lineage(UUID id){var p=proposal(id);UUID root=(UUID)p.get("rootProposalId");return jdbc.sql("SELECT id FROM ai_question_proposal WHERE id=:root OR root_proposal_id=:root ORDER BY generation_attempt,created_at,id").param("root",root).query(UUID.class).list().stream().map(this::proposal).toList();}
  @Transactional public Map<String,Object> cancel(UUID id){var job=get(id);if(List.of("CANCELLED").contains(job.get("status")))return job;if(!List.of("QUEUED","RUNNING").contains(job.get("status")))throw error(HttpStatus.CONFLICT,"AI_JOB_NOT_CANCELLABLE","Job can no longer be cancelled");jdbc.sql("UPDATE ai_generation_job SET cancellation_requested=true,status=CASE WHEN status='QUEUED' THEN 'CANCELLED' ELSE status END,cancelled_at=CASE WHEN status='QUEUED' THEN :now ELSE cancelled_at END,version=version+1 WHERE id=:id").param("now",now()).param("id",id).update();return get(id);}
  @Scheduled(fixedDelay=1000)public void work(){if(!enabled)return;var ids=jdbc.sql("SELECT id FROM ai_generation_job WHERE job_type='QUESTION_GENERATION' AND status='QUEUED' AND cancellation_requested=false AND next_attempt_at<=now() ORDER BY created_at LIMIT 1").query(UUID.class).list();if(!ids.isEmpty())run(ids.getFirst());}
  void run(UUID id){int claimed=jdbc.sql("UPDATE ai_generation_job SET status='RUNNING',started_at=coalesce(started_at,:now),version=version+1 WHERE id=:id AND status='QUEUED' AND cancellation_requested=false").param("now",now()).param("id",id).update();if(claimed==0)return;var row=jdbc.sql("SELECT * FROM ai_generation_job WHERE id=:id").param("id",id).query().singleRow();try{var request=mapper.readValue(String.valueOf(row.get("target_context")),QuestionGenerationProviderClient.Request.class).execution(id,(String)row.get("requested_by"),(Integer)row.get("retry_count"));verifySnapshot(request);var result=provider.generate(request);if(cancelled(id)){cancelRunning(id);return;}transactions.executeWithoutResult(ignored->persist(id,row,request,result));}catch(AiProviderException e){failOrRetry(id,(Integer)row.get("retry_count"),e);}catch(Exception e){failOrRetry(id,(Integer)row.get("retry_count"),new AiProviderException("AI_QUESTION_GENERATION_OUTPUT_INVALID",false,"Question generation output was invalid"));}}
  @Transactional void persist(UUID id,Map<String,Object> row,QuestionGenerationProviderClient.Request request,QuestionGenerationProviderClient.Result result){if(cancelled(id)){cancelRunning(id);return;}var valid=new ArrayList<AssessedProposal>();var failures=new ArrayList<Map<String,String>>();var seen=new HashSet<String>();if("QUESTIONS_PROPOSED".equals(result.resultType())){int index=0;for(var proposal:result.proposals()==null?List.<QuestionGenerationProviderClient.Proposal>of():result.proposals()){try{validator.validateProposal(request,proposal);if(!seen.add(QuestionProposalValidator.normalize(proposal.questionText())))throw new AiProviderException("AI_QUESTION_GENERATION_DUPLICATE_PROPOSAL",false,"Duplicate proposal");var assessment=intelligence.assess(proposal,new QuestionIntelligenceEngine.Context(true,now(),request.target().language(),QuestionIntelligenceAssessment.GenerationIntent.PRACTICE));valid.add(new AssessedProposal(proposal,assessment));if(!assessment.passedValidation()){String codes=assessment.blockingIssues().stream().map(QuestionIntelligenceAssessment.Finding::code).sorted().reduce((a,b)->a+","+b).orElse("UNKNOWN");failures.add(Map.of("proposal",String.valueOf(index),"code","AI_QUESTION_INTELLIGENCE_REJECTED","message","Blocking question intelligence findings: "+codes));metrics.counter("ai.question_intelligence.assessments","result","rejected","quality",assessment.qualityLevel().name()).increment();}else metrics.counter("ai.question_intelligence.assessments","result","passed","quality",assessment.qualityLevel().name()).increment();}catch(AiProviderException e){failures.add(Map.of("proposal",String.valueOf(index),"code",e.code(),"message",e.getMessage()));metrics.counter("ai.question_generation.proposals","result","validation_rejected").increment();}index++;}}else validator.validate(request,result);
    if("QUESTIONS_PROPOSED".equals(result.resultType())&&valid.isEmpty()){jdbc.sql("UPDATE ai_question_generation_detail SET validation_failures=CAST(:failures AS jsonb),original_output_checksum=:checksum WHERE generation_job_id=:id").param("failures",json(failures)).param("checksum",checksum(result)).param("id",id).update();throw new AiProviderException("AI_QUESTION_GENERATION_NO_VALID_PROPOSALS",false,"No grounded question proposal passed validation");}
    String outputChecksum=result.structuredOutputChecksum()==null?checksum(result):result.structuredOutputChecksum();int order=0;var usage=result.usage();for(var p:valid)insertProposal(id,row,request,p.proposal(),p.assessment(),order++,outputChecksum,usage);String status=failures.isEmpty()?"COMPLETED":"PARTIALLY_COMPLETED";String resultType=result.resultType();jdbc.sql("UPDATE ai_question_generation_detail SET validation_failures=CAST(:failures AS jsonb),original_output_checksum=:checksum WHERE generation_job_id=:id").param("failures",json(failures)).param("checksum",outputChecksum).param("id",id).update();jdbc.sql("UPDATE ai_generation_job SET status=:status,result_type=:result,completed_at=:now,input_tokens=:input,output_tokens=:output,total_tokens=:total,provider_request_id=:request,version=version+1 WHERE id=:id").param("status",status).param("result",resultType).param("now",now()).param("input",usage==null?null:usage.inputTokens(),Types.INTEGER).param("output",usage==null?null:usage.outputTokens(),Types.INTEGER).param("total",usage==null||usage.inputTokens()==null||usage.outputTokens()==null?null:usage.inputTokens()+usage.outputTokens(),Types.INTEGER).param("request",usage==null?null:usage.requestId(),Types.VARCHAR).param("id",id).update();metrics.counter("ai.question_generation.jobs","result",status.toLowerCase()).increment();}
  private void insertProposal(UUID job,Map<String,Object> row,QuestionGenerationProviderClient.Request request,QuestionGenerationProviderClient.Proposal p,int order,String outputChecksum,QuestionGenerationProviderClient.Usage usage){UUID id=UUID.randomUUID();OffsetDateTime now=now();String textChecksum=sha(p.questionText());var regeneration=jdbc.sql("SELECT regeneration_parent_proposal_id AS parent,regeneration_root_proposal_id AS root,regeneration_feedback AS feedback,regenerated_by AS actor FROM ai_question_generation_detail WHERE generation_job_id=:job").param("job",job).query().singleRow();UUID parent=(UUID)regeneration.get("parent"),root=(UUID)regeneration.get("root");int attempt=1;if(parent!=null){long duplicate=jdbc.sql("SELECT count(*) FROM ai_question_proposal WHERE (id=:root OR root_proposal_id=:root) AND proposal_text_checksum=:checksum").param("root",root).param("checksum",textChecksum).query(Long.class).single();if(duplicate>0)throw new AiProviderException("AI_QUESTION_REGENERATION_DUPLICATE",false,"Regenerated proposal duplicated its lineage");attempt=jdbc.sql("SELECT generation_attempt+1 FROM ai_question_proposal WHERE id=:id").param("id",parent).query(Integer.class).single();}
    int inserted=jdbc.sql("INSERT INTO ai_question_proposal(id,generation_job_id,proposal_order,question_type,question_text,language,explanation,rationale,target_fact_id,target_fact_version_id,target_fact_version,target_fact_checksum,target_fact_snapshot,learning_objective_id,warnings,confidence,provider,model,prompt_version,provider_request_id,input_tokens,output_tokens,total_tokens,original_output_checksum,proposal_text_checksum,root_proposal_id,parent_proposal_id,generation_attempt,regenerated_by,regenerated_at,regeneration_feedback,created_at,updated_at) VALUES(:id,:job,:order,:type,:text,:language,:explanation,:rationale,:fact,:factVersion,:version,:checksum,:snapshot,:objective,CAST(:warnings AS jsonb),:confidence,:provider,:model,:prompt,:request,:input,:output,:total,:outputChecksum,:textChecksum,:root,:parent,:attempt,:regeneratedBy,:regeneratedAt,:feedback,:now,:now) ON CONFLICT DO NOTHING").param("id",id).param("job",job).param("order",order).param("type",p.questionType()).param("text",p.questionText()).param("language",p.language()).param("explanation",p.explanation()).param("rationale",p.rationale()).param("fact",request.target().knowledgeFactId()).param("factVersion",request.target().knowledgeFactVersionId()).param("version",request.target().version()).param("checksum",request.target().checksum()).param("snapshot",request.target().text()).param("objective",request.context().learningObjectiveId()).param("warnings",json(p.warnings()==null?List.of():p.warnings())).param("confidence",p.confidence(),Types.VARCHAR).param("provider",row.get("provider")).param("model",row.get("model")).param("prompt",row.get("prompt_version")).param("request",usage==null?null:usage.requestId(),Types.VARCHAR).param("input",usage==null?null:usage.inputTokens(),Types.INTEGER).param("output",usage==null?null:usage.outputTokens(),Types.INTEGER).param("total",usage==null||usage.inputTokens()==null||usage.outputTokens()==null?null:usage.inputTokens()+usage.outputTokens(),Types.INTEGER).param("outputChecksum",outputChecksum).param("textChecksum",textChecksum).param("root",root,Types.OTHER).param("parent",parent,Types.OTHER).param("attempt",attempt).param("regeneratedBy",regeneration.get("actor"),Types.VARCHAR).param("regeneratedAt",parent==null?null:now,Types.TIMESTAMP_WITH_TIMEZONE).param("feedback",regeneration.get("feedback"),Types.VARCHAR).param("now",now).update();if(inserted==0)throw new AiProviderException("AI_QUESTION_REGENERATION_DUPLICATE",false,"Regenerated proposal was not unique");
    int optionOrder=0;for(var option:p.answerOptions())jdbc.sql("INSERT INTO ai_question_proposal_option(id,proposal_id,option_key,display_order,text,correct,rationale) VALUES(:id,:proposal,:key,:display,:text,:correct,:rationale)").param("id",UUID.randomUUID()).param("proposal",id).param("key",option.optionKey()).param("display",optionOrder++).param("text",option.text()).param("correct",option.correct()).param("rationale",blank(option.rationale()),Types.VARCHAR).update();int evidenceOrder=0;jdbc.sql("INSERT INTO ai_question_proposal_evidence(id,proposal_id,evidence_type,supported_claim,display_order) VALUES(:id,:proposal,'KNOWLEDGE_FACT',:claim,:display)").param("id",UUID.randomUUID()).param("proposal",id).param("claim",p.factEvidence().supportedClaim()).param("display",evidenceOrder++).update();for(var evidence:p.sourceEvidence()==null?List.<QuestionGenerationProviderClient.SourceEvidence>of():p.sourceEvidence())jdbc.sql("INSERT INTO ai_question_proposal_evidence(id,proposal_id,evidence_type,source_id,source_title,source_checksum,supported_claim,quote,display_order) VALUES(:id,:proposal,'SOURCE',:source,:title,:checksum,:claim,:quote,:display)").param("id",UUID.randomUUID()).param("proposal",id).param("source",evidence.sourceId()).param("title",evidence.sourceTitle()).param("checksum",evidence.sourceChecksum()).param("claim",p.factEvidence().supportedClaim()).param("quote",evidence.quote()).param("display",evidenceOrder++).update();if(parent!=null){int linked=jdbc.sql("UPDATE ai_question_proposal SET status='SUPERSEDED',superseded_by_proposal_id=:successor,updated_at=:now,version=version+1 WHERE id=:parent AND status IN ('PROPOSED','REJECTED') AND superseded_by_proposal_id IS NULL").param("successor",id).param("now",now).param("parent",parent).update();if(linked==0)throw new AiProviderException("ACTIVE_SUCCESSOR_ALREADY_EXISTS",false,"Proposal already has a successor");audit(String.valueOf(regeneration.get("actor")),"AI_PROPOSAL_REGENERATED",id,Map.of("predecessorProposalId",parent,"rootProposalId",root,"generationAttempt",attempt,"jobId",job));audit(String.valueOf(regeneration.get("actor")),"AI_PROPOSAL_SUPERSEDED",parent,Map.of("successorProposalId",id));audit(String.valueOf(regeneration.get("actor")),"AI_PROPOSAL_LINEAGE_LINKED",id,Map.of("predecessorProposalId",parent,"rootProposalId",root));}}
  private void validateRequest(QuestionGenerationProviderClient.Request r){if(r.proposalCount()<1||r.proposalCount()>3)throw error(HttpStatus.UNPROCESSABLE_ENTITY,"AI_QUESTION_GENERATION_INVALID_PROPOSAL_COUNT","Request one to three proposals");if(r.questionType()!=null&&!List.of("SINGLE_CHOICE","TRUE_FALSE","MULTIPLE_CHOICE").contains(r.questionType()))throw error(HttpStatus.UNPROCESSABLE_ENTITY,"AI_QUESTION_GENERATION_QUESTION_TYPE_INVALID","Unsupported question type");if(!List.of("sv","en").contains(r.target().language().toLowerCase()))throw error(HttpStatus.UNPROCESSABLE_ENTITY,"AI_QUESTION_GENERATION_FACT_UNSUPPORTED_LANGUAGE","Unsupported fact language");if(!sha(r.target().text()).equals(r.target().checksum()))throw error(HttpStatus.UNPROCESSABLE_ENTITY,"AI_QUESTION_GENERATION_FACT_INVALID","Fact checksum does not match content");verifySnapshot(r);}
  private void verifySnapshot(QuestionGenerationProviderClient.Request r){if(r.target().text()==null||r.target().text().isBlank()||r.target().text().length()>5000||!sha(r.target().text()).equals(r.target().checksum()))throw new AiProviderException("AI_QUESTION_GENERATION_INPUT_STALE",false,"Immutable fact snapshot is invalid");for(var s:r.context().sources()){if(s.contentExcerpt()==null||s.contentExcerpt().length()>12000||!sha(s.contentExcerpt()).equals(s.checksum()))throw new AiProviderException("AI_QUESTION_GENERATION_SOURCE_CHANGED",false,"Immutable Source snapshot is invalid");}}
  private boolean cancelled(UUID id){return jdbc.sql("SELECT cancellation_requested FROM ai_generation_job WHERE id=:id").param("id",id).query(Boolean.class).single();}
  private void validateRejection(String code,String comment){var allowed=List.of("FACTUALLY_INCORRECT","AMBIGUOUS","DUPLICATE","POOR_DISTRACTORS","WRONG_CORRECT_ANSWER","WRONG_DIFFICULTY","WRONG_BLOOM_LEVEL","WRONG_QUESTION_TYPE","UNSUPPORTED_BY_KNOWLEDGE_FACT","UNSUPPORTED_BY_SOURCE","LANGUAGE_QUALITY","READABILITY","BIAS_OR_SAFETY","FORMAT_INVALID","OTHER");if(code==null||!allowed.contains(code))throw error(HttpStatus.UNPROCESSABLE_ENTITY,"AI_QUESTION_REJECTION_REASON_INVALID","A supported rejection reason is required");if(comment!=null&&comment.length()>1000)throw error(HttpStatus.UNPROCESSABLE_ENTITY,"AI_QUESTION_REJECTION_COMMENT_INVALID","Reviewer comment is too long");if("OTHER".equals(code)&&(comment==null||comment.isBlank()))throw error(HttpStatus.UNPROCESSABLE_ENTITY,"AI_QUESTION_REJECTION_COMMENT_REQUIRED","Reviewer comment is required for OTHER");}
  private AiApiException stateConflict(Map<String,Object> proposal,String action){String status=String.valueOf(proposal.get("status"));String code=switch(status){case "ACCEPTED"->"AI_QUESTION_PROPOSAL_ALREADY_ACCEPTED";case "REJECTED"->"AI_QUESTION_PROPOSAL_ALREADY_REJECTED";case "SUPERSEDED"->"AI_QUESTION_PROPOSAL_ALREADY_SUPERSEDED";default->"AI_QUESTION_PROPOSAL_STALE";};return error(HttpStatus.CONFLICT,code,"Proposal cannot be "+action+" in its current state");}
  private Map<String,Object> regenerationResult(UUID job,UUID parent){var result=new java.util.LinkedHashMap<String,Object>();result.put("jobId",job);result.put("parentProposalId",parent);result.put("status",get(job).get("status"));result.put("location","/ai/question-generation-jobs/"+job);return result;}
  private void audit(String actor,String action,UUID entity,Map<String,Object> metadata){jdbc.sql("INSERT INTO ai_audit_event(id,occurred_at,actor_id,action,entity_type,entity_id,metadata) VALUES(:id,:now,:actor,:action,'AI_QUESTION_PROPOSAL',:entity,CAST(:metadata AS jsonb))").param("id",UUID.randomUUID()).param("now",now()).param("actor",actor).param("action",action).param("entity",entity).param("metadata",json(metadata)).update();}
  private void cancelRunning(UUID id){jdbc.sql("UPDATE ai_generation_job SET status='CANCELLED',cancelled_at=:now,version=version+1 WHERE id=:id").param("now",now()).param("id",id).update();}
  private void failOrRetry(UUID id,int retries,AiProviderException e){if(e.transientFailure()&&retries<maxRetries)jdbc.sql("UPDATE ai_generation_job SET status='QUEUED',retry_count=retry_count+1,next_attempt_at=:next,error_code=:code,error_message=:message,version=version+1 WHERE id=:id").param("next",now().plusSeconds(1L<<(retries+1))).param("code",e.code()).param("message",sanitize(e.getMessage())).param("id",id).update();else jdbc.sql("UPDATE ai_generation_job SET status='FAILED',failed_at=:now,error_code=:code,error_message=:message,version=version+1 WHERE id=:id").param("now",now()).param("code",e.code()).param("message",sanitize(e.getMessage())).param("id",id).update();metrics.counter("ai.question_generation.jobs","result","failed").increment();}
  private int inputSize(QuestionGenerationProviderClient.Request r){return r.target().text().length()+r.context().sources().stream().mapToInt(s->s.contentExcerpt().length()).sum();}
  private String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException(e);}}
  private Object read(String value){try{return mapper.readValue(value,new TypeReference<Object>(){});}catch(Exception e){return List.of();}}
  private String checksum(Object value){return sha(json(value));}private String sha(String value){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
  private String blank(String value){return value==null||value.isBlank()?null:value.trim();}private String sanitize(String value){if(value==null)return null;String clean=value.replaceAll("(?i)(key|token|secret)=[^ ,]+","$1=[redacted]");return clean.substring(0,Math.min(500,clean.length()));}
  private OffsetDateTime now(){return OffsetDateTime.now(ZoneOffset.UTC);}private AiApiException error(HttpStatus status,String code,String message){return new AiApiException(status,code,message);}
}
