package se.medbo.examplatform.ai.question;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Types;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import se.medbo.examplatform.ai.generation.AiApiException;

@Service
final class QuestionGenerationBatchService {
  record Item(QuestionGenerationProviderClient.Target target,QuestionGenerationProviderClient.Context context,
              String questionType,String targetDifficulty,String targetBloomLevel){}
  record Definition(String scopeType,UUID scopeId,String scopeLabel,String language,Map<String,Object> configuration,
                    String requestedBy,String idempotencyKey,List<Item> items){}
  private static final Set<String> RETRYABLE=Set.of("AI_REQUEST_TIMEOUT","AI_PROVIDER_UNAVAILABLE","AI_PROVIDER_RATE_LIMITED","PROVIDER_RATE_LIMITED","PROVIDER_TIMEOUT");
  private final JdbcClient jdbc;private final ObjectMapper mapper;private final QuestionGenerationJobService jobs;private final TransactionTemplate transactions;
  private final String provider,model,workerId=UUID.randomUUID().toString();private final int concurrency,maxAttempts;
  QuestionGenerationBatchService(JdbcClient jdbc,ObjectMapper mapper,QuestionGenerationJobService jobs,PlatformTransactionManager tx,
      @Value("${ai.editorial.provider:FAKE}")String provider,@Value("${ai.editorial.model:deterministic-v1}")String model,
      @Value("${ai.question-batches.concurrency:2}")int concurrency,@Value("${ai.question-batches.max-attempts:3}")int maxAttempts){
    this.jdbc=jdbc;this.mapper=mapper;this.jobs=jobs;this.transactions=new TransactionTemplate(tx);this.provider=provider;this.model=model;
    this.concurrency=Math.max(1,Math.min(concurrency,8));this.maxAttempts=Math.max(1,Math.min(maxAttempts,5));
  }

  Map<String,Object> create(Definition definition){
    validate(definition);String checksum=sha(json(Map.of("scopeType",definition.scopeType(),"scopeId",definition.scopeId(),"language",definition.language(),"configuration",definition.configuration(),"items",definition.items())));
    var existing=jdbc.sql("SELECT id,definition_checksum FROM ai_question_generation_batch WHERE requested_by=:actor AND idempotency_key=:key")
        .param("actor",definition.requestedBy()).param("key",definition.idempotencyKey()).query().listOfRows();
    if(!existing.isEmpty()){if(!checksum.equals(existing.getFirst().get("definition_checksum")))throw error(HttpStatus.CONFLICT,"BATCH_IDEMPOTENCY_CONFLICT","The idempotency key was already used with a different batch definition");return batch((UUID)existing.getFirst().get("id"));}
    UUID id=UUID.randomUUID();OffsetDateTime now=now();
    transactions.executeWithoutResult(ignored->{
      jdbc.sql("INSERT INTO ai_question_generation_batch(id,scope_type,scope_id,scope_label,language,configuration,definition_checksum,requested_by,idempotency_key,status,provider,model,created_at) VALUES(:id,:type,:scope,:label,:language,CAST(:configuration AS jsonb),:checksum,:actor,:key,'PENDING',:provider,:model,:now)")
          .param("id",id).param("type",definition.scopeType()).param("scope",definition.scopeId(),Types.OTHER).param("label",definition.scopeLabel(),Types.VARCHAR).param("language",definition.language()).param("configuration",json(definition.configuration())).param("checksum",checksum).param("actor",definition.requestedBy()).param("key",definition.idempotencyKey()).param("provider",provider).param("model",model).param("now",now).update();
      int sequence=0;for(var item:definition.items())jdbc.sql("INSERT INTO ai_question_generation_batch_item(id,batch_id,sequence,target_snapshot,context_snapshot,knowledge_fact_id,knowledge_fact_version_id,knowledge_fact_version,knowledge_fact_checksum,topic_id,subject_id,exam_version_id,question_type,language,target_difficulty,target_bloom_level,status,created_at) VALUES(:id,:batch,:sequence,CAST(:target AS jsonb),CAST(:context AS jsonb),:fact,:factVersion,:version,:checksum,:topic,:subject,:examVersion,:type,:language,:difficulty,:bloom,'PENDING',:now)")
          .param("id",UUID.randomUUID()).param("batch",id).param("sequence",sequence++).param("target",json(item.target())).param("context",json(item.context())).param("fact",item.target().knowledgeFactId()).param("factVersion",item.target().knowledgeFactVersionId()).param("version",item.target().version()).param("checksum",item.target().checksum()).param("topic",item.context().topicId(),Types.OTHER).param("subject",item.context().subjectId(),Types.OTHER).param("examVersion",item.context().examVersionId(),Types.OTHER).param("type",item.questionType()).param("language",definition.language()).param("difficulty",item.targetDifficulty(),Types.VARCHAR).param("bloom",item.targetBloomLevel(),Types.VARCHAR).param("now",now).update();
      audit(definition.requestedBy(),"AI_BATCH_CREATED",id,Map.of("scopeType",definition.scopeType(),"requestedCount",definition.items().size()));
    });return batch(id);
  }

  Map<String,Object> batch(UUID id){var rows=jdbc.sql("SELECT id,scope_type AS \"scopeType\",scope_id AS \"scopeId\",scope_label AS \"scopeLabel\",language,configuration::text AS configuration,requested_by AS \"createdBy\",status,provider,model,created_at AS \"createdAt\",started_at AS \"startedAt\",completed_at AS \"completedAt\",cancelled_at AS \"cancelledAt\",version FROM ai_question_generation_batch WHERE id=:id").param("id",id).query().listOfRows();if(rows.isEmpty())throw error(HttpStatus.NOT_FOUND,"BATCH_NOT_FOUND","Question generation batch was not found");var result=rows.getFirst();result.put("configuration",read(String.valueOf(result.get("configuration"))));result.putAll(progress(id));return result;}
  Map<String,Object> list(int page,int size,String status,String scopeType,String createdBy){page=Math.max(0,page);size=Math.min(100,Math.max(1,size));var count=jdbc.sql("SELECT count(*) FROM ai_question_generation_batch WHERE (CAST(:status AS text) IS NULL OR status=:status) AND (CAST(:scopeType AS text) IS NULL OR scope_type=:scopeType) AND (CAST(:actor AS text) IS NULL OR requested_by=:actor)").param("status",blank(status)).param("scopeType",blank(scopeType)).param("actor",blank(createdBy)).query(Long.class).single();var ids=jdbc.sql("SELECT id FROM ai_question_generation_batch WHERE (CAST(:status AS text) IS NULL OR status=:status) AND (CAST(:scopeType AS text) IS NULL OR scope_type=:scopeType) AND (CAST(:actor AS text) IS NULL OR requested_by=:actor) ORDER BY created_at DESC,id LIMIT :size OFFSET :offset").param("status",blank(status)).param("scopeType",blank(scopeType)).param("actor",blank(createdBy)).param("size",size).param("offset",page*size).query(UUID.class).list();return page(ids.stream().map(this::batch).toList(),page,size,count);}
  Map<String,Object> items(UUID batchId,int page,int size,String status,UUID factId){batch(batchId);page=Math.max(0,page);size=Math.min(100,Math.max(1,size));String where=" WHERE batch_id=:batch AND (CAST(:status AS text) IS NULL OR status=:status) AND (CAST(:fact AS uuid) IS NULL OR knowledge_fact_id=:fact) ";long total=jdbc.sql("SELECT count(*) FROM ai_question_generation_batch_item"+where).param("batch",batchId).param("status",blank(status)).param("fact",factId).query(Long.class).single();var rows=jdbc.sql("SELECT id,batch_id AS \"batchId\",sequence,knowledge_fact_id AS \"knowledgeFactId\",knowledge_fact_version_id AS \"knowledgeFactVersionId\",question_type AS \"questionType\",language,target_difficulty AS \"targetDifficulty\",target_bloom_level AS \"targetBloomLevel\",status,generation_job_id AS \"generationJobId\",proposal_id AS \"proposalId\",attempt_count AS \"attemptCount\",rate_limit_count AS \"rateLimitCount\",failure_code AS \"failureCode\",failure_message AS \"failureMessage\",next_retry_at AS \"nextRetryAt\",started_at AS \"startedAt\",completed_at AS \"completedAt\",created_at AS \"createdAt\",version FROM ai_question_generation_batch_item"+where+" ORDER BY sequence LIMIT :size OFFSET :offset").param("batch",batchId).param("status",blank(status)).param("fact",factId).param("size",size).param("offset",page*size).query().listOfRows();return page(rows,page,size,total);}
  Map<String,Object> proposals(UUID batchId,int page,int size,String status){batch(batchId);page=Math.max(0,page);size=Math.min(100,Math.max(1,size));String where=" FROM ai_question_generation_batch_item i JOIN LATERAL (SELECT candidate.id,candidate.status FROM ai_question_proposal root JOIN ai_question_proposal candidate ON candidate.id=root.id OR candidate.root_proposal_id=root.id WHERE root.id=i.proposal_id ORDER BY candidate.generation_attempt DESC,candidate.created_at DESC LIMIT 1) p ON true WHERE i.batch_id=:batch AND (CAST(:status AS text) IS NULL OR p.status=:status) ";long total=jdbc.sql("SELECT count(*)"+where).param("batch",batchId).param("status",blank(status)).query(Long.class).single();var ids=jdbc.sql("SELECT p.id"+where+" ORDER BY i.sequence LIMIT :size OFFSET :offset").param("batch",batchId).param("status",blank(status)).param("size",size).param("offset",page*size).query(UUID.class).list();var values=ids.stream().map(id->{var value=jobs.withIntelligence(jobs.proposal(id));assignment(id).ifPresent(value::putAll);return value;}).toList();return page(values,page,size,total);}

  Map<String,Object> cancel(UUID id,String actor){var current=batch(id);String status=String.valueOf(current.get("status"));if("CANCELLED".equals(status)||"CANCELLING".equals(status))return current;if(!List.of("PENDING","RUNNING").contains(status))throw error(HttpStatus.CONFLICT,"BATCH_NOT_CANCELLABLE","The batch can no longer be cancelled");jdbc.sql("UPDATE ai_question_generation_batch SET cancellation_requested=true,status='CANCELLING',version=version+1 WHERE id=:id").param("id",id).update();jdbc.sql("UPDATE ai_question_generation_batch_item SET status='CANCELLED',completed_at=:now,version=version+1 WHERE batch_id=:id AND status IN ('PENDING','RETRY_SCHEDULED')").param("now",now()).param("id",id).update();audit(actor,"AI_BATCH_CANCELLATION_REQUESTED",id,Map.of());refresh(id);return batch(id);}
  Map<String,Object> retryFailed(UUID id,List<UUID> selected,String actor){batch(id);var ids=jdbc.sql("SELECT id FROM ai_question_generation_batch_item WHERE batch_id=:batch AND status='FAILED' AND attempt_count<:max AND failure_code=ANY(:codes)").param("batch",id).param("max",maxAttempts).param("codes",RETRYABLE.toArray(String[]::new)).query(UUID.class).list();if(selected!=null&&!selected.isEmpty())ids=ids.stream().filter(selected::contains).toList();for(UUID item:ids)jdbc.sql("UPDATE ai_question_generation_batch_item SET status='RETRY_SCHEDULED',next_retry_at=:now,failure_message=NULL,version=version+1 WHERE id=:id").param("now",now()).param("id",item).update();if(!ids.isEmpty())jdbc.sql("UPDATE ai_question_generation_batch SET status='RUNNING',completed_at=NULL,version=version+1 WHERE id=:id").param("id",id).update();audit(actor,"AI_BATCH_FAILED_ITEMS_RETRIED",id,Map.of("retried",ids.size()));return batch(id);}
  Map<String,Object> assign(List<UUID> proposalIds,String reviewer,String actor,OffsetDateTime deadline){if(proposalIds==null||proposalIds.isEmpty())throw error(HttpStatus.UNPROCESSABLE_ENTITY,"BULK_ACTION_EMPTY_SELECTION","Select at least one proposal");var results=new ArrayList<Map<String,Object>>();for(UUID id:proposalIds)try{jobs.proposal(id);jdbc.sql("INSERT INTO ai_question_proposal_review_assignment(proposal_id,assigned_reviewer_id,assigned_by,assigned_at,review_deadline) VALUES(:id,:reviewer,:actor,:now,:deadline) ON CONFLICT(proposal_id) DO UPDATE SET assigned_reviewer_id=:reviewer,assigned_by=:actor,assigned_at=:now,review_deadline=:deadline,review_status='ASSIGNED',version=ai_question_proposal_review_assignment.version+1").param("id",id).param("reviewer",reviewer).param("actor",actor).param("now",now()).param("deadline",deadline,Types.TIMESTAMP_WITH_TIMEZONE).update();audit(actor,"AI_REVIEW_ASSIGNED",id,Map.of("reviewer",reviewer));results.add(outcome(id,"SUCCEEDED",null));}catch(AiApiException e){results.add(outcome(id,"FAILED",e.code()));}return bulk(results);}
  Map<String,Object> unassign(List<UUID> ids,String actor){if(ids==null||ids.isEmpty())throw error(HttpStatus.UNPROCESSABLE_ENTITY,"BULK_ACTION_EMPTY_SELECTION","Select at least one proposal");var results=new ArrayList<Map<String,Object>>();for(UUID id:ids){int changed=jdbc.sql("DELETE FROM ai_question_proposal_review_assignment WHERE proposal_id=:id").param("id",id).update();if(changed>0)audit(actor,"AI_REVIEW_UNASSIGNED",id,Map.of());results.add(outcome(id,changed>0?"SUCCEEDED":"FAILED",changed>0?null:"REVIEW_ASSIGNMENT_NOT_FOUND"));}return bulk(results);}

  @Scheduled(fixedDelayString="${ai.question-batches.poll-interval-ms:500}")void work(){
    recoverStale();int active=jdbc.sql("SELECT count(*) FROM ai_question_generation_batch_item WHERE status='PROCESSING' AND lease_until>now()").query(Integer.class).single();
    for(int slot=active;slot<concurrency;slot++){UUID item=claim();if(item==null)break;start(item);}
    monitor();
  }
  private UUID claim(){return transactions.execute(status->{var ids=jdbc.sql("SELECT i.id FROM ai_question_generation_batch_item i JOIN ai_question_generation_batch b ON b.id=i.batch_id WHERE i.status IN ('PENDING','RETRY_SCHEDULED') AND (i.next_retry_at IS NULL OR i.next_retry_at<=now()) AND b.status IN ('PENDING','RUNNING') AND b.cancellation_requested=false ORDER BY i.created_at,i.sequence FOR UPDATE OF i SKIP LOCKED LIMIT 1").query(UUID.class).list();if(ids.isEmpty())return null;UUID id=ids.getFirst();jdbc.sql("UPDATE ai_question_generation_batch_item SET status='PROCESSING',lease_owner=:owner,lease_until=now()+interval '2 minutes',started_at=coalesce(started_at,now()),attempt_count=attempt_count+1,version=version+1 WHERE id=:id").param("owner",workerId).param("id",id).update();UUID batch=jdbc.sql("SELECT batch_id FROM ai_question_generation_batch_item WHERE id=:id").param("id",id).query(UUID.class).single();jdbc.sql("UPDATE ai_question_generation_batch SET status='RUNNING',started_at=coalesce(started_at,now()),version=version+1 WHERE id=:id AND status='PENDING'").param("id",batch).update();return id;});}
  private void start(UUID itemId){var item=jdbc.sql("SELECT batch_id,target_snapshot::text AS target,context_snapshot::text AS context,question_type,target_difficulty,target_bloom_level,attempt_count FROM ai_question_generation_batch_item WHERE id=:id").param("id",itemId).query().singleRow();try{var target=mapper.readValue(String.valueOf(item.get("target")),QuestionGenerationProviderClient.Target.class);var context=mapper.readValue(String.valueOf(item.get("context")),QuestionGenerationProviderClient.Context.class);var request=new QuestionGenerationProviderClient.Request(target,context,1,String.valueOf(item.get("question_type")),"question-generation-batch-v1",null,null,0,null,(String)item.get("target_difficulty"),(String)item.get("target_bloom_level"));var job=jobs.create(request,"batch:"+item.get("batch_id"),"batch-item:"+itemId,provider,model);jdbc.sql("UPDATE ai_question_generation_batch_item SET generation_job_id=:job,lease_until=now()+interval '10 minutes',version=version+1 WHERE id=:id AND status='PROCESSING'").param("job",job.get("id")).param("id",itemId).update();audit("system","AI_BATCH_ITEM_STARTED",itemId,Map.of("generationJobId",job.get("id")));}catch(Exception e){fail(itemId,"BATCH_ITEM_INITIALIZATION_FAILED","The item could not be initialized",false);}}
  private void monitor(){var rows=jdbc.sql("SELECT i.id,i.batch_id,i.generation_job_id,i.attempt_count,j.status,j.error_code,j.error_message FROM ai_question_generation_batch_item i JOIN ai_generation_job j ON j.id=i.generation_job_id WHERE i.status='PROCESSING' ORDER BY i.started_at LIMIT 100").query().listOfRows();for(var row:rows){String state=String.valueOf(row.get("status"));if(List.of("QUEUED","RUNNING").contains(state)){jdbc.sql("UPDATE ai_question_generation_batch_item SET lease_until=now()+interval '10 minutes' WHERE id=:id").param("id",row.get("id")).update();continue;}UUID item=(UUID)row.get("id"),batch=(UUID)row.get("batch_id");if(List.of("COMPLETED","PARTIALLY_COMPLETED").contains(state)){var proposals=jobs.proposals((UUID)row.get("generation_job_id"));if(proposals.isEmpty())fail(item,"GENERATION_NO_PROPOSAL","Generation completed without a proposal",false);else{UUID proposal=(UUID)proposals.getFirst().get("id");jdbc.sql("UPDATE ai_question_generation_batch_item SET status='GENERATED',proposal_id=:proposal,completed_at=now(),lease_owner=NULL,lease_until=NULL,version=version+1 WHERE id=:id").param("proposal",proposal).param("id",item).update();audit("system","AI_BATCH_ITEM_GENERATED",item,Map.of("proposalId",proposal));}}else{String code=String.valueOf(row.get("error_code"));fail(item,code,(String)row.get("error_message"),RETRYABLE.contains(code));}refresh(batch);}}
  private void fail(UUID item,String code,String message,boolean retryable){var row=jdbc.sql("SELECT batch_id,attempt_count FROM ai_question_generation_batch_item WHERE id=:id").param("id",item).query().singleRow();int attempts=(Integer)row.get("attempt_count");String status=retryable&&attempts<maxAttempts?"RETRY_SCHEDULED":"FAILED";jdbc.sql("UPDATE ai_question_generation_batch_item SET status=:status,failure_code=:code,failure_message=:message,last_failure_at=now(),next_retry_at=CASE WHEN :retry THEN now()+make_interval(secs=>CAST(power(2,:attempts) AS integer)) ELSE NULL END,rate_limit_count=rate_limit_count+CASE WHEN :rate THEN 1 ELSE 0 END,lease_owner=NULL,lease_until=NULL,version=version+1 WHERE id=:id").param("status",status).param("code",code).param("message",safe(message)).param("retry","RETRY_SCHEDULED".equals(status)).param("attempts",attempts).param("rate",code!=null&&code.contains("RATE_LIMIT")).param("id",item).update();audit("system","RETRY_SCHEDULED".equals(status)?"AI_BATCH_ITEM_RETRY_SCHEDULED":"AI_BATCH_ITEM_FAILED",item,Map.of("failureCode",code==null?"UNKNOWN":code));refresh((UUID)row.get("batch_id"));}
  private void refresh(UUID batch){var counts=counts(batch);int requested=n(counts,"requested"),active=n(counts,"pending")+n(counts,"processing")+n(counts,"retryScheduled");var state=jdbc.sql("SELECT status,cancellation_requested FROM ai_question_generation_batch WHERE id=:id").param("id",batch).query().singleRow();String next;if(Boolean.TRUE.equals(state.get("cancellation_requested")))next=active==0?"CANCELLED":"CANCELLING";else if(active>0)next="RUNNING";else if(n(counts,"generated")==requested)next="COMPLETED";else if(n(counts,"generated")>0)next="PARTIALLY_COMPLETED";else next="FAILED";jdbc.sql("UPDATE ai_question_generation_batch SET status=:status,completed_at=CASE WHEN :terminal THEN coalesce(completed_at,now()) ELSE NULL END,cancelled_at=CASE WHEN :cancelled THEN coalesce(cancelled_at,now()) ELSE cancelled_at END,version=version+1 WHERE id=:id AND status<>:status").param("status",next).param("terminal",List.of("COMPLETED","PARTIALLY_COMPLETED","FAILED","CANCELLED").contains(next)).param("cancelled","CANCELLED".equals(next)).param("id",batch).update();}
  private void recoverStale(){jdbc.sql("UPDATE ai_question_generation_batch_item SET status=CASE WHEN attempt_count<:max THEN 'RETRY_SCHEDULED' ELSE 'FAILED' END,failure_code='PROCESSING_LEASE_EXPIRED',failure_message='Processing lease expired and was recovered',next_retry_at=CASE WHEN attempt_count<:max THEN now() ELSE NULL END,lease_owner=NULL,lease_until=NULL,version=version+1 WHERE status='PROCESSING' AND lease_until<now() AND generation_job_id IS NULL").param("max",maxAttempts).update();}
  private Map<String,Object> progress(UUID batch){var counts=counts(batch);int requested=n(counts,"requested"),generated=n(counts,"generated"),failed=n(counts,"failed"),cancelled=n(counts,"cancelled");var review=jdbc.sql("SELECT count(*) FILTER(WHERE p.status='ACCEPTED') AS accepted,count(*) FILTER(WHERE p.status='REJECTED') AS rejected,count(*) FILTER(WHERE p.status='SUPERSEDED') AS superseded,count(*) FILTER(WHERE p.status='PROPOSED') AS unreviewed FROM ai_question_generation_batch_item i JOIN LATERAL (SELECT candidate.status FROM ai_question_proposal root JOIN ai_question_proposal candidate ON candidate.id=root.id OR candidate.root_proposal_id=root.id WHERE root.id=i.proposal_id ORDER BY candidate.generation_attempt DESC,candidate.created_at DESC LIMIT 1) p ON true WHERE i.batch_id=:batch").param("batch",batch).query().singleRow();var result=new LinkedHashMap<String,Object>(counts);result.putAll(review);int reviewed=((Number)review.get("accepted")).intValue()+((Number)review.get("rejected")).intValue();result.put("reviewed",reviewed);result.put("generationProgressPercentage",requested==0?0:(generated+failed+cancelled)*100/requested);result.put("reviewProgressPercentage",generated==0?0:reviewed*100/generated);result.put("acceptanceProgressPercentage",generated==0?0:((Number)review.get("accepted")).intValue()*100/generated);var usage=jdbc.sql("SELECT coalesce(sum(j.input_tokens),0) AS \"inputTokens\",coalesce(sum(j.output_tokens),0) AS \"outputTokens\",coalesce(sum(j.total_tokens),0) AS \"totalTokens\" FROM ai_question_generation_batch_item i LEFT JOIN ai_generation_job j ON j.id=i.generation_job_id WHERE i.batch_id=:batch").param("batch",batch).query().singleRow();result.put("usage",usage);return result;}
  private Map<String,Object> counts(UUID batch){return jdbc.sql("SELECT count(*) AS requested,count(*) FILTER(WHERE status='PENDING') AS pending,count(*) FILTER(WHERE status='PROCESSING') AS processing,count(*) FILTER(WHERE status='RETRY_SCHEDULED') AS \"retryScheduled\",count(*) FILTER(WHERE status='GENERATED') AS generated,count(*) FILTER(WHERE status='FAILED') AS failed,count(*) FILTER(WHERE status='CANCELLED') AS cancelled FROM ai_question_generation_batch_item WHERE batch_id=:batch").param("batch",batch).query().singleRow();}
  private java.util.Optional<Map<String,Object>> assignment(UUID proposal){var rows=jdbc.sql("SELECT assigned_reviewer_id AS \"assignedReviewerId\",assigned_by AS \"assignedBy\",assigned_at AS \"assignedAt\",review_deadline AS \"reviewDeadline\",review_status AS \"reviewWorkflowStatus\" FROM ai_question_proposal_review_assignment WHERE proposal_id=:id").param("id",proposal).query().listOfRows();return rows.stream().findFirst();}
  private void validate(Definition d){if(d.items()==null||d.items().isEmpty())throw error(HttpStatus.UNPROCESSABLE_ENTITY,"BATCH_SCOPE_EMPTY","The selected scope contains no eligible Knowledge Facts");if(d.items().size()>200)throw error(HttpStatus.UNPROCESSABLE_ENTITY,"BATCH_LIMIT_EXCEEDED","The batch exceeds the configured maximum of 200 proposals");if(d.items().stream().map(i->i.target().knowledgeFactId()+"|"+i.questionType()+"|"+i.targetDifficulty()+"|"+i.targetBloomLevel()).distinct().count()!=d.items().size())throw error(HttpStatus.UNPROCESSABLE_ENTITY,"BATCH_DUPLICATE_ITEM","The resolved batch contains duplicate generation items");if(!List.of("sv","en").contains(d.language()))throw error(HttpStatus.UNPROCESSABLE_ENTITY,"BATCH_UNSUPPORTED_LANGUAGE","The batch language is unsupported");}
  private Map<String,Object> page(List<?> items,int page,int size,long total){return Map.of("items",items,"page",page,"size",size,"totalItems",total,"totalPages",(total+size-1)/size);}
  private Map<String,Object> outcome(UUID id,String outcome,String code){var value=new LinkedHashMap<String,Object>();value.put("proposalId",id);value.put("outcome",outcome);value.put("errorCode",code);return value;}
  private Map<String,Object> bulk(List<Map<String,Object>> results){long success=results.stream().filter(r->"SUCCEEDED".equals(r.get("outcome"))).count();return Map.of("requested",results.size(),"succeeded",success,"failed",results.size()-success,"results",results);}
  private void audit(String actor,String action,UUID entity,Map<String,Object> metadata){jdbc.sql("INSERT INTO ai_audit_event(id,occurred_at,actor_id,action,entity_type,entity_id,metadata) VALUES(:id,:now,:actor,:action,'AI_QUESTION_BATCH',:entity,CAST(:metadata AS jsonb))").param("id",UUID.randomUUID()).param("now",now()).param("actor",actor).param("action",action).param("entity",entity).param("metadata",json(metadata)).update();}
  private String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException(e);}}
  private Object read(String value){try{return mapper.readValue(value,new TypeReference<Object>(){});}catch(Exception e){return Map.of();}}
  private String sha(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
  private int n(Map<String,Object> values,String key){return ((Number)values.get(key)).intValue();}
  private String safe(String value){if(value==null)return null;return value.substring(0,Math.min(500,value.length()));}
  private String blank(String value){return value==null||value.isBlank()?null:value;}
  private OffsetDateTime now(){return OffsetDateTime.now(ZoneOffset.UTC);}
  private AiApiException error(HttpStatus status,String code,String message){return new AiApiException(status,code,message);}
}
