import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { AiQuestionGenerationWorkspace } from "./AiQuestionGenerationWorkspace";
import type { KnowledgeFact } from "../../../api/generated";
import { adminQueryKeys } from "../../../api/query-keys/adminQueryKeys";

const fact: KnowledgeFact = { id:"11111111-1111-1111-1111-111111111111",learningObjectiveId:"22222222-2222-2222-2222-222222222222",currentVersionId:"33333333-3333-3333-3333-333333333333",canonicalStatement:"Riksdagen beslutar om Sveriges lagar.",reviewStatus:"APPROVED",status:"ACTIVE",learningObjectiveTitle:"Demokrati",topicId:"44444444-4444-4444-4444-444444444444",topicName:"Styrelseskick",subjectId:"55555555-5555-5555-5555-555555555555",subjectName:"Samhälle",sourceCount:1,sourceIds:["66666666-6666-6666-6666-666666666666"],createdAt:"2026-07-21T08:00:00Z",updatedAt:"2026-07-21T08:00:00Z",version:2 };
const job={id:"77777777-7777-7777-7777-777777777777",operationType:"GENERATE_QUESTIONS_FROM_FACT",resultType:"QUESTIONS_PROPOSED",requestedBy:"author",requestedCount:1,requestedQuestionType:"SINGLE_CHOICE",targetKnowledgeFactId:fact.id,targetKnowledgeFactVersionId:fact.currentVersionId,targetVersion:1,targetChecksum:"a".repeat(64),proposalCount:1,status:"COMPLETED",provider:"FAKE",model:"deterministic-v1",promptVersion:"question-generation-foundation-v1",createdAt:"2026-07-21T08:00:00Z",retryCount:0,version:2};
const proposal={id:"88888888-8888-8888-8888-888888888888",generationJobId:job.id,proposalOrder:0,operationType:"GENERATE_QUESTIONS_FROM_FACT",questionType:"SINGLE_CHOICE",questionText:"Vilken institution beslutar om Sveriges lagar?",language:"sv",answerOptions:[{id:"99999999-9999-9999-9999-999999999991",optionKey:"A",displayOrder:0,text:"Riksdagen",correct:true},{id:"99999999-9999-9999-9999-999999999992",optionKey:"B",displayOrder:1,text:"Polisen",correct:false}],explanation:fact.canonicalStatement,rationale:"Tests the approved fact directly.",targetKnowledgeFactId:fact.id,targetKnowledgeFactVersionId:fact.currentVersionId,targetVersion:1,targetChecksum:"a".repeat(64),learningObjectiveId:fact.learningObjectiveId,warnings:[],evidence:[{id:"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",evidenceType:"KNOWLEDGE_FACT",supportedClaim:fact.canonicalStatement,displayOrder:0}],validationStatus:"VALID",status:"PROPOSED",provider:"FAKE",model:"deterministic-v1",promptVersion:"question-generation-foundation-v1",createdAt:"2026-07-21T08:00:00Z",updatedAt:"2026-07-21T08:00:00Z",version:0};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});}
function renderWorkspace(override:Partial<KnowledgeFact>={},canGenerate=true){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<QueryClientProvider client={client}><AiQuestionGenerationWorkspace fact={{...fact,...override}} canGenerate={canGenerate} canInspect sourcesReady /></QueryClientProvider>);}
describe("AI question generation workspace",()=>{
  it("enables approved facts and shows the bounded generation dialog",async()=>{renderWorkspace();await userEvent.click(screen.getByRole("button",{name:"Generate questions"}));expect(screen.getByRole("dialog")).toHaveTextContent(fact.canonicalStatement);expect(screen.getByLabelText("Number of question proposals")).toHaveDisplayValue("3");expect(screen.getAllByRole("option")).toHaveLength(7);expect(screen.getAllByText(/proposals only/)).toHaveLength(2);});
  it("disables generation with a clear reason for draft and retired facts or missing permission",()=>{const {unmount}=renderWorkspace({reviewStatus:"UNREVIEWED",status:"DRAFT"});expect(screen.getByText(/must be approved/)).toBeInTheDocument();expect(screen.getByRole("button",{name:"Generate questions"})).toBeDisabled();unmount();renderWorkspace({},false);expect(screen.getByText(/do not have permission/)).toBeInTheDocument();});
  it("renders proposals, correct answers, evidence, provenance and rejection confirmation",async()=>{vi.stubGlobal("fetch",vi.fn().mockImplementation((request:Request)=>{if(request.url.includes("/proposals"))return Promise.resolve(json([proposal]));if(request.url.includes("ai-question-generation-jobs")&&request.method==="POST")return Promise.resolve(json(job,202));return Promise.resolve(json(job));}));renderWorkspace();await userEvent.click(screen.getByRole("button",{name:"Generate questions"}));await userEvent.selectOptions(screen.getByLabelText("Number of question proposals"),"1");await userEvent.click(screen.getByRole("button",{name:"Generate"}));expect(await screen.findByRole("heading",{name:proposal.questionText})).toBeInTheDocument();expect(screen.getByText("Proposed correct answer")).toBeInTheDocument();expect(screen.getByText(/Approved Knowledge Fact/)).toBeInTheDocument();expect(screen.getByText(/question-generation-foundation-v1/)).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"Reject proposal"}));expect(screen.getByRole("dialog",{name:"Confirm proposal rejection"})).toBeInTheDocument();});
  it("isolates query state by fact version and job",()=>{expect(adminQueryKeys.ai.questionProposals("fact-a","v1","job-a")).not.toEqual(adminQueryKeys.ai.questionProposals("fact-a","v2","job-a"));expect(adminQueryKeys.ai.questionProposals("fact-a","v1","job-a")).not.toEqual(adminQueryKeys.ai.questionProposals("fact-b","v1","job-a"));expect(adminQueryKeys.ai.questionProposals("fact-a","v1","job-a")).not.toEqual(adminQueryKeys.ai.questionProposals("fact-a","v1","job-b"));});
});
