import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { AiQuestionGenerationWorkspace } from "./AiQuestionGenerationWorkspace";
import type { AiQuestionGenerationEligibility, KnowledgeFact } from "../../../api/generated";
import { adminQueryKeys } from "../../../api/query-keys/adminQueryKeys";

const fact: KnowledgeFact = { id:"11111111-1111-1111-1111-111111111111",learningObjectiveId:"22222222-2222-2222-2222-222222222222",currentVersionId:"33333333-3333-3333-3333-333333333333",canonicalStatement:"Riksdagen beslutar om Sveriges lagar.",reviewStatus:"APPROVED",status:"ACTIVE",learningObjectiveTitle:"Demokrati",topicId:"44444444-4444-4444-4444-444444444444",topicName:"Styrelseskick",subjectId:"55555555-5555-5555-5555-555555555555",subjectName:"Samhälle",sourceCount:1,sourceIds:["66666666-6666-6666-6666-666666666666"],createdAt:"2026-07-21T08:00:00Z",updatedAt:"2026-07-21T08:00:00Z",version:2 };
const job={id:"77777777-7777-7777-7777-777777777777",operationType:"GENERATE_QUESTIONS_FROM_FACT",resultType:"QUESTIONS_PROPOSED",requestedBy:"author",requestedCount:1,requestedQuestionType:"SINGLE_CHOICE",targetKnowledgeFactId:fact.id,targetKnowledgeFactVersionId:fact.currentVersionId,targetVersion:1,targetChecksum:"a".repeat(64),proposalCount:1,status:"COMPLETED",provider:"FAKE",model:"deterministic-v1",promptVersion:"question-generation-foundation-v1",createdAt:"2026-07-21T08:00:00Z",retryCount:0,version:2};
const proposal={id:"88888888-8888-8888-8888-888888888888",generationJobId:job.id,proposalOrder:0,operationType:"GENERATE_QUESTIONS_FROM_FACT",questionType:"SINGLE_CHOICE",questionText:"Vilken institution beslutar om Sveriges lagar?",language:"sv",answerOptions:[{id:"99999999-9999-9999-9999-999999999991",optionKey:"A",displayOrder:0,text:"Riksdagen",correct:true},{id:"99999999-9999-9999-9999-999999999992",optionKey:"B",displayOrder:1,text:"Polisen",correct:false}],explanation:fact.canonicalStatement,rationale:"Tests the approved fact directly.",targetKnowledgeFactId:fact.id,targetKnowledgeFactVersionId:fact.currentVersionId,targetVersion:1,targetChecksum:"a".repeat(64),learningObjectiveId:fact.learningObjectiveId,warnings:[],evidence:[{id:"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",evidenceType:"KNOWLEDGE_FACT",supportedClaim:fact.canonicalStatement,displayOrder:0}],validationStatus:"VALID",status:"PROPOSED",provider:"FAKE",model:"deterministic-v1",promptVersion:"question-generation-foundation-v1",createdAt:"2026-07-21T08:00:00Z",updatedAt:"2026-07-21T08:00:00Z",version:0};
const eligible: AiQuestionGenerationEligibility={eligible:true,reasons:[],factStatus:"ACTIVE",reviewStatus:"APPROVED",sourceContextReady:true,canGenerate:true,canInspect:true};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});}
function mockApi(options:{capability?:AiQuestionGenerationEligibility;history?:unknown[];jobState?:typeof job;proposals?:unknown[]}={}){const capability=options.capability??eligible;const history=options.history??[];vi.stubGlobal("fetch",vi.fn().mockImplementation((request:Request)=>{const url=request.url;if(url.includes("eligibility"))return Promise.resolve(json(capability));if(url.includes("/proposals"))return Promise.resolve(json(options.proposals??[proposal]));if(url.includes("ai-question-generation-jobs")&&request.method==="POST")return Promise.resolve(json(options.jobState??job,202));if(url.includes("/ai/question-generation-jobs/"))return Promise.resolve(json(options.jobState??job));if(url.includes("ai-question-generation-jobs"))return Promise.resolve(json(history));return Promise.resolve(json({}));}));}
function renderWorkspace(value=fact){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return render(<QueryClientProvider client={client}><AiQuestionGenerationWorkspace fact={value}/></QueryClientProvider>);}

describe("AI question generation workspace",()=>{
  it("shows the exact title, no-job state and enabled author action",async()=>{mockApi();renderWorkspace();expect(screen.getByRole("heading",{name:"AI Question Proposals"})).toBeInTheDocument();const button=screen.getByRole("button",{name:"Generate Questions"});await waitFor(()=>expect(button).toBeEnabled());expect(await screen.findByText(/No question-generation job/)).toBeInTheDocument();await userEvent.click(button);expect(screen.getByRole("dialog")).toHaveTextContent(fact.canonicalStatement);});
  it("uses authoritative draft and retired reasons",async()=>{mockApi({capability:{...eligible,eligible:false,reasons:["FACT_NOT_APPROVED","FACT_INACTIVE"]}});const view=renderWorkspace();expect(await screen.findByText("Approve this Knowledge Fact before generating questions.")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Generate Questions"})).toBeDisabled();view.unmount();mockApi({capability:{...eligible,eligible:false,reasons:["FACT_RETIRED"],factStatus:"RETIRED"}});renderWorkspace({...fact,status:"RETIRED"});expect(await screen.findByText("Retired facts cannot be used for question generation.")).toBeInTheDocument();});
  it("explains reviewer and publisher permissions instead of hiding the section",async()=>{mockApi({capability:{...eligible,canGenerate:false}});const view=renderWorkspace();expect(await screen.findByText(/only content authors and administrators/)).toBeInTheDocument();expect(screen.getByRole("button",{name:"Generate Questions"})).toBeDisabled();view.unmount();mockApi({capability:{...eligible,canGenerate:false,canInspect:false}});renderWorkspace();expect(await screen.findByText("Your current role does not allow access to AI question generation.")).toBeInTheDocument();expect(screen.queryByRole("button",{name:"Generate Questions"})).not.toBeInTheDocument();});
  it("rediscovers a terminal job and rejected proposal after mount",async()=>{mockApi({history:[job],proposals:[{...proposal,status:"REJECTED",rejectionReason:"Duplicate"}]});renderWorkspace();expect(await screen.findByRole("heading",{name:proposal.questionText})).toBeInTheDocument();expect(screen.getByText("Rejected")).toBeInTheDocument();expect(screen.getByText(/Duplicate/)).toBeInTheDocument();});
  it("selects a newly generated job and renders its proposal",async()=>{mockApi();renderWorkspace();await userEvent.click(await screen.findByRole("button",{name:"Generate Questions"}));await userEvent.selectOptions(screen.getByLabelText("Number of question proposals"),"1");await userEvent.click(screen.getByRole("button",{name:"Generate"}));expect(await screen.findByRole("heading",{name:proposal.questionText})).toBeInTheDocument();expect(screen.getByText("Proposed correct answer")).toBeInTheDocument();expect(screen.getByText(/question-generation-foundation-v1/)).toBeInTheDocument();});
  it("resumes polling for a recovered active job",async()=>{const running={...job,status:"RUNNING",proposalCount:0};mockApi({history:[running],jobState:running});renderWorkspace();expect(await screen.findByText("RUNNING")).toBeInTheDocument();await waitFor(()=>expect(vi.mocked(fetch).mock.calls.filter(([request])=>(request as Request).url.includes(`/ai/question-generation-jobs/${job.id}`)).length).toBeGreaterThan(1),{timeout:2500});});
  it("isolates eligibility, history, jobs and proposals by fact",()=>{expect(adminQueryKeys.ai.questionEligibility("fact-a","v1")).not.toEqual(adminQueryKeys.ai.questionEligibility("fact-b","v1"));expect(adminQueryKeys.ai.questionHistory("fact-a")).not.toEqual(adminQueryKeys.ai.questionHistory("fact-b"));expect(adminQueryKeys.ai.questionProposals("fact-a","v1","job-a")).not.toEqual(adminQueryKeys.ai.questionProposals("fact-a","v1","job-b"));});
});
