package se.medbo.examplatform.content.deletion;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import se.medbo.examplatform.content.shared.DomainException;

@Service
public class ContentDeletionService {
    private final JdbcClient jdbc;
    public ContentDeletionService(JdbcClient jdbc){this.jdbc=jdbc;}

    @Transactional public void deleteTopic(UUID id,String reason){requireAdmin();var row=lock("topic",id);draft(row);var b=blocks(
            block("LEARNING_OBJECTIVE",count("SELECT count(*) FROM learning_objective WHERE topic_id=:id",id),"learning objectives"),
            block("KNOWLEDGE_FACT",count("SELECT count(*) FROM knowledge_fact f JOIN learning_objective o ON o.id=f.learning_objective_id WHERE o.topic_id=:id",id),"knowledge facts"),
            block("QUESTION",count("SELECT count(*) FROM question q JOIN learning_objective o ON o.id=q.learning_objective_id WHERE o.topic_id=:id",id),"questions"),
            block("RELEASE",count("SELECT count(*) FROM content_release_item i WHERE EXISTS(SELECT 1 FROM question_version qv JOIN learning_objective o ON o.id=qv.learning_objective_id WHERE qv.id=i.content_version_id AND o.topic_id=:id) OR EXISTS(SELECT 1 FROM knowledge_fact_version fv JOIN knowledge_fact f ON f.id=fv.knowledge_fact_id JOIN learning_objective o ON o.id=f.learning_objective_id WHERE fv.id=i.content_version_id AND o.topic_id=:id)",id),"release items"));reject(b,"ARCHIVE");remove("topic",id,reason);}
    @Transactional public void deleteSubject(UUID id,String reason){requireAdmin();var row=lock("subject",id);draft(row);var b=blocks(block("TOPIC",count("SELECT count(*) FROM topic WHERE subject_id=:id",id),"topics"),block("DESCENDANT_CONTENT",count("SELECT count(*) FROM learning_objective o JOIN topic t ON t.id=o.topic_id WHERE t.subject_id=:id",id),"learning objectives"),block("RELEASE",count("SELECT count(*) FROM content_release_item i WHERE EXISTS(SELECT 1 FROM question_version qv JOIN learning_objective o ON o.id=qv.learning_objective_id JOIN topic t ON t.id=o.topic_id WHERE qv.id=i.content_version_id AND t.subject_id=:id)",id),"release items"));reject(b,"ARCHIVE");remove("subject",id,reason);}
    @Transactional public void deleteExamVersion(UUID id,String reason){requireAdmin();var row=lock("exam_version",id);draft(row);var b=blocks(block("SUBJECT",count("SELECT count(*) FROM subject WHERE exam_version_id=:id",id),"subjects"),block("RELEASE",count("SELECT count(*) FROM content_release WHERE exam_version_id=:id",id),"releases"));reject(b,"ARCHIVE");remove("exam_version",id,reason);}
    @Transactional public void deleteExam(UUID id,String reason){requireAdmin();var row=lock("exam",id);draft(row);var b=blocks(block("EXAM_VERSION",count("SELECT count(*) FROM exam_version WHERE exam_id=:id",id),"exam versions"),block("RELEASE",count("SELECT count(*) FROM content_release WHERE exam_id=:id",id),"releases"));reject(b,"ARCHIVE");remove("exam",id,reason);}
    @Transactional public void deleteObjective(UUID id,String reason){requireAdmin();var row=lock("learning_objective",id);draft(row);var b=blocks(block("KNOWLEDGE_FACT",count("SELECT count(*) FROM knowledge_fact WHERE learning_objective_id=:id",id),"knowledge facts"),block("QUESTION",count("SELECT count(*) FROM question WHERE learning_objective_id=:id",id),"questions"),block("RELEASE",count("SELECT count(*) FROM content_release_item i WHERE EXISTS(SELECT 1 FROM question_version v WHERE v.id=i.content_version_id AND v.learning_objective_id=:id) OR EXISTS(SELECT 1 FROM knowledge_fact_version v JOIN knowledge_fact f ON f.id=v.knowledge_fact_id WHERE v.id=i.content_version_id AND f.learning_objective_id=:id)",id),"release items"));reject(b,"ARCHIVE");remove("learning_objective",id,reason);}
    @Transactional public void deleteSource(UUID id,String reason){requireAdmin();var row=lock("source_reference",id);if(!"UNREVIEWED".equals(row.get("review_status"))||!"ACTIVE".equals(row.get("status")))historical("Unused, unreviewed sources may be deleted; retire this source instead");var b=blocks(block("KNOWLEDGE_FACT",count("SELECT count(*) FROM knowledge_fact_source WHERE source_reference_id=:id",id),"knowledge facts"),block("SOURCE_HISTORY",count("SELECT count(*) FROM source_reference WHERE replacement_source_id=:id",id),"replacement references"));reject(b,"RETIRE");remove("source_reference",id,reason);}
    @Transactional public void deleteFact(UUID id,String reason){var row=lock("knowledge_fact",id);draftUnreviewed(row);UUID version=(UUID)row.get("current_version_id");ownerOrAdmin(author("knowledge_fact_version",version));var b=blocks(block("REVIEW_HISTORY",count("SELECT count(*) FROM review_item WHERE content_type='KNOWLEDGE_FACT' AND content_id=:id",id),"review records"),block("QUESTION",count("SELECT count(*) FROM question_knowledge_fact q WHERE q.knowledge_fact_version_id IN(SELECT id FROM knowledge_fact_version WHERE knowledge_fact_id=:id)",id),"questions"),block("RELEASE",count("SELECT count(*) FROM content_release_item WHERE content_type='KNOWLEDGE_FACT' AND content_id=:id",id),"release items"),block("HISTORICAL_VERSION",Math.max(0,count("SELECT count(*) FROM knowledge_fact_version WHERE knowledge_fact_id=:id",id)-1),"historical versions"));reject(b,"RETIRE");setAudit(reason);jdbc.sql("UPDATE knowledge_fact SET current_version_id=NULL WHERE id=:id").param("id",id).update();jdbc.sql("DELETE FROM knowledge_fact_source WHERE knowledge_fact_version_id=:id").param("id",version).update();jdbc.sql("DELETE FROM knowledge_fact_version WHERE id=:id").param("id",version).update();delete("knowledge_fact",id);}
    @Transactional public void deleteQuestion(UUID id,String reason){var row=lock("question",id);draftUnreviewed(row);UUID version=(UUID)row.get("current_version_id");ownerOrAdmin(author("question_version",version));var b=blocks(block("REVIEW_HISTORY",count("SELECT count(*) FROM review_item WHERE content_type='QUESTION' AND content_id=:id",id),"review records"),block("RELEASE",count("SELECT count(*) FROM content_release_item WHERE content_type='QUESTION' AND content_id=:id",id),"release items"),block("HISTORICAL_VERSION",Math.max(0,count("SELECT count(*) FROM question_version WHERE question_id=:id",id)-1),"historical versions"));reject(b,"RETIRE");setAudit(reason);jdbc.sql("UPDATE question SET current_version_id=NULL WHERE id=:id").param("id",id).update();jdbc.sql("DELETE FROM question_version WHERE id=:id").param("id",version).update();delete("question",id);}
    @Transactional public void deleteRelease(UUID id,String reason){var row=lock("content_release",id);if(!"DRAFT".equals(row.get("status")))historical("Only a never-published draft release can be deleted");ownerOrPublisherOrAdmin((String)row.get("created_by"));var b=blocks(block("PUBLISHED_SNAPSHOT",count("SELECT count(*) FROM published_release_snapshot WHERE release_id=:id",id),"published snapshots"),block("DELIVERY_HISTORY",count("SELECT count(*) FROM release_delivery_attempt WHERE release_id=:id",id),"delivery attempts"),block("ACTIVATION_HISTORY",count("SELECT count(*) FROM release_activation_history WHERE release_id=:id OR previous_active_release_id=:id",id),"activation records"),block("RELEASE_HISTORY",count("SELECT count(*) FROM content_release WHERE previous_release_id=:id",id),"successor releases"));reject(b,"NONE");setAudit(reason);jdbc.sql("DELETE FROM content_release_item WHERE release_id=:id").param("id",id).update();jdbc.sql("DELETE FROM release_validation_run WHERE release_id=:id").param("id",id).update();delete("content_release",id);}

    private Map<String,Object> lock(String table,UUID id){var rows=jdbc.sql("SELECT * FROM "+table+" WHERE id=:id FOR UPDATE").param("id",id).query().listOfRows();if(rows.isEmpty())throw DomainException.notFound(entity(table));return rows.getFirst();}
    private long count(String sql,UUID id){return jdbc.sql(sql).param("id",id).query(Long.class).single();}
    private Block block(String type,long count,String label){return new Block(type,count,count==1?"This entity has 1 "+label+".":"This entity has "+count+" "+label+".");}
    private List<Block> blocks(Block... values){return java.util.Arrays.stream(values).filter(v->v.count()>0).toList();}
    private void reject(List<Block>b,String action){if(b.isEmpty())return;throw new DomainException(HttpStatus.CONFLICT,"ENTITY_HAS_DEPENDENCIES","Deletion is blocked by dependent or historical content",b.stream().map(v->(Object)Map.of("type",v.type(),"count",v.count(),"message",v.message(),"recommendedAction",action)).toList());}
    private void draft(Map<String,Object>r){if(!"DRAFT".equals(r.get("status")))throw new DomainException(HttpStatus.CONFLICT,"DELETE_REQUIRES_DRAFT_STATUS","Only draft content can be deleted");}
    private void draftUnreviewed(Map<String,Object>r){if(!"UNREVIEWED".equals(r.get("review_status")))historical("Submitted, reviewed, or approved content must be retired");draft(r);}
    private void historical(String message){throw new DomainException(HttpStatus.CONFLICT,"ENTITY_ALREADY_HISTORICAL",message,List.of(Map.of("recommendedAction","RETIRE")));}
    private void remove(String table,UUID id,String reason){setAudit(reason);delete(table,id);}
    private void delete(String table,UUID id){try{jdbc.sql("DELETE FROM "+table+" WHERE id=:id").param("id",id).update();}catch(org.springframework.dao.DataIntegrityViolationException e){throw new DomainException(HttpStatus.CONFLICT,"ENTITY_HAS_DEPENDENCIES","Deletion was blocked because a dependency was added concurrently",List.of(Map.of("type","CONCURRENT_DEPENDENCY","count",1,"message","Refresh and inspect dependencies before retrying")));}}
    private void setAudit(String reason){var a=authentication();String roles=a.getAuthorities().stream().map(Object::toString).collect(java.util.stream.Collectors.joining(","));jdbc.sql("SELECT set_config('app.actor_id',:actor,true),set_config('app.actor_name',:actor,true),set_config('app.actor_roles',:roles,true),set_config('app.delete_reason',:reason,true)").param("actor",a.getName()).param("roles",roles).param("reason",reason==null?"":reason).query((rs,n)->1).single();}
    private String author(String table,UUID version){return jdbc.sql("SELECT author_id FROM "+table+" WHERE id=:id").param("id",version).query(String.class).single();}
    private void requireAdmin(){if(!has("ROLE_ADMIN"))throw new DomainException(HttpStatus.FORBIDDEN,"FORBIDDEN","Only an administrator may delete structure or sources");}
    private void ownerOrAdmin(String owner){if(!has("ROLE_ADMIN")&&!authentication().getName().equals(owner))throw new DomainException(HttpStatus.FORBIDDEN,"FORBIDDEN","Content authors may delete only their own drafts");}
    private void ownerOrPublisherOrAdmin(String owner){if(!has("ROLE_ADMIN")&&!has("ROLE_CONTENT_PUBLISHER"))throw new DomainException(HttpStatus.FORBIDDEN,"FORBIDDEN","A publisher role is required");if(!has("ROLE_ADMIN")&&!authentication().getName().equals(owner))throw new DomainException(HttpStatus.FORBIDDEN,"FORBIDDEN","Publishers may delete only their own draft releases");}
    private boolean has(String role){return authentication().getAuthorities().stream().anyMatch(a->a.getAuthority().equals(role));}
    private org.springframework.security.core.Authentication authentication(){return SecurityContextHolder.getContext().getAuthentication();}
    private String entity(String table){return switch(table){case"exam_version"->"Exam version";case"source_reference"->"Source";case"learning_objective"->"Learning objective";case"knowledge_fact"->"Knowledge fact";case"content_release"->"Release";default->Character.toUpperCase(table.charAt(0))+table.substring(1);};}
    private record Block(String type,long count,String message){}
}
