package se.medbo.examplatform.content.ai;

import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.JsonNode;import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.URI;import java.net.http.HttpClient;import java.net.http.HttpRequest;import java.net.http.HttpResponse;import java.sql.Types;import java.time.OffsetDateTime;import java.time.ZoneOffset;import java.util.List;import java.util.Map;import java.util.UUID;
import org.springframework.beans.factory.annotation.Value;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import se.medbo.examplatform.content.shared.DomainException;

@Service
public class AiEditorialService {
 private final JdbcClient jdbc;private final ObjectMapper mapper;private final HttpClient http=HttpClient.newBuilder().connectTimeout(java.time.Duration.ofSeconds(5)).build();private final String baseUrl;private final String apiKey;
 public record Create(UUID sourceId,UUID learningObjectiveId,int requestedCount,String language,String editorialInstruction,String idempotencyKey){}public record Edit(String text,long version){}public record Decision(String reason,long version){}
 public AiEditorialService(JdbcClient jdbc,ObjectMapper mapper,@Value("${content.ai-service.base-url:http://localhost:8083}")String baseUrl,@Value("${content.ai-service.internal-api-key:}")String apiKey){this.jdbc=jdbc;this.mapper=mapper;this.baseUrl=baseUrl;this.apiKey=apiKey;}
 public Map<String,Object> create(Create in){requireAuthor();if(apiKey.isBlank())throw unavailable("AI_PROVIDER_NOT_CONFIGURED","AI Service authentication is not configured");var source=one("SELECT id,title,content_text AS \"contentText\",content_checksum AS \"contentChecksum\",status FROM source_reference WHERE id=:id",in.sourceId(),"Source");if("RETIRED".equals(source.get("status")))throw validation("Retired sources cannot be used for generation");if(source.get("contentText")==null)throw new DomainException(HttpStatus.UNPROCESSABLE_ENTITY,"AI_SOURCE_CONTENT_REQUIRED","Source content must be added before generation");var objective=one("SELECT lo.id,lo.title,lo.status FROM learning_objective lo WHERE lo.id=:id",in.learningObjectiveId(),"Learning objective");if("ARCHIVED".equals(objective.get("status")))throw validation("Archived learning objectives cannot receive generated proposals");var payload=new java.util.LinkedHashMap<String,Object>();payload.put("sourceId",in.sourceId());payload.put("sourceTitle",source.get("title"));payload.put("sourceContent",source.get("contentText"));payload.put("sourceContentChecksum",source.get("contentChecksum"));payload.put("learningObjectiveId",in.learningObjectiveId());payload.put("learningObjectiveTitle",objective.get("title"));payload.put("requestedBy",actor());payload.put("requestedCount",in.requestedCount());payload.put("language",in.language());payload.put("editorialInstruction",in.editorialInstruction()==null?"":in.editorialInstruction());payload.put("idempotencyKey",in.idempotencyKey());return post("/internal/v1/knowledge-fact-generation/jobs",payload);}
 public Map<String,Object> job(UUID id){var result=get("/internal/v1/knowledge-fact-generation/jobs/"+id);authorizeJob(result);return result;}
 public List<Map<String,Object>> proposals(UUID id){authorizeJob(job(id));return getList("/internal/v1/knowledge-fact-generation/jobs/"+id+"/proposals");}
 public Map<String,Object> cancel(UUID id){var job=job(id);if(!isAdmin()&&!actor().equals(job.get("requestedBy")))throw forbidden();return post("/internal/v1/knowledge-fact-generation/jobs/"+id+"/cancel",Map.of());}
 public Map<String,Object> edit(UUID id,Edit in){requireAuthor();authorizeProposal(id);return patch("/internal/v1/knowledge-fact-generation/proposals/"+id,Map.of("text",in.text(),"version",in.version()));}
 public Map<String,Object> reject(UUID id,Decision in){requireAuthor();authorizeProposal(id);return post("/internal/v1/knowledge-fact-generation/proposals/"+id+"/reject",Map.of("reason",in.reason()==null?"":in.reason(),"version",in.version()));}
 @Transactional public Map<String,Object> accept(UUID proposalId,long version){requireAuthor();var proposal=authorizeProposal(proposalId);if("ACCEPTED".equals(proposal.get("status"))){UUID existing=jdbc.sql("SELECT v.knowledge_fact_id FROM knowledge_fact_ai_provenance p JOIN knowledge_fact_version v ON v.id=p.knowledge_fact_version_id WHERE p.proposal_id=:id").param("id",proposalId).query(UUID.class).optional().orElse(null);if(existing!=null)return fact(existing);throw conflict("AI_PROPOSAL_ALREADY_ACCEPTED","The proposal was already accepted");}if(!List.of("PROPOSED","EDITED").contains(proposal.get("status")))throw conflict("AI_PROPOSAL_ALREADY_PROCESSED","The proposal was already processed");UUID objective=uuid(proposal.get("learning_objective_id"));UUID source=uuid(proposal.get("source_id"));String text=(String)proposal.get("edited_text");String normalized=text.trim().replaceAll("\\s+"," ").toLowerCase();var duplicate=jdbc.sql("SELECT id FROM knowledge_fact WHERE learning_objective_id=:objective AND lower(regexp_replace(trim(canonical_statement),'\\s+',' ','g'))=:text AND status<>'RETIRED'").param("objective",objective).param("text",normalized).query(UUID.class).list();if(!duplicate.isEmpty())throw conflict("AI_PROPOSAL_DUPLICATE","An equivalent Knowledge Fact already exists");
   UUID factId=UUID.randomUUID(),factVersionId=UUID.randomUUID();var now=OffsetDateTime.now(ZoneOffset.UTC);String actor=actor();jdbc.sql("INSERT INTO knowledge_fact(id,learning_objective_id,canonical_statement,review_status,status,created_at,updated_at) VALUES(:id,:objective,:text,'UNREVIEWED','DRAFT',:now,:now)").param("id",factId).param("objective",objective).param("text",text.trim()).param("now",now).update();jdbc.sql("INSERT INTO knowledge_fact_version(id,knowledge_fact_id,version_number,canonical_statement,review_status,author_id,created_at,updated_at) VALUES(:id,:fact,1,:text,'UNREVIEWED',:actor,:now,:now)").param("id",factVersionId).param("fact",factId).param("text",text.trim()).param("actor",actor).param("now",now).update();jdbc.sql("UPDATE knowledge_fact SET current_version_id=:version WHERE id=:fact").param("version",factVersionId).param("fact",factId).update();jdbc.sql("INSERT INTO knowledge_fact_source VALUES(:version,:source)").param("version",factVersionId).param("source",source).update();
   jdbc.sql("INSERT INTO knowledge_fact_ai_provenance(knowledge_fact_version_id,generation_job_id,proposal_id,provider,model,prompt_version,generated_at,source_reference_id,source_content_checksum,learning_objective_id,requesting_user_id,original_proposed_text,final_accepted_text,accepting_user_id,accepted_at,confidence,source_evidence,provider_request_id,input_tokens,output_tokens) VALUES(:version,:job,:proposal,:provider,:model,:prompt,:generated,:source,:checksum,:objective,:requester,:original,:final,:actor,:now,:confidence,CAST(:evidence AS jsonb),:requestId,:input,:output)").param("version",factVersionId).param("job",uuid(proposal.get("generation_job_id"))).param("proposal",proposalId).param("provider",proposal.get("provider")).param("model",proposal.get("model")).param("prompt",proposal.get("prompt_version")).param("generated",OffsetDateTime.parse(String.valueOf(proposal.get("generated_at")))).param("source",source).param("checksum",proposal.get("source_content_checksum")).param("objective",objective).param("requester",proposal.get("requested_by")).param("original",proposal.get("proposed_text")).param("final",text.trim()).param("actor",actor).param("now",now).param("confidence",proposal.get("confidence"),Types.VARCHAR).param("evidence",String.valueOf(proposal.get("source_evidence"))).param("requestId",proposal.get("provider_request_id"),Types.VARCHAR).param("input",proposal.get("input_tokens"),Types.INTEGER).param("output",proposal.get("output_tokens"),Types.INTEGER).update();
   post("/internal/v1/knowledge-fact-generation/proposals/"+proposalId+"/accepted",Map.of("knowledgeFactId",factId,"acceptedBy",actor,"version",version));return fact(factId);
 }
 public Map<String,Object> provenance(UUID factId){var rows=jdbc.sql("SELECT p.knowledge_fact_version_id AS \"knowledgeFactVersionId\",p.generation_job_id AS \"generationJobId\",p.proposal_id AS \"proposalId\",p.provider,p.model,p.prompt_version AS \"promptVersion\",p.generated_at AS \"generatedAt\",p.source_reference_id AS \"sourceId\",s.title AS \"sourceTitle\",p.source_content_checksum AS \"sourceContentChecksum\",p.learning_objective_id AS \"learningObjectiveId\",p.requesting_user_id AS \"requestingUserId\",p.original_proposed_text AS \"originalProposedText\",p.final_accepted_text AS \"finalAcceptedText\",p.accepting_user_id AS \"acceptingUserId\",p.accepted_at AS \"acceptedAt\",p.confidence,p.source_evidence::text AS \"sourceEvidence\",p.provider_request_id AS \"providerRequestId\",p.input_tokens AS \"inputTokens\",p.output_tokens AS \"outputTokens\" FROM knowledge_fact_ai_provenance p JOIN knowledge_fact_version v ON v.id=p.knowledge_fact_version_id JOIN source_reference s ON s.id=p.source_reference_id WHERE v.knowledge_fact_id=:id ORDER BY v.version_number DESC LIMIT 1").param("id",factId).query().listOfRows();if(rows.isEmpty())throw new DomainException(HttpStatus.NOT_FOUND,"AI_PROVENANCE_NOT_FOUND","This Knowledge Fact has no AI provenance");var result=rows.getFirst();try{result.put("sourceEvidence",mapper.readValue((String)result.get("sourceEvidence"),List.class));}catch(Exception e){throw new IllegalStateException("Stored provenance evidence is invalid",e);}return result;}
 private Map<String,Object> authorizeProposal(UUID id){var proposal=get("/internal/v1/knowledge-fact-generation/proposals/"+id);var job=get("/internal/v1/knowledge-fact-generation/jobs/"+proposal.get("generation_job_id"));authorizeJob(job);return proposal;}private void authorizeJob(Map<String,Object> job){if(!isAdmin()&&!actor().equals(job.get("requestedBy")))throw forbidden();}
 private Map<String,Object> fact(UUID id){var row=one("SELECT id,learning_objective_id AS \"learningObjectiveId\",current_version_id AS \"currentVersionId\",canonical_statement AS \"canonicalStatement\",review_status AS \"reviewStatus\",status,created_at AS \"createdAt\",updated_at AS \"updatedAt\",version FROM knowledge_fact WHERE id=:id",id,"Knowledge fact");row.put("generatedByAi",true);return row;}
 private Map<String,Object> one(String sql,UUID id,String label){var rows=jdbc.sql(sql).param("id",id).query().listOfRows();if(rows.isEmpty())throw DomainException.notFound(label);return rows.getFirst();}private UUID uuid(Object value){return value instanceof UUID u?u:UUID.fromString(String.valueOf(value));}
 private Map<String,Object> get(String path){return send("GET",path,null,new TypeReference<>(){});}private List<Map<String,Object>> getList(String path){return send("GET",path,null,new TypeReference<>(){});}private Map<String,Object> post(String path,Object body){return send("POST",path,body,new TypeReference<>(){});}private Map<String,Object> patch(String path,Object body){return send("PATCH",path,body,new TypeReference<>(){});}
 private <T>T send(String method,String path,Object body,TypeReference<T> type){try{var builder=HttpRequest.newBuilder(URI.create(baseUrl+path)).timeout(java.time.Duration.ofSeconds(10)).header("X-Internal-Api-Key",apiKey).header("Content-Type","application/json");String json=body==null?"":mapper.writeValueAsString(body);builder.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json));var response=http.send(builder.build(),HttpResponse.BodyHandlers.ofString());if(response.statusCode()>=200&&response.statusCode()<300)return mapper.readValue(response.body(),type);JsonNode error=mapper.readTree(response.body());throw new DomainException(HttpStatus.valueOf(response.statusCode()),error.path("code").asText("AI_PROVIDER_UNAVAILABLE"),error.path("message").asText("AI Service rejected the request"));}catch(DomainException e){throw e;}catch(Exception e){throw unavailable("AI_PROVIDER_UNAVAILABLE","AI Service could not be reached");}}
 private void requireAuthor(){if(!has("ROLE_CONTENT_AUTHOR")&&!has("ROLE_ADMIN"))throw forbidden();}private boolean isAdmin(){return has("ROLE_ADMIN");}private boolean has(String role){return SecurityContextHolder.getContext().getAuthentication().getAuthorities().stream().anyMatch(a->role.equals(a.getAuthority()));}private String actor(){return SecurityContextHolder.getContext().getAuthentication().getName();}private DomainException forbidden(){return new DomainException(HttpStatus.FORBIDDEN,"FORBIDDEN","Content author permission is required");}private DomainException unavailable(String c,String m){return new DomainException(HttpStatus.SERVICE_UNAVAILABLE,c,m);}private DomainException validation(String m){return new DomainException(HttpStatus.UNPROCESSABLE_ENTITY,"AI_INVALID_GENERATION_REQUEST",m);}private DomainException conflict(String c,String m){return new DomainException(HttpStatus.CONFLICT,c,m);}
}
