package se.medbo.examplatform.content.ai;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import se.medbo.examplatform.content.shared.DomainException;

@Service
final class AiQuestionBatchService {
  record Scope(String type,UUID id,List<UUID> knowledgeFactIds){}
  record Request(Scope scope,String language,int questionsPerKnowledgeFact,List<String> questionTypes,
                 Map<String,Integer> difficultyDistribution,Map<String,Integer> bloomDistribution,String idempotencyKey){}
  private static final int MAX=200;
  private static final List<String> TYPES=List.of("SINGLE_CHOICE","TRUE_FALSE","MULTIPLE_CHOICE");
  private static final List<String> DIFFICULTIES=List.of("EASY","MEDIUM","HARD");
  private static final List<String> BLOOMS=List.of("REMEMBER","UNDERSTAND","APPLY","ANALYZE");
  private final JdbcClient jdbc;private final AiQuestionGenerationService generation;
  AiQuestionBatchService(JdbcClient jdbc,AiQuestionGenerationService generation){this.jdbc=jdbc;this.generation=generation;}

  Map<String,Object> preview(Request request){generation.requireBatchAuthor();return plan(request,false);}
  Map<String,Object> create(Request request){generation.requireBatchAuthor();if(request.idempotencyKey()==null||request.idempotencyKey().isBlank())throw validation("VALIDATION_ERROR","idempotencyKey is required");var plan=plan(request,true);var payload=new LinkedHashMap<String,Object>();payload.put("scopeType",request.scope().type());payload.put("scopeId",request.scope().id());payload.put("scopeLabel",plan.get("scopeLabel"));payload.put("language",request.language());payload.put("configuration",Map.of("questionsPerKnowledgeFact",request.questionsPerKnowledgeFact(),"questionTypes",request.questionTypes(),"difficultyDistribution",request.difficultyDistribution(),"bloomDistribution",request.bloomDistribution(),"resolvedDistributions",plan.get("resolvedDistributions")));payload.put("requestedBy",generation.currentActor());payload.put("idempotencyKey",request.idempotencyKey());payload.put("items",plan.get("items"));return generation.internalPost("/internal/v1/question-generation-batches",payload);}
  Map<String,Object> list(int page,int size,String status,String scopeType,String createdBy){requireViewer();String actor=generation.isBatchAdmin()||isReviewer()?createdBy:generation.currentActor();return generation.internalGet("/internal/v1/question-generation-batches?page="+page+"&size="+size+query("status",status)+query("scopeType",scopeType)+query("createdBy",actor));}
  Map<String,Object> get(UUID id){var batch=generation.internalGet("/internal/v1/question-generation-batches/"+id);authorize(batch);return batch;}
  Map<String,Object> items(UUID id,int page,int size,String status,UUID fact){get(id);return generation.internalGet("/internal/v1/question-generation-batches/"+id+"/items?page="+page+"&size="+size+query("status",status)+(fact==null?"":"&knowledgeFactId="+fact));}
  Map<String,Object> proposals(UUID id,int page,int size,String status){get(id);return generation.internalGet("/internal/v1/question-generation-batches/"+id+"/proposals?page="+page+"&size="+size+query("status",status));}
  Map<String,Object> cancel(UUID id){var batch=get(id);if(!generation.isBatchAdmin()&&!generation.currentActor().equals(batch.get("createdBy")))throw forbidden();return generation.internalPost("/internal/v1/question-generation-batches/"+id+"/cancel",Map.of("actor",generation.currentActor()));}
  Map<String,Object> retry(UUID id,List<UUID> itemIds){var batch=get(id);if(!generation.isBatchAdmin()&&!generation.currentActor().equals(batch.get("createdBy")))throw forbidden();return generation.internalPost("/internal/v1/question-generation-batches/"+id+"/retry-failed",Map.of("itemIds",itemIds==null?List.of():itemIds,"actor",generation.currentActor()));}
  Map<String,Object> assign(List<UUID> ids,String reviewer,OffsetDateTime deadline){requireViewer();var body=new LinkedHashMap<String,Object>();body.put("proposalIds",ids);body.put("reviewerId",reviewer);body.put("actor",generation.currentActor());body.put("reviewDeadline",deadline);return generation.internalPost("/internal/v1/question-generation-batches/proposals/assign",body);}
  Map<String,Object> unassign(List<UUID> ids){requireViewer();return generation.internalPost("/internal/v1/question-generation-batches/proposals/unassign",Map.of("proposalIds",ids,"actor",generation.currentActor()));}
  Map<String,Object> bulkReject(List<UUID> ids,String reason,String comment,Map<UUID,Long> versions){requireViewer();return bulk(ids,id->generation.reject(id,reason,comment,version(versions,id)),"AI_BULK_REJECTION_REQUESTED");}
  Map<String,Object> bulkRegenerate(List<UUID> ids,String feedback,Map<UUID,Long> versions,String key){requireViewer();return bulk(ids,id->generation.regenerate(id,feedback,version(versions,id),key+":"+id),"AI_BULK_REGENERATION_REQUESTED");}
  Map<String,Object> bulkAccept(List<UUID> ids,Map<UUID,Long> versions){generation.requireBatchAuthor();return bulk(ids,id->generation.accept(id,version(versions,id)),"AI_BULK_ACCEPTANCE_REQUESTED");}
  Map<String,Object> export(UUID id,String format){var batch=get(id);var proposals=proposals(id,0,MAX,null);return Map.of("format",format==null?"JSON":format.toUpperCase(),"batch",batch,"proposals",proposals.get("items"));}

  @SuppressWarnings("unchecked")
  private Map<String,Object> plan(Request request,boolean includeItems){
    validate(request);String label=scopeLabel(request.scope());var resolved=resolve(request.scope());var eligible=new ArrayList<UUID>();var exclusions=new LinkedHashMap<String,Integer>();var snapshots=new LinkedHashMap<UUID,Map<String,Object>>();
    for(UUID id:resolved)try{var snapshot=generation.generationSnapshot(id,request.language());eligible.add(id);snapshots.put(id,snapshot);}catch(DomainException e){exclusions.merge(e.code(),1,Integer::sum);}
    if(eligible.isEmpty())throw validation("BATCH_SCOPE_EMPTY","The selected scope contains no eligible Knowledge Facts");
    int total=eligible.size()*request.questionsPerKnowledgeFact();if(total>MAX)throw validation("BATCH_LIMIT_EXCEEDED","This configuration would generate "+total+" proposals. The maximum allowed is "+MAX+".");
    var difficulty=assign(request.difficultyDistribution(),DIFFICULTIES,total);var bloom=assign(request.bloomDistribution(),BLOOMS,total);var items=new ArrayList<Map<String,Object>>();
    for(int index=0;index<total;index++){UUID fact=eligible.get(index/request.questionsPerKnowledgeFact());var item=new LinkedHashMap<String,Object>();item.putAll(snapshots.get(fact));item.put("questionType",request.questionTypes().get(index%request.questionTypes().size()));item.put("targetDifficulty",difficulty.get(index));item.put("targetBloomLevel",bloom.get(index));items.add(item);}
    var result=new LinkedHashMap<String,Object>();result.put("scopeLabel",label);result.put("resolvedKnowledgeFactCount",eligible.size());result.put("estimatedProposalCount",total);result.put("excludedKnowledgeFactCount",resolved.size()-eligible.size());result.put("exclusionReasons",exclusions);result.put("questionTypeDistribution",counts(items,"questionType"));result.put("difficultyDistribution",counts(items,"targetDifficulty"));result.put("bloomDistribution",counts(items,"targetBloomLevel"));result.put("resolvedDistributions",Map.of("questionTypes",counts(items,"questionType"),"difficulty",counts(items,"targetDifficulty"),"bloom",counts(items,"targetBloomLevel")));result.put("configuredMaximum",MAX);result.put("withinLimit",true);result.put("estimatedProviderCalls",total);result.put("estimatedTokenUsage",Map.of("calculable",false,"reason","Provider token usage depends on source context and generated output"));result.put("warnings",exclusions.isEmpty()?List.of():List.of("Some Knowledge Facts were excluded because they are not eligible."));if(includeItems)result.put("items",items);return result;
  }
  private List<UUID> resolve(Scope scope){if(scope==null||scope.type()==null)throw validation("VALIDATION_ERROR","scope is required");List<UUID> ids=switch(scope.type()){case "KNOWLEDGE_FACT"->List.of(required(scope.id()));case "MULTIPLE_KNOWLEDGE_FACTS"->scope.knowledgeFactIds()==null?List.of():scope.knowledgeFactIds();case "TOPIC"->jdbc.sql("SELECT f.id FROM knowledge_fact f JOIN learning_objective lo ON lo.id=f.learning_objective_id WHERE lo.topic_id=:id ORDER BY f.id").param("id",required(scope.id())).query(UUID.class).list();case "SUBJECT"->jdbc.sql("SELECT f.id FROM knowledge_fact f JOIN learning_objective lo ON lo.id=f.learning_objective_id JOIN topic t ON t.id=lo.topic_id WHERE t.subject_id=:id ORDER BY f.id").param("id",required(scope.id())).query(UUID.class).list();case "EXAM_VERSION"->jdbc.sql("SELECT f.id FROM knowledge_fact f JOIN learning_objective lo ON lo.id=f.learning_objective_id JOIN topic t ON t.id=lo.topic_id JOIN subject s ON s.id=t.subject_id WHERE s.exam_version_id=:id ORDER BY f.id").param("id",required(scope.id())).query(UUID.class).list();default->throw validation("BATCH_SCOPE_INVALID","Unsupported generation scope");};return new ArrayList<>(new LinkedHashSet<>(ids));}
  private String scopeLabel(Scope scope){if("MULTIPLE_KNOWLEDGE_FACTS".equals(scope.type()))return "Selected Knowledge Facts";String table=switch(scope.type()){case "KNOWLEDGE_FACT"->"knowledge_fact";case "TOPIC"->"topic";case "SUBJECT"->"subject";case "EXAM_VERSION"->"exam_version";default->null;};if(table==null)return scope.type();var exists=jdbc.sql("SELECT EXISTS(SELECT 1 FROM "+table+" WHERE id=:id)").param("id",scope.id()).query(Boolean.class).single();if(!exists)throw validation("BATCH_SCOPE_NOT_FOUND","The selected generation scope was not found");return scope.type().replace('_',' ')+" · "+scope.id();}
  private void validate(Request request){if(request==null||request.scope()==null)throw validation("VALIDATION_ERROR","scope is required");if(!List.of("sv","en").contains(request.language()))throw validation("BATCH_UNSUPPORTED_LANGUAGE","The selected language is unsupported");if(request.questionsPerKnowledgeFact()<1||request.questionsPerKnowledgeFact()>3)throw validation("BATCH_INVALID_CONFIGURATION","Request one to three questions per Knowledge Fact");if(request.questionTypes()==null||request.questionTypes().isEmpty()||request.questionTypes().stream().anyMatch(t->!TYPES.contains(t)))throw validation("BATCH_INVALID_DISTRIBUTION","Select at least one supported question type");distribution(request.difficultyDistribution(),DIFFICULTIES);distribution(request.bloomDistribution(),BLOOMS);}
  private void distribution(Map<String,Integer> values,List<String> supported){if(values==null||values.isEmpty())throw validation("BATCH_INVALID_DISTRIBUTION","A distribution is required");if(values.keySet().stream().anyMatch(k->!supported.contains(k))||values.values().stream().anyMatch(v->v==null||v<0)||values.values().stream().mapToInt(Integer::intValue).sum()!=100)throw validation("BATCH_INVALID_DISTRIBUTION","Distribution values must be supported, non-negative, and total 100");}
  private List<String> assign(Map<String,Integer> percentages,List<String> order,int total){record Share(String value,int base,double fraction){}var shares=order.stream().filter(percentages::containsKey).map(v->{double exact=percentages.get(v)*total/100d;return new Share(v,(int)Math.floor(exact),exact-Math.floor(exact));}).toList();var counts=new LinkedHashMap<String,Integer>();shares.forEach(s->counts.put(s.value(),s.base()));int remaining=total-counts.values().stream().mapToInt(Integer::intValue).sum();shares.stream().sorted(Comparator.comparingDouble(Share::fraction).reversed().thenComparingInt(s->order.indexOf(s.value()))).limit(remaining).forEach(s->counts.compute(s.value(),(k,v)->v+1));var result=new ArrayList<String>();while(result.size()<total)for(String value:order)if(counts.getOrDefault(value,0)>0){result.add(value);counts.compute(value,(k,v)->v-1);}return result;}
  private Map<String,Integer> counts(List<Map<String,Object>> items,String field){var result=new LinkedHashMap<String,Integer>();items.forEach(item->result.merge(String.valueOf(item.get(field)),1,Integer::sum));return result;}
  private interface Action{Map<String,Object> run(UUID id);}
  private Map<String,Object> bulk(List<UUID> ids,Action action,String event){if(ids==null||ids.isEmpty())throw validation("BULK_ACTION_EMPTY_SELECTION","Select at least one proposal");var results=new ArrayList<Map<String,Object>>();for(UUID id:ids)try{var value=action.run(id);results.add(Map.of("proposalId",id,"outcome","SUCCEEDED","result",value));}catch(DomainException e){results.add(Map.of("proposalId",id,"outcome","FAILED","errorCode",e.code(),"message",e.getMessage()));}catch(RuntimeException e){results.add(Map.of("proposalId",id,"outcome","FAILED","errorCode","BULK_ITEM_FAILED","message","The proposal action could not be completed"));}long success=results.stream().filter(r->"SUCCEEDED".equals(r.get("outcome"))).count();return Map.of("action",event,"requested",ids.size(),"succeeded",success,"failed",ids.size()-success,"results",results);}
  private long version(Map<UUID,Long> versions,UUID id){if(versions==null||versions.get(id)==null)throw validation("OPTIMISTIC_LOCK_CONFLICT","A proposal version is required");return versions.get(id);}
  private void authorize(Map<String,Object> batch){requireViewer();if(!generation.isBatchAdmin()&&!isReviewer()&&!generation.currentActor().equals(batch.get("createdBy")))throw forbidden();}
  private void requireViewer(){if(!generation.canReviewBatches())throw forbidden();}
  private boolean isReviewer(){return generation.isBatchReviewer();}
  private String query(String name,String value){return value==null||value.isBlank()?"":"&"+name+"="+java.net.URLEncoder.encode(value,java.nio.charset.StandardCharsets.UTF_8);}
  private UUID required(UUID id){if(id==null)throw validation("VALIDATION_ERROR","scope id is required");return id;}
  private DomainException validation(String code,String message){return new DomainException(HttpStatus.UNPROCESSABLE_ENTITY,code,message);}
  private DomainException forbidden(){return new DomainException(HttpStatus.FORBIDDEN,"FORBIDDEN","AI batch permission is required");}
}
