package se.medbo.examplatform.content.ai;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import se.medbo.examplatform.content.knowledge.KnowledgeFactTextQualityValidator;
import se.medbo.examplatform.content.question.QuestionService;
import se.medbo.examplatform.content.shared.DomainException;

@Service
public class AiQuestionGenerationService {
  private final JdbcClient jdbc;private final ObjectMapper mapper;private final KnowledgeFactTextQualityValidator quality;private final QuestionService questions;private final HttpClient http=HttpClient.newBuilder().connectTimeout(java.time.Duration.ofSeconds(5)).build();private final String baseUrl,apiKey,language;private final int maxSourceCharacters;
  AiQuestionGenerationService(JdbcClient jdbc,ObjectMapper mapper,KnowledgeFactTextQualityValidator quality,QuestionService questions,@Value("${content.ai-service.base-url:http://localhost:8083}")String baseUrl,@Value("${content.ai-service.internal-api-key:}")String apiKey,@Value("${content.default-language:sv}")String language,@Value("${content.ai-service.max-source-context-characters:12000}")int maxSourceCharacters){this.jdbc=jdbc;this.mapper=mapper;this.quality=quality;this.questions=questions;this.baseUrl=baseUrl;this.apiKey=apiKey;this.language=language;this.maxSourceCharacters=maxSourceCharacters;}
  public Map<String,Object> create(UUID factId,int proposalCount,String questionType,String idempotencyKey){requireAuthor();if(proposalCount<1||proposalCount>3)throw validation("AI_QUESTION_GENERATION_INVALID_PROPOSAL_COUNT","Request one to three proposals");if(questionType!=null&&!List.of("SINGLE_CHOICE","TRUE_FALSE","MULTIPLE_CHOICE").contains(questionType))throw validation("AI_QUESTION_GENERATION_QUESTION_TYPE_INVALID","Unsupported question type");if(idempotencyKey==null||idempotencyKey.isBlank())throw validation("VALIDATION_ERROR","idempotencyKey is required");var fact=factSnapshot(factId);eligible(fact);var sources=sourceSnapshots(uuid(fact.get("factVersionId")));var target=Map.of("knowledgeFactId",factId,"knowledgeFactVersionId",fact.get("factVersionId"),"version",fact.get("versionNumber"),"text",fact.get("canonicalStatement"),"checksum",checksum(String.valueOf(fact.get("canonicalStatement"))),"language",language);var context=new LinkedHashMap<String,Object>();context.put("learningObjectiveId",fact.get("learningObjectiveId"));context.put("learningObjectiveTitle",fact.get("learningObjectiveTitle"));context.put("learningObjectiveDescription",fact.get("learningObjectiveDescription"));context.put("topicId",fact.get("topicId"));context.put("topicTitle",fact.get("topicTitle"));context.put("subjectId",fact.get("subjectId"));context.put("subjectTitle",fact.get("subjectTitle"));context.put("examId",fact.get("examId"));context.put("examVersionId",fact.get("examVersionId"));context.put("sources",sources);var payload=new LinkedHashMap<String,Object>();payload.put("target",target);payload.put("context",context);payload.put("proposalCount",proposalCount);payload.put("questionType",questionType);payload.put("requestedBy",actor());payload.put("idempotencyKey",idempotencyKey);return post("/internal/v1/question-generation/jobs",payload);}
  public Map<String,Object> eligibility(UUID factId){var fact=factSnapshot(factId);var reasons=eligibilityReasons(fact);boolean canGenerate=isAuthor()||isAdmin();boolean canInspect=canGenerate||isReviewer();var result=new LinkedHashMap<String,Object>();result.put("eligible",reasons.isEmpty());result.put("reasons",reasons);result.put("factStatus",fact.get("status"));result.put("reviewStatus",fact.get("reviewStatus"));result.put("sourceContextReady",sourceContextReady(uuid(fact.get("factVersionId"))));result.put("canGenerate",canGenerate);result.put("canInspect",canInspect);return result;}
  public List<Map<String,Object>> history(UUID factId,int limit){factSnapshot(factId);if(!isAuthor()&&!isAdmin()&&!isReviewer())throw forbidden();var jobs=getList("/internal/v1/question-generation/jobs?knowledgeFactId="+factId+"&limit="+limit);if(isAdmin()||isReviewer())return jobs;return jobs.stream().filter(job->actor().equals(job.get("requestedBy"))).toList();}
  public Map<String,Object> job(UUID id){var job=get("/internal/v1/question-generation/jobs/"+id);authorize(job);return job;}
  public List<Map<String,Object>> proposals(UUID id){var job=job(id);verifyCurrent(job);return getList("/internal/v1/question-generation/jobs/"+id+"/proposals");}
  public Map<String,Object> cancel(UUID id){var job=job(id);if(!isAdmin()&&!actor().equals(job.get("requestedBy")))throw forbidden();return post("/internal/v1/question-generation/jobs/"+id+"/cancel",Map.of());}
  public Map<String,Object> reject(UUID id,String reason,long version){var proposal=get("/internal/v1/question-generation/proposals/"+id);var job=job(uuid(proposal.get("generationJobId")));verifyCurrent(job);if(!isAdmin()&&!isReviewer()&&!actor().equals(job.get("requestedBy")))throw forbidden();return post("/internal/v1/question-generation/proposals/"+id+"/reject",Map.of("reason",reason==null?"":reason,"actor",actor(),"version",version));}

  @Transactional public Map<String,Object> accept(UUID proposalId,long version){
    requireAuthor();
    var existing=jdbc.sql("SELECT question_id FROM question_ai_provenance WHERE proposal_id=:id").param("id",proposalId).query(UUID.class).optional();
    if(existing.isPresent())return acceptedSummary(questions.question(existing.get()));
    var proposal=get("/internal/v1/question-generation/proposals/"+proposalId);
    if(!proposalId.equals(uuid(proposal.get("id"))))throw new DomainException(HttpStatus.NOT_FOUND,"AI_QUESTION_PROPOSAL_NOT_FOUND","Question proposal was not found");
    if(!"PROPOSED".equals(proposal.get("status")))throw conflict("AI_QUESTION_PROPOSAL_NOT_ACCEPTABLE","Only a proposed question can be accepted");
    if(((Number)proposal.get("version")).longValue()!=version)throw conflict("AI_QUESTION_PROPOSAL_STALE","Question proposal changed");
    var intelligence=map(proposal.get("intelligenceAssessment"));
    if(!"EVALUATED".equals(intelligence.get("evaluationStatus"))||!Boolean.TRUE.equals(intelligence.get("passedValidation")))
      throw conflict("AI_QUESTION_INTELLIGENCE_REJECTED","Question Intelligence validation must pass");
    var revalidation=post("/internal/v1/question-generation/proposals/"+proposalId+"/revalidate",Map.of());
    var fact=factSnapshot(uuid(proposal.get("targetKnowledgeFactId")));eligible(fact);
    if(!uuid(fact.get("factVersionId")).equals(uuid(proposal.get("targetKnowledgeFactVersionId")))||!checksum(String.valueOf(fact.get("canonicalStatement"))).equals(proposal.get("targetChecksum")))
      throw conflict("AI_QUESTION_GENERATION_INPUT_STALE","Knowledge Fact changed after the proposal was generated");
    var currentSources=sourceSnapshots(uuid(fact.get("factVersionId")));
    if(!sourceChecksums(currentSources).equals(sourceChecksums((List<Map<String,Object>>)revalidation.get("sourceChecksums"))))
      throw conflict("AI_QUESTION_GENERATION_SOURCE_CHANGED","A linked Source changed after the proposal was generated");
    var options=((List<Map<String,Object>>)proposal.get("answerOptions")).stream().map(o->new QuestionService.OptionInput(null,((Number)o.get("displayOrder")).intValue(),String.valueOf(o.get("text")),Boolean.TRUE.equals(o.get("correct")),null)).toList();
    UUID objective=uuid(proposal.get("learningObjectiveId"));
    exactDuplicate(objective,String.valueOf(proposal.get("questionText")),options);
    String difficulty=canonicalDifficulty(String.valueOf(intelligence.get("difficulty")));
    var created=questions.createAcceptedProposal(new QuestionService.AiQuestionInput(proposalId,objective,String.valueOf(proposal.get("questionType")),String.valueOf(proposal.get("questionText")),difficulty,
        String.valueOf(proposal.get("explanation")),String.valueOf(proposal.get("language")),uuid(proposal.get("targetKnowledgeFactId")),options,(String)intelligence.get("bloomsLevel"),(String)intelligence.get("complexity"),
        (String)intelligence.get("generationIntent"),integer(intelligence.get("estimatedReadingSeconds"))));
    var now=java.time.OffsetDateTime.now(java.time.ZoneOffset.UTC);UUID questionId=uuid(created.get("id")),questionVersionId=uuid(created.get("currentVersionId"));
    for(var source:currentSources)jdbc.sql("INSERT INTO question_source_reference(question_version_id,source_reference_id) VALUES(:version,:source)")
        .param("version",questionVersionId).param("source",uuid(source.get("sourceId"))).update();
    jdbc.sql("INSERT INTO question_ai_provenance(question_id,question_version_id,proposal_id,generation_job_id,knowledge_fact_id,knowledge_fact_version_id,knowledge_fact_checksum,source_checksums,proposal_checksum,provider,model,prompt_version,generated_at,accepted_by,accepted_at,intelligence_engine_version) VALUES(:question,:version,:proposal,:job,:fact,:factVersion,:factChecksum,CAST(:sources AS jsonb),:proposalChecksum,:provider,:model,:prompt,:generated,:actor,:accepted,:engine)")
        .param("question",questionId).param("version",questionVersionId).param("proposal",proposalId).param("job",uuid(proposal.get("generationJobId"))).param("fact",uuid(proposal.get("targetKnowledgeFactId")))
        .param("factVersion",uuid(proposal.get("targetKnowledgeFactVersionId"))).param("factChecksum",proposal.get("targetChecksum")).param("sources",json(sourceChecksums(currentSources)))
        .param("proposalChecksum",String.valueOf(revalidation.get("proposalChecksum"))).param("provider",proposal.get("provider")).param("model",proposal.get("model")).param("prompt",proposal.get("promptVersion"))
        .param("generated",java.time.OffsetDateTime.parse(String.valueOf(proposal.get("createdAt")))).param("actor",actor()).param("accepted",now).param("engine",revalidation.get("intelligenceEngineVersion")).update();
    audit(proposalId,questionId,"GROUNDING_REVALIDATED",Map.of("knowledgeFactId",proposal.get("targetKnowledgeFactId")));
    audit(proposalId,questionId,"QUESTION_INTELLIGENCE_REVALIDATED",Map.of("engineVersion",revalidation.get("intelligenceEngineVersion")));
    audit(proposalId,questionId,"QUESTION_CREATED_FROM_AI_PROPOSAL",Map.of("status","DRAFT"));
    audit(proposalId,questionId,"AI_PROPOSAL_LINKED_TO_QUESTION",Map.of("questionVersionId",questionVersionId));
    post("/internal/v1/question-generation/proposals/"+proposalId+"/accept",Map.of("questionId",questionId,"actor",actor(),"version",version,"validationChecksum",revalidation.get("validationChecksum")));
    audit(proposalId,questionId,"AI_QUESTION_PROPOSAL_ACCEPTED",Map.of("questionId",questionId));
    return acceptedSummary(created);
  }
  private Map<String,Object> factSnapshot(UUID id){var rows=jdbc.sql("SELECT f.id,f.review_status AS \"reviewStatus\",f.status,f.version,kfv.id AS \"factVersionId\",kfv.version_number AS \"versionNumber\",kfv.canonical_statement AS \"canonicalStatement\",kfv.review_status AS \"versionReviewStatus\",lo.id AS \"learningObjectiveId\",lo.title AS \"learningObjectiveTitle\",lo.description AS \"learningObjectiveDescription\",lo.status AS \"learningObjectiveStatus\",t.id AS \"topicId\",t.name AS \"topicTitle\",t.status AS \"topicStatus\",s.id AS \"subjectId\",s.name AS \"subjectTitle\",s.status AS \"subjectStatus\",ev.id AS \"examVersionId\",ev.status AS \"examVersionStatus\",e.id AS \"examId\",e.status AS \"examStatus\" FROM knowledge_fact f JOIN knowledge_fact_version kfv ON kfv.id=f.current_version_id JOIN learning_objective lo ON lo.id=f.learning_objective_id JOIN topic t ON t.id=lo.topic_id JOIN subject s ON s.id=t.subject_id JOIN exam_version ev ON ev.id=s.exam_version_id JOIN exam e ON e.id=ev.exam_id WHERE f.id=:id").param("id",id).query().listOfRows();if(rows.isEmpty())throw new DomainException(HttpStatus.NOT_FOUND,"AI_QUESTION_GENERATION_FACT_NOT_FOUND","Knowledge Fact was not found");return rows.getFirst();}
  private void eligible(Map<String,Object> fact){var reasons=eligibilityReasons(fact);if(reasons.isEmpty())return;String reason=reasons.getFirst();String code=switch(reason){case "FACT_NOT_APPROVED"->"AI_QUESTION_GENERATION_FACT_NOT_APPROVED";case "FACT_RETIRED"->"AI_QUESTION_GENERATION_FACT_RETIRED";case "FACT_INACTIVE"->"AI_QUESTION_GENERATION_FACT_INACTIVE";case "SOURCE_CONTEXT_NOT_READY"->"AI_QUESTION_GENERATION_SOURCE_CONTEXT_UNAVAILABLE";case "UNSUPPORTED_LANGUAGE"->"AI_QUESTION_GENERATION_FACT_UNSUPPORTED_LANGUAGE";default->"AI_QUESTION_GENERATION_FACT_INVALID";};String message=switch(reason){case "FACT_NOT_APPROVED"->"Fact must be approved before generating questions";case "FACT_RETIRED"->"Retired facts cannot be used for question generation";case "FACT_INACTIVE"->"Fact must be active before generating questions";case "SOURCE_CONTEXT_NOT_READY"->"Linked Source context is unavailable";case "UNSUPPORTED_LANGUAGE"->"Fact language is unsupported";default->"Fact text or hierarchy is not suitable for question generation";};throw validation(code,message);}
  private List<String> eligibilityReasons(Map<String,Object> fact){var reasons=new ArrayList<String>();if(!"APPROVED".equals(fact.get("reviewStatus"))||!"APPROVED".equals(fact.get("versionReviewStatus")))reasons.add("FACT_NOT_APPROVED");if("RETIRED".equals(fact.get("status")))reasons.add("FACT_RETIRED");else if(!"ACTIVE".equals(fact.get("status")))reasons.add("FACT_INACTIVE");if(List.of("ARCHIVED").contains(fact.get("learningObjectiveStatus"))||List.of("ARCHIVED").contains(fact.get("topicStatus"))||List.of("ARCHIVED").contains(fact.get("subjectStatus"))||List.of("ARCHIVED").contains(fact.get("examStatus"))||List.of("ARCHIVED").contains(fact.get("examVersionStatus")))reasons.add("FACT_HIERARCHY_INACTIVE");if(quality.validate(String.valueOf(fact.get("canonicalStatement"))).quality()!=KnowledgeFactTextQualityValidator.Quality.VALID)reasons.add("INVALID_CONTENT");if(!List.of("sv","en").contains(language.toLowerCase()))reasons.add("UNSUPPORTED_LANGUAGE");if(!sourceContextReady(uuid(fact.get("factVersionId"))))reasons.add("SOURCE_CONTEXT_NOT_READY");return reasons;}
  private boolean sourceContextReady(UUID versionId){var rows=jdbc.sql("SELECT s.content_text AS \"contentText\",s.content_checksum AS \"contentChecksum\",s.status FROM knowledge_fact_source k JOIN source_reference s ON s.id=k.source_reference_id WHERE k.knowledge_fact_version_id=:id").param("id",versionId).query().listOfRows();return !rows.isEmpty()&&rows.stream().allMatch(r->r.get("contentText")!=null&&r.get("contentChecksum")!=null&&!"RETIRED".equals(r.get("status")));}
  private List<Map<String,Object>> sourceSnapshots(UUID versionId){var rows=jdbc.sql("SELECT s.id,s.title,s.content_text AS \"contentText\",s.content_checksum AS \"contentChecksum\",s.status FROM knowledge_fact_source k JOIN source_reference s ON s.id=k.source_reference_id WHERE k.knowledge_fact_version_id=:id ORDER BY s.id").param("id",versionId).query().listOfRows();if(rows.isEmpty()||rows.stream().anyMatch(r->r.get("contentText")==null||r.get("contentChecksum")==null||"RETIRED".equals(r.get("status"))))throw validation("AI_QUESTION_GENERATION_SOURCE_CONTEXT_UNAVAILABLE","Linked Source context is unavailable");int remaining=maxSourceCharacters;var result=new ArrayList<Map<String,Object>>();for(var row:rows){String content=String.valueOf(row.get("contentText"));int length=Math.min(content.length(),Math.max(0,remaining));if(length==0)break;String excerpt=content.substring(0,length);result.add(Map.of("sourceId",row.get("id"),"title",row.get("title"),"checksum",checksum(excerpt),"contentExcerpt",excerpt));remaining-=length;}if(result.isEmpty())throw validation("AI_QUESTION_GENERATION_SOURCE_CONTEXT_UNAVAILABLE","Linked Source context is unavailable");return result;}
  private void verifyCurrent(Map<String,Object> job){var current=factSnapshot(uuid(job.get("targetKnowledgeFactId")));eligible(current);if(!uuid(current.get("factVersionId")).equals(uuid(job.get("targetKnowledgeFactVersionId")))||!checksum(String.valueOf(current.get("canonicalStatement"))).equals(job.get("targetChecksum")))throw new DomainException(HttpStatus.CONFLICT,"AI_QUESTION_GENERATION_INPUT_STALE","Knowledge Fact changed after generation was requested");}
  private void authorize(Map<String,Object> job){if(!isAdmin()&&!isReviewer()&&!actor().equals(job.get("requestedBy")))throw forbidden();}
  private void exactDuplicate(UUID objective,String text,List<QuestionService.OptionInput> options){
    String normalized=normalize(text);var candidates=jdbc.sql("SELECT id,current_version_id FROM question WHERE learning_objective_id=:objective AND lower(regexp_replace(trim(question_text),'\\s+',' ','g'))=:text AND status<>'RETIRED'")
        .param("objective",objective).param("text",normalized).query().listOfRows();
    var signature=options.stream().sorted(java.util.Comparator.comparing(QuestionService.OptionInput::displayOrder)).map(o->normalize(o.text())+"|"+o.correct()).toList();
    for(var candidate:candidates){var stored=jdbc.sql("SELECT text,correct FROM question_option WHERE question_version_id=:id ORDER BY display_order").param("id",candidate.get("current_version_id")).query().listOfRows().stream().map(o->normalize(String.valueOf(o.get("text")))+"|"+o.get("correct")).toList();if(signature.equals(stored))throw conflict("AI_QUESTION_DUPLICATE","An exact Question already exists under this Learning Objective");}
  }
  private List<Map<String,Object>> sourceChecksums(List<Map<String,Object>> values){return values.stream().map(v->Map.<String,Object>of("sourceId",String.valueOf(v.get("sourceId")),"checksum",String.valueOf(v.get("checksum")))).sorted(java.util.Comparator.comparing(v->String.valueOf(v.get("sourceId")))).toList();}
  private String canonicalDifficulty(String value){return switch(value){case "VERY_EASY"->"EASY";case "VERY_HARD"->"HARD";case "EASY","MEDIUM","HARD"->value;default->throw conflict("AI_QUESTION_DIFFICULTY_INVALID","Question Intelligence difficulty is unsupported");};}
  private Map<String,Object> acceptedSummary(Map<String,Object> question){return Map.of("questionId",question.get("id"),"status",question.get("status"),"reviewStatus",question.get("reviewStatus"),"location","/questions/"+question.get("id"));}
  @SuppressWarnings("unchecked")private Map<String,Object> map(Object value){return (Map<String,Object>)value;}
  private Integer integer(Object value){return value==null?null:((Number)value).intValue();}
  private String normalize(String value){return value==null?"":value.trim().replaceAll("\\s+"," ").toLowerCase(java.util.Locale.ROOT);}
  private String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException(e);}}
  private void audit(UUID proposalId,UUID questionId,String event,Map<String,Object> metadata){
    var authentication=SecurityContextHolder.getContext().getAuthentication();String roles=authentication.getAuthorities().stream().map(Object::toString).sorted().collect(java.util.stream.Collectors.joining(","));
    var details=new LinkedHashMap<String,Object>(metadata);details.put("proposalId",proposalId);details.put("questionId",questionId);details.put("event",event);
    jdbc.sql("INSERT INTO audit_event(id,occurred_at,actor_id,actor_name,actor_role,action,entity_type,entity_id,metadata,request_id) VALUES(:id,now(),:actor,:actor,:roles,'CREATE','AIQuestionAcceptance',:entity,CAST(:metadata AS jsonb),:request)")
        .param("id",UUID.randomUUID()).param("actor",actor()).param("roles",roles).param("entity",proposalId).param("metadata",json(details)).param("request","ai-question-accept-"+proposalId).update();
  }
  private Map<String,Object> get(String path){return send("GET",path,null,new TypeReference<>(){});}private List<Map<String,Object>> getList(String path){return send("GET",path,null,new TypeReference<>(){});}private Map<String,Object> post(String path,Object body){return send("POST",path,body,new TypeReference<>(){});}
  private <T>T send(String method,String path,Object body,TypeReference<T> type){if(apiKey.isBlank())throw new DomainException(HttpStatus.SERVICE_UNAVAILABLE,"AI_PROVIDER_NOT_CONFIGURED","AI Service authentication is not configured");try{var builder=HttpRequest.newBuilder(URI.create(baseUrl+path)).timeout(java.time.Duration.ofSeconds(15)).header("X-Internal-Api-Key",apiKey).header("Content-Type","application/json");String json=body==null?"":mapper.writeValueAsString(body);builder.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json));var response=http.send(builder.build(),HttpResponse.BodyHandlers.ofString());if(response.statusCode()/100==2)return mapper.readValue(response.body(),type);JsonNode error=mapper.readTree(response.body());throw new DomainException(HttpStatus.valueOf(response.statusCode()),error.path("code").asText("AI_PROVIDER_UNAVAILABLE"),error.path("message").asText("AI Service rejected the request"));}catch(DomainException e){throw e;}catch(Exception e){throw new DomainException(HttpStatus.SERVICE_UNAVAILABLE,"AI_PROVIDER_UNAVAILABLE","AI Service could not be reached");}}
  private void requireAuthor(){if(!isAuthor()&&!isAdmin())throw forbidden();}private boolean isAuthor(){return has("ROLE_CONTENT_AUTHOR");}private boolean isAdmin(){return has("ROLE_ADMIN");}private boolean isReviewer(){return has("ROLE_CONTENT_REVIEWER");}private boolean has(String role){return SecurityContextHolder.getContext().getAuthentication().getAuthorities().stream().anyMatch(a->role.equals(a.getAuthority()));}private String actor(){return SecurityContextHolder.getContext().getAuthentication().getName();}private DomainException forbidden(){return new DomainException(HttpStatus.FORBIDDEN,"FORBIDDEN","Question-generation permission is required");}private DomainException validation(String code,String message){return new DomainException(HttpStatus.UNPROCESSABLE_ENTITY,code,message);}private DomainException conflict(String code,String message){return new DomainException(HttpStatus.CONFLICT,code,message);}private UUID uuid(Object value){return value instanceof UUID u?u:UUID.fromString(String.valueOf(value));}
  private String checksum(String value){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
