package se.medbo.examplatform.ai.generation;

import com.fasterxml.jackson.core.JsonProcessingException;import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Types;import java.time.OffsetDateTime;import java.time.ZoneOffset;import java.util.List;import java.util.Map;import java.util.UUID;
import org.springframework.beans.factory.annotation.Value;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import se.medbo.examplatform.ai.provider.AiProviderClient;import se.medbo.examplatform.ai.provider.AiProviderException;
import se.medbo.examplatform.ai.editorial.EditorialJobService;

@Service
public class GenerationJobService {
    private final JdbcClient jdbc;private final AiProviderClient provider;private final StructuredOutputValidator validator;private final ObjectMapper mapper;private final EditorialJobService editorialJobs;
    private final boolean enabled;private final String providerName;private final String model;private final int maxSource;private final int maxCount;private final int maxRetries;private final int hourlyLimit;
    public record Create(UUID sourceId,String sourceTitle,String sourceContent,String sourceContentChecksum,UUID learningObjectiveId,String learningObjectiveTitle,String requestedBy,int requestedCount,String language,String editorialInstruction,String idempotencyKey){}
    public GenerationJobService(JdbcClient jdbc,AiProviderClient provider,StructuredOutputValidator validator,ObjectMapper mapper,EditorialJobService editorialJobs,
      @Value("${ai.editorial.enabled:false}")boolean enabled,@Value("${ai.editorial.provider:FAKE}")String providerName,@Value("${ai.editorial.model:deterministic-v1}")String model,
      @Value("${ai.editorial.max-source-characters:50000}")int maxSource,@Value("${ai.editorial.max-proposals:20}")int maxCount,@Value("${ai.editorial.max-retries:2}")int maxRetries,@Value("${ai.editorial.request-limit-per-hour:30}")int hourlyLimit){this.jdbc=jdbc;this.provider=provider;this.validator=validator;this.mapper=mapper;this.editorialJobs=editorialJobs;this.enabled=enabled;this.providerName=providerName;this.model=model;this.maxSource=maxSource;this.maxCount=maxCount;this.maxRetries=maxRetries;this.hourlyLimit=hourlyLimit;}
    @Transactional public Map<String,Object> create(Create in){
      if(!enabled)throw error(HttpStatus.SERVICE_UNAVAILABLE,"AI_FEATURE_DISABLED","AI-assisted generation is disabled");if(in.sourceContent()==null||in.sourceContent().isBlank())throw error(HttpStatus.UNPROCESSABLE_ENTITY,"AI_SOURCE_CONTENT_REQUIRED","Source content is required");if(in.sourceContent().length()>maxSource)throw error(HttpStatus.UNPROCESSABLE_ENTITY,"AI_SOURCE_TOO_LARGE","Source content exceeds the configured limit");if(in.requestedCount()<1||in.requestedCount()>maxCount)throw error(HttpStatus.UNPROCESSABLE_ENTITY,"AI_INVALID_GENERATION_REQUEST","Requested proposal count is outside the configured range");
      long recent=jdbc.sql("SELECT count(*) FROM ai_generation_job WHERE requested_by=:actor AND created_at>now()-interval '1 hour'").param("actor",in.requestedBy()).query(Long.class).single();if(recent>=hourlyLimit)throw error(HttpStatus.TOO_MANY_REQUESTS,"AI_RATE_LIMIT_EXCEEDED","The hourly AI generation limit was reached");
      var existing=jdbc.sql("SELECT id FROM ai_generation_job WHERE requested_by=:actor AND idempotency_key=:key").param("actor",in.requestedBy()).param("key",in.idempotencyKey()).query(UUID.class).list();if(!existing.isEmpty())return get(existing.getFirst());
      var id=UUID.randomUUID();var now=now();jdbc.sql("INSERT INTO ai_generation_job(id,job_type,source_id,source_title,source_content,source_content_checksum,learning_objective_id,learning_objective_title,requested_by,requested_count,language,editorial_instruction,idempotency_key,status,provider,model,prompt_version,created_at,next_attempt_at,input_character_count) VALUES(:id,'KNOWLEDGE_FACT',:source,:title,:content,:checksum,:objective,:objectiveTitle,:actor,:count,:language,:instruction,:key,'QUEUED',:provider,:model,:prompt,:now,:now,:chars)")
       .param("id",id).param("source",in.sourceId()).param("title",in.sourceTitle()).param("content",in.sourceContent()).param("checksum",in.sourceContentChecksum()).param("objective",in.learningObjectiveId()).param("objectiveTitle",in.learningObjectiveTitle()).param("actor",in.requestedBy()).param("count",in.requestedCount()).param("language",in.language()).param("instruction",blank(in.editorialInstruction()),Types.VARCHAR).param("key",in.idempotencyKey()).param("provider",providerName).param("model",model).param("prompt",PromptTemplateRegistry.KNOWLEDGE_FACT_V1).param("now",now).param("chars",in.sourceContent().length()).update();return get(id);
    }
    public Map<String,Object> get(UUID id){var rows=jdbc.sql("SELECT id,source_id AS \"sourceId\",source_title AS \"sourceTitle\",source_content_checksum AS \"sourceContentChecksum\",learning_objective_id AS \"learningObjectiveId\",learning_objective_title AS \"learningObjectiveTitle\",requested_by AS \"requestedBy\",requested_count AS \"requestedCount\",status,provider,model,prompt_version AS \"promptVersion\",created_at AS \"createdAt\",started_at AS \"startedAt\",completed_at AS \"completedAt\",failed_at AS \"failedAt\",cancelled_at AS \"cancelledAt\",retry_count AS \"retryCount\",input_tokens AS \"inputTokens\",output_tokens AS \"outputTokens\",total_tokens AS \"totalTokens\",reported_cost AS \"reportedCost\",provider_request_id AS \"providerRequestId\",error_code AS \"errorCode\",error_message AS \"errorMessage\",version,(SELECT count(*) FROM ai_knowledge_fact_proposal p WHERE p.generation_job_id=ai_generation_job.id) AS \"generatedCount\" FROM ai_generation_job WHERE id=:id").param("id",id).query().listOfRows();if(rows.isEmpty())throw error(HttpStatus.NOT_FOUND,"AI_JOB_NOT_FOUND","Generation job was not found");return rows.getFirst();}
    public List<Map<String,Object>> proposals(UUID job){get(job);var rows=jdbc.sql("SELECT id,generation_job_id AS \"generationJobId\",source_id AS \"sourceId\",learning_objective_id AS \"learningObjectiveId\",proposed_text AS \"proposedText\",edited_text AS \"editedText\",source_evidence::text AS \"sourceEvidence\",confidence,model_note AS \"modelNote\",status,rejection_reason AS \"rejectionReason\",resulting_knowledge_fact_id AS \"resultingKnowledgeFactId\",accepted_by AS \"acceptedBy\",accepted_at AS \"acceptedAt\",created_at AS \"createdAt\",updated_at AS \"updatedAt\",version FROM ai_knowledge_fact_proposal WHERE generation_job_id=:id ORDER BY created_at,id").param("id",job).query().listOfRows();rows.forEach(this::parseEvidence);return rows;}
    @Transactional public Map<String,Object> cancel(UUID id){var current=get(id);String status=(String)current.get("status");if(!List.of("QUEUED","RUNNING").contains(status))throw error(HttpStatus.CONFLICT,"AI_JOB_NOT_CANCELLABLE","The job can no longer be cancelled");jdbc.sql("UPDATE ai_generation_job SET cancellation_requested=true,status=CASE WHEN status='QUEUED' THEN 'CANCELLED' ELSE status END,cancelled_at=CASE WHEN status='QUEUED' THEN :now ELSE cancelled_at END,version=version+1 WHERE id=:id").param("now",now()).param("id",id).update();return get(id);}
    @Transactional public Map<String,Object> edit(UUID id,String text,long version){if(text==null||text.isBlank()||text.length()>500)throw error(HttpStatus.UNPROCESSABLE_ENTITY,"AI_INVALID_GENERATION_REQUEST","Proposal text must contain 1 to 500 characters");int n=jdbc.sql("UPDATE ai_knowledge_fact_proposal SET edited_text=:text,normalized_text=:normalized,status='EDITED',updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND status IN ('PROPOSED','EDITED')").param("text",text.trim()).param("normalized",StructuredOutputValidator.normalize(text)).param("now",now()).param("id",id).param("version",version).update();if(n==0)throw error(HttpStatus.CONFLICT,"STALE_VERSION","The proposal changed or is no longer editable");return proposal(id);}
    @Transactional public Map<String,Object> reject(UUID id,String reason,long version){int n=jdbc.sql("UPDATE ai_knowledge_fact_proposal SET status='REJECTED',rejection_reason=:reason,updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND status IN ('PROPOSED','EDITED')").param("reason",blank(reason),Types.VARCHAR).param("now",now()).param("id",id).param("version",version).update();if(n==0)throw error(HttpStatus.CONFLICT,"AI_PROPOSAL_ALREADY_PROCESSED","The proposal was already processed");return proposal(id);}
    @Transactional public Map<String,Object> markAccepted(UUID id,UUID fact,String actor,long version){int n=jdbc.sql("UPDATE ai_knowledge_fact_proposal SET status='ACCEPTED',resulting_knowledge_fact_id=:fact,accepted_by=:actor,accepted_at=:now,updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND status IN ('PROPOSED','EDITED')").param("fact",fact).param("actor",actor).param("now",now()).param("id",id).param("version",version).update();if(n==0)throw error(HttpStatus.CONFLICT,"AI_PROPOSAL_ALREADY_ACCEPTED","The proposal was already processed");return proposal(id);}
    public Map<String,Object> proposal(UUID id){var rows=jdbc.sql("SELECT p.id,p.generation_job_id,p.source_id,p.learning_objective_id,p.proposed_text,p.edited_text,p.source_evidence::text AS source_evidence,p.confidence,p.model_note,p.status,p.rejection_reason,p.resulting_knowledge_fact_id,p.accepted_by,p.accepted_at,p.created_at,p.updated_at,p.version,j.provider,j.model,j.prompt_version,j.created_at AS generated_at,j.requested_by,j.source_content_checksum,j.provider_request_id,j.input_tokens,j.output_tokens FROM ai_knowledge_fact_proposal p JOIN ai_generation_job j ON j.id=p.generation_job_id WHERE p.id=:id").param("id",id).query().listOfRows();if(rows.isEmpty())throw error(HttpStatus.NOT_FOUND,"AI_PROPOSAL_NOT_FOUND","Proposal was not found");return rows.getFirst();}
    @Scheduled(fixedDelay=1000) public void work(){if(!enabled)return;if(editorialJobs.workOne())return;var jobs=jdbc.sql("SELECT id FROM ai_generation_job WHERE operation_type IS NULL AND status='QUEUED' AND cancellation_requested=false AND next_attempt_at<=now() ORDER BY created_at LIMIT 1").query(UUID.class).list();if(!jobs.isEmpty())run(jobs.getFirst());}
    void run(UUID id){Map<String,Object> row;int claimed=jdbc.sql("UPDATE ai_generation_job SET status='RUNNING',started_at=coalesce(started_at,:now),version=version+1 WHERE id=:id AND status='QUEUED' AND cancellation_requested=false").param("now",now()).param("id",id).update();if(claimed==0)return;row=jdbc.sql("SELECT * FROM ai_generation_job WHERE id=:id").param("id",id).query().singleRow();try{var result=provider.generate(new AiProviderClient.GenerationRequest((String)row.get("source_content"),(String)row.get("learning_objective_title"),(String)row.get("language"),(Integer)row.get("requested_count"),(String)row.get("editorial_instruction"),(String)row.get("prompt_version"),id,(String)row.get("requested_by"),(Integer)row.get("retry_count")));validator.validate(result,(String)row.get("source_content"),(Integer)row.get("requested_count"));if(Boolean.TRUE.equals(jdbc.sql("SELECT cancellation_requested FROM ai_generation_job WHERE id=:id").param("id",id).query(Boolean.class).single())){cancelRunning(id);return;}persist(id,row,result);}
      catch(AiProviderException e){failOrRetry(id,(Integer)row.get("retry_count"),e);}catch(Exception e){failOrRetry(id,(Integer)row.get("retry_count"),new AiProviderException("AI_PROVIDER_UNAVAILABLE",true,"The AI provider is temporarily unavailable"));}}
    @Transactional void persist(UUID id,Map<String,Object> row,AiProviderClient.GenerationResult result){var now=now();for(var p:result.proposals()){jdbc.sql("INSERT INTO ai_knowledge_fact_proposal(id,generation_job_id,source_id,learning_objective_id,proposed_text,edited_text,source_evidence,confidence,model_note,status,created_at,updated_at,normalized_text) VALUES(:id,:job,:source,:objective,:text,:text,CAST(:evidence AS jsonb),:confidence,:note,'PROPOSED',:now,:now,:normalized) ON CONFLICT(generation_job_id,normalized_text) DO NOTHING").param("id",UUID.randomUUID()).param("job",id).param("source",row.get("source_id")).param("objective",row.get("learning_objective_id")).param("text",p.text()).param("evidence",json(p.sourceEvidence())).param("confidence",p.confidence(),Types.VARCHAR).param("note",p.notes(),Types.VARCHAR).param("now",now).param("normalized",StructuredOutputValidator.normalize(p.text())).update();}int count=jdbc.sql("SELECT count(*) FROM ai_knowledge_fact_proposal WHERE generation_job_id=:id").param("id",id).query(Integer.class).single();var usage=result.usage();jdbc.sql("UPDATE ai_generation_job SET status=:status,completed_at=:now,input_tokens=:input,output_tokens=:output,total_tokens=:total,provider_request_id=:request,version=version+1 WHERE id=:id").param("status",count<(Integer)row.get("requested_count")?"PARTIALLY_COMPLETED":"COMPLETED").param("now",now).param("input",usage==null?null:usage.inputTokens(),Types.INTEGER).param("output",usage==null?null:usage.outputTokens(),Types.INTEGER).param("total",usage==null||usage.inputTokens()==null||usage.outputTokens()==null?null:usage.inputTokens()+usage.outputTokens(),Types.INTEGER).param("request",usage==null?null:usage.requestId(),Types.VARCHAR).param("id",id).update();}
    private void failOrRetry(UUID id,int retries,AiProviderException e){if(e.transientFailure()&&retries<maxRetries){long delay=(long)Math.pow(2,retries+1);jdbc.sql("UPDATE ai_generation_job SET status='QUEUED',retry_count=retry_count+1,next_attempt_at=:next,error_code=:code,error_message=:message,version=version+1 WHERE id=:id").param("next",now().plusSeconds(delay)).param("code",e.code()).param("message",sanitize(e.getMessage())).param("id",id).update();}else jdbc.sql("UPDATE ai_generation_job SET status='FAILED',failed_at=:now,error_code=:code,error_message=:message,version=version+1 WHERE id=:id").param("now",now()).param("code",e.code()).param("message",sanitize(e.getMessage())).param("id",id).update();}
    private void cancelRunning(UUID id){jdbc.sql("UPDATE ai_generation_job SET status='CANCELLED',cancelled_at=:now,version=version+1 WHERE id=:id").param("now",now()).param("id",id).update();}
    private void parseEvidence(Map<String,Object> row){try{row.put("sourceEvidence",mapper.readValue((String)row.get("sourceEvidence"),List.class));}catch(Exception e){throw new IllegalStateException("Stored proposal evidence is invalid",e);}}private String json(Object o){try{return mapper.writeValueAsString(o);}catch(JsonProcessingException e){throw new IllegalStateException(e);}}private String blank(String s){return s==null||s.isBlank()?null:s.trim();}private String sanitize(String s){return s==null?null:s.replaceAll("[\\r\\n]"," ").substring(0,Math.min(500,s.length()));}private OffsetDateTime now(){return OffsetDateTime.now(ZoneOffset.UTC);}private AiApiException error(HttpStatus s,String c,String m){return new AiApiException(s,c,m);}
}
