import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { listKnowledgeFacts,type FactReviewStatus,type FactStatus } from '../../../api/generated';
import { contentServiceClient } from '../../../api/client/contentServiceClient';
import { unwrap } from '../../../api/client/adminApi';
import { adminQueryKeys } from '../../../api/query-keys/adminQueryKeys';
import { AsyncState } from '../../../components/AsyncState';

export function KnowledgeFactListPage(){const[search,setSearch]=useState('');const[review,setReview]=useState('');const[status,setStatus]=useState('');const[publisher,setPublisher]=useState('');const[validAt,setValidAt]=useState('');const[page,setPage]=useState(0);const filters={search,review,status,publisher,validAt,page};const query=useQuery({queryKey:adminQueryKeys.facts.list(filters),queryFn:()=>unwrap(listKnowledgeFacts({client:contentServiceClient,query:{page,size:20,search:search||undefined,reviewStatus:(review||undefined)as FactReviewStatus|undefined,status:(status||undefined)as FactStatus|undefined,sourcePublisher:publisher||undefined,validAt:validAt||undefined}}))});return <><header className="page-header"><div><h1>Knowledge facts</h1><p>Canonical, source-backed statements used by future questions.</p></div><div className="actions"><Link className="button" to="/knowledge/objectives">Learning objectives</Link><Link className="button" to="/knowledge/facts/new">Create fact</Link></div></header><div className="filters"><label>Search<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label><label>Review<select value={review} onChange={e=>setReview(e.target.value)}><option value="">All</option><option>UNREVIEWED</option><option>UNDER_REVIEW</option><option>APPROVED</option><option>REJECTED</option><option>REQUIRES_UPDATE</option></select></label><label>Lifecycle<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option>DRAFT</option><option>ACTIVE</option><option>RETIRED</option></select></label><label>Source publisher<input value={publisher} onChange={e=>setPublisher(e.target.value)}/></label><label>Valid on<input type="date" value={validAt} onChange={e=>setValidAt(e.target.value)}/></label></div><AsyncState loading={query.isPending} error={query.error}>{query.data?.items.length===0?<p>No knowledge facts match these filters.</p>:<table><thead><tr><th>Statement</th><th>Topic / objective</th><th>Review</th><th>Lifecycle</th><th>Sources</th><th>Updated</th></tr></thead><tbody>{query.data?.items.map(f=><tr key={f.id}><td><Link to={`/knowledge/facts/${f.id}`}>{f.canonicalStatement}</Link></td><td>{f.topicName} / {f.learningObjectiveTitle}</td><td>{f.reviewStatus}</td><td>{f.status}</td><td>{f.sourceCount}</td><td>{new Date(f.updatedAt).toLocaleDateString()}</td></tr>)}</tbody></table>}<div className="pager"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={!query.data||page+1>=query.data.totalPages} onClick={()=>setPage(p=>p+1)}>Next</button></div></AsyncState></>}
