import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { ReactNode } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Screen } from '../../components/Screen';
import { Body, Button, Card, Icon, Title } from '../../components/ui';
import type { RootStackParamList } from '../../navigation/types';
import { theme } from '../../theme';
import { useAuth } from './AuthContext';

function AuthLayout({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children:ReactNode}){return <Screen><View style={styles.brand}><Icon name="profile" size={42}/><Text style={styles.brandName}>Svea Study</Text></View><Card><Text style={styles.eyebrow}>{eyebrow}</Text><Title>{title}</Title><Body>{description}</Body><View style={styles.actions}>{children}</View></Card><Text style={styles.privacy}>Your account stores only the information needed for learning and progress.</Text></Screen>}
export function WelcomeScreen({navigation}:NativeStackScreenProps<RootStackParamList,'Welcome'>){return <AuthLayout eyebrow="Swedish citizenship preparation" title="Welcome to Svea Study" description="Sign in to keep your practice, mock exams and progress securely connected to your account."><Button label="Sign in" onPress={()=>navigation.navigate('Login')}/><Button label="Create account" variant="secondary" onPress={()=>navigation.navigate('Register')}/></AuthLayout>}
export function LoginScreen({navigation}:NativeStackScreenProps<RootStackParamList,'Login'>){const auth=useAuth();return <AuthLayout eyebrow="Welcome back" title="Sign in" description="Continue securely through the Svea Study identity service."><Button label="Continue to sign in" onPress={()=>void auth.login()}/><Button label="Forgot password?" variant="secondary" onPress={()=>navigation.navigate('ForgotPassword')}/></AuthLayout>}
export function RegisterScreen(){const auth=useAuth();return <AuthLayout eyebrow="Create your account" title="Start learning" description="Registration, password policy, terms acceptance and email verification are handled securely by our identity provider."><Button label="Continue to registration" onPress={()=>void auth.register()}/></AuthLayout>}
export function ForgotPasswordScreen(){const auth=useAuth();return <AuthLayout eyebrow="Account recovery" title="Reset your password" description="Continue to the secure identity service. Its response is intentionally neutral and does not reveal whether an email is registered."><Button label="Continue to password reset" onPress={()=>void auth.forgotPassword()}/></AuthLayout>}
export function VerificationPendingScreen(){const auth=useAuth();return <AuthLayout eyebrow="Almost finished" title="Verify your email" description="Open the verification message sent by the identity service. After verification, sign in again to continue."><Button label="Sign in after verification" onPress={()=>void auth.login()}/><Button label="Use another account" variant="secondary" onPress={()=>void auth.logout()}/></AuthLayout>}
export function SessionExpiredScreen(){const auth=useAuth();return <AuthLayout eyebrow="Session ended" title="Please sign in again" description="Your secure session could not be refreshed. Your saved learning data remains available after you sign in."><Button label="Sign in" onPress={()=>void auth.login()}/><Button label="Return to welcome" variant="secondary" onPress={()=>void auth.logout()}/></AuthLayout>}
const styles=StyleSheet.create({brand:{alignItems:'center',gap:theme.spacing.xs,marginVertical:theme.spacing.lg},brandName:{color:theme.colors.primary,fontSize:28,fontWeight:'800'},eyebrow:{color:theme.colors.primary,fontSize:13,fontWeight:'700',letterSpacing:1,textTransform:'uppercase'},actions:{gap:theme.spacing.sm,marginTop:theme.spacing.sm},privacy:{color:theme.colors.muted,...theme.typography.caption,textAlign:'center'}});
