import { Alert, StyleSheet, Text, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Screen } from '../../components/Screen';
import { Body, Button, Card, Loading, StatusBadge, Title } from '../../components/ui';
import { theme } from '../../theme';
import { useAuth } from './AuthContext';
import { learningApi } from '../../api/learningApi';

export function ProfileScreen(){const auth=useAuth();const qc=useQueryClient();const identity=auth.claims?.sub??'';const profile=useQuery({queryKey:['learner-profile',identity],queryFn:()=>learningApi.profile(identity),enabled:Boolean(identity)});const deletion=useMutation({mutationFn:()=>learningApi.deleteAccount(identity),onSuccess:async()=>{qc.clear();await auth.logout();}});const remove=()=>Alert.alert('Delete account?','Your profile will be anonymised and the account disabled. This cannot be undone.',[{text:'Cancel',style:'cancel'},{text:'Delete account',style:'destructive',onPress:()=>deletion.mutate()}]);if(!auth.claims||profile.isLoading)return <Screen><Loading label="Loading account…"/></Screen>;const data=profile.data;return <Screen><Title>Profile</Title><Body>Your authenticated learner account.</Body><Card><View style={styles.row}><Text style={styles.label}>Display name</Text><Text style={styles.value}>{data?.displayName??auth.claims.name??'Learner'}</Text></View><View style={styles.row}><Text style={styles.label}>Email</Text><Text style={styles.value}>{data?.email??auth.claims.email??'Not provided'}</Text></View><StatusBadge label={(data?.emailVerified??auth.claims.email_verified)?'Email verified':'Verification required'} tone={(data?.emailVerified??auth.claims.email_verified)?'success':'neutral'}/><StatusBadge label={data?.accountStatus??'ACTIVE'} tone="success"/></Card><Card><Title>Account</Title><Button label="Log out" variant="secondary" onPress={()=>void auth.logout()}/><Button label={deletion.isPending?'Deleting account…':'Delete account'} variant="secondary" disabled={deletion.isPending} onPress={remove}/>{deletion.isError?<Body>We could not delete your account. Please try again.</Body>:null}</Card><Text style={styles.links}>Privacy policy · Terms of use</Text></Screen>}
const styles=StyleSheet.create({row:{gap:theme.spacing.xxs},label:{color:theme.colors.muted,...theme.typography.caption},value:{color:theme.colors.text,...theme.typography.body},links:{color:theme.colors.primary,textAlign:'center'}});
