import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {listReleases,type ReleaseStatus} from '../../../api/generated';
import {contentServiceClient} from '../../../api/client/contentServiceClient';
import {unwrap} from '../../../api/client/adminApi';
import {adminQueryKeys} from '../../../api/query-keys/adminQueryKeys';
import {AsyncState} from '../../../components/AsyncState';

export function ReleaseListPage(){const[search,setSearch]=useState('');const[status,setStatus]=useState('');const[page,setPage]=useState(0);const filters={search,status,page};const query=useQuery({queryKey:adminQueryKeys.releases.list(filters),queryFn:()=>unwrap(listReleases({client:contentServiceClient,query:{search:search||undefined,status:(status||undefined)as ReleaseStatus|undefined,page,size:20}}))});return <><header className="page-header"><div><h1>Releases</h1><p>Build, validate, publish, deliver and activate immutable learner content.</p></div><Link className="button" to="/releases/new">Create release</Link></header><div className="filters"><label>Search<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option>{['DRAFT','VALIDATED','PUBLISHED','DELIVERY_FAILED','DELIVERED','ACTIVE','RETIRED'].map(x=><option key={x}>{x}</option>)}</select></label></div><AsyncState loading={query.isPending} error={query.error}>{query.data?.items.length===0?<p>No releases match these filters.</p>:<table><thead><tr><th>Release</th><th>Exam version</th><th>Status</th><th>Questions</th><th>Facts</th><th>Updated</th></tr></thead><tbody>{query.data?.items.map(r=><tr key={r.id}><td><Link to={`/releases/${r.id}`}>{r.displayName}</Link><br/><small>{r.releaseNumber}</small></td><td>{r.examName}<br/><small>{r.examVersionName}</small></td><td><span className="status">{r.status}</span></td><td>{r.questionCount}</td><td>{r.knowledgeFactCount}</td><td>{new Date(r.updatedAt).toLocaleDateString()}</td></tr>)}</tbody></table>}<div className="pager"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={!query.data||page+1>=query.data.totalPages} onClick={()=>setPage(p=>p+1)}>Next</button></div></AsyncState></>}
