import {render,screen} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {AuthProvider} from '../app/auth/AuthContext';
import {AppRouter} from '../app/router/AppRouter';
import {AdminRole} from '../app/permissions/permissions';
import {adminSessionStorageKey} from '../app/auth/authSession';
function json(body:object){return new Response(JSON.stringify(body),{status:200,headers:{'content-type':'application/json'}})}
function renderRoute(path:string){sessionStorage.setItem(adminSessionStorageKey,JSON.stringify({id:'admin',displayName:'Administrator',roles:[AdminRole.Admin]}));const client=new QueryClient({defaultOptions:{queries:{retry:false}}});return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]}><AuthProvider><AppRouter/></AuthProvider></MemoryRouter></QueryClientProvider>)}
describe('Phase 7 operations',()=>{
  it('renders all operational health sections with aggregate data',async()=>{vi.stubGlobal('fetch',vi.fn().mockImplementation((request:Request)=>{const url=request.url;if(url.includes('content-health'))return Promise.resolve(json({questionsMissingFacts:2,factsWithoutQuestions:3,objectivesWithoutQuestions:1,topicsWithoutQuestions:0,subjectsWithoutQuestions:0}));if(url.includes('review-health'))return Promise.resolve(json({pending:4,assignedToMe:1,averageAgeHours:12,rejectedToday:0,requiresUpdateToday:1}));if(url.includes('source-health'))return Promise.resolve(json({retired:1,requiresUpdate:2,unused:3,factsReferencingRetired:0,factsReferencingOutdated:1}));if(url.includes('learner-health'))return Promise.resolve(json({practiceSessions:8,mockExams:2,activeMockExams:1,completedMockExams:1,expiredMockExams:0,averageScore:75,passRate:100,averageDurationSeconds:300}));return Promise.resolve(json({published:1,failedDeliveries:0}));}));renderRoute('/reports');expect(screen.getByRole('heading',{name:'Platform health'})).toBeInTheDocument();expect(await screen.findByText('8')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Learner runtime health'})).toBeInTheDocument();});
  it('renders filterable audit events and expandable detail',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(json({items:[{id:'3fef62e4-ea78-4f03-bdbb-fab1b97edc30',timestamp:'2026-07-20T10:00:00Z',actorId:'author',actorName:'Author',actorRole:'CONTENT_AUTHOR',action:'CREATE',entityType:'Question',entityId:'3fef62e4-ea78-4f03-bdbb-fab1b97edc31',metadata:{},requestId:'req-1',newState:{status:'DRAFT'}}],page:0,size:25,totalItems:1,totalPages:1})));renderRoute('/audit');expect(screen.getByRole('heading',{name:'Audit log'})).toBeInTheDocument();expect(await screen.findByText('Author')).toBeInTheDocument();expect(screen.getByText('View change')).toBeInTheDocument();});
});
