package se.medbo.examplatform.content.review;

import java.sql.Types;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import se.medbo.examplatform.content.knowledge.KnowledgeBaseService;
import se.medbo.examplatform.content.question.QuestionService;
import se.medbo.examplatform.content.shared.DomainException;

@Service
public class ReviewQueryService {
    private static final String PROJECTION="SELECT ri.id,ri.content_type AS \"contentType\",ri.content_id AS \"contentId\",ri.content_version_id AS \"contentVersionId\",COALESCE(q.code,'FACT') AS \"contentCode\",COALESCE(q.question_text,f.canonical_statement) AS \"titleOrSummary\",ri.review_status AS \"reviewStatus\",ri.lifecycle_status AS \"lifecycleStatus\",ri.author_id AS \"authorId\",ri.author_id AS \"authorName\",ri.submitted_at AS \"submittedAt\",ri.updated_at AS \"updatedAt\",ri.assigned_reviewer_id AS \"assignedReviewerId\",ri.assigned_reviewer_id AS \"assignedReviewerName\",ri.priority,lo.id AS \"learningObjectiveId\",lo.title AS \"learningObjectiveTitle\",t.id AS \"topicId\",t.name AS \"topicName\",s.id AS \"subjectId\",s.name AS \"subjectName\",ri.version,false AS stale,(CASE WHEN ri.content_type='KNOWLEDGE_FACT' THEN (SELECT count(*) FROM question_knowledge_fact qkf WHERE qkf.knowledge_fact_version_id=ri.content_version_id) ELSE 0 END) AS \"impactWarningCount\" FROM review_item ri LEFT JOIN knowledge_fact f ON ri.content_type='KNOWLEDGE_FACT' AND f.id=ri.content_id LEFT JOIN question q ON ri.content_type='QUESTION' AND q.id=ri.content_id JOIN learning_objective lo ON lo.id=COALESCE(f.learning_objective_id,q.learning_objective_id) JOIN topic t ON t.id=lo.topic_id JOIN subject s ON s.id=t.subject_id ";
    private final JdbcClient jdbc;private final KnowledgeBaseService facts;private final QuestionService questions;private final ReviewWorkflowService workflow;
    public ReviewQueryService(JdbcClient jdbc,KnowledgeBaseService facts,QuestionService questions,ReviewWorkflowService workflow){this.jdbc=jdbc;this.facts=facts;this.questions=questions;this.workflow=workflow;}

    public Map<String,Object> queue(int page,int size,String search,String contentType,String reviewStatus,String lifecycle,UUID subject,UUID topic,UUID objective,String author,String assigned,Boolean unassigned,Boolean assignedToMe,LocalDate submittedFrom,LocalDate submittedTo,String priority,String sort,String direction,Boolean warnings){
        page=Math.max(0,page);size=Math.min(100,Math.max(1,size));String current=workflow.actor();if(!canReview())author=current;if("ALL".equals(reviewStatus))reviewStatus=null;
        var where=" WHERE (CAST(:search AS text) IS NULL OR lower(COALESCE(q.question_text,f.canonical_statement)) LIKE lower('%'||:search||'%') OR lower(COALESCE(q.code,'')) LIKE lower('%'||:search||'%') OR lower(ri.author_id) LIKE lower('%'||:search||'%') OR lower(t.name) LIKE lower('%'||:search||'%') OR lower(lo.title) LIKE lower('%'||:search||'%')) AND (CAST(:type AS text) IS NULL OR ri.content_type=:type) AND (CAST(:review AS text) IS NULL OR ri.review_status=:review) AND (CAST(:lifecycle AS text) IS NULL OR ri.lifecycle_status=:lifecycle) AND (CAST(:subject AS uuid) IS NULL OR s.id=:subject) AND (CAST(:topic AS uuid) IS NULL OR t.id=:topic) AND (CAST(:objective AS uuid) IS NULL OR lo.id=:objective) AND (CAST(:author AS text) IS NULL OR ri.author_id=:author) AND (CAST(:assigned AS text) IS NULL OR ri.assigned_reviewer_id=:assigned) AND (:unassigned=false OR ri.assigned_reviewer_id IS NULL) AND (:mine=false OR ri.assigned_reviewer_id=:current) AND (CAST(:fromDate AS date) IS NULL OR ri.submitted_at>=:fromDate) AND (CAST(:toDate AS date) IS NULL OR ri.submitted_at<(:toDate+1)) AND (CAST(:priority AS text) IS NULL OR ri.priority=:priority) AND (:warnings=false OR (ri.content_type='KNOWLEDGE_FACT' AND EXISTS(SELECT 1 FROM question_knowledge_fact qkf WHERE qkf.knowledge_fact_version_id=ri.content_version_id))) ";
        var count=jdbc.sql("SELECT count(*) FROM ("+PROJECTION+where+") x");params(count,search,contentType,reviewStatus,lifecycle,subject,topic,objective,author,assigned,unassigned,assignedToMe,current,submittedFrom,submittedTo,priority,warnings);long total=count.query(Long.class).single();
        String order=switch(sort==null?"default":sort){case "submittedAt"->"ri.submitted_at";case "updatedAt"->"ri.updated_at";case "priority"->"CASE ri.priority WHEN 'URGENT' THEN 4 WHEN 'HIGH' THEN 3 WHEN 'NORMAL' THEN 2 ELSE 1 END";default->"CASE ri.priority WHEN 'URGENT' THEN 4 WHEN 'HIGH' THEN 3 WHEN 'NORMAL' THEN 2 ELSE 1 END DESC,ri.submitted_at";};String dir="desc".equalsIgnoreCase(direction)?"DESC":"ASC";if("default".equals(sort)||sort==null)dir="ASC";
        var query=jdbc.sql(PROJECTION+where+" ORDER BY "+order+" "+dir+",ri.id ASC LIMIT :size OFFSET :offset");params(query,search,contentType,reviewStatus,lifecycle,subject,topic,objective,author,assigned,unassigned,assignedToMe,current,submittedFrom,submittedTo,priority,warnings);var items=query.param("size",size).param("offset",page*size).query().listOfRows();return Map.of("items",items,"page",page,"size",size,"totalItems",total,"totalPages",(total+size-1)/size);
    }

    public Map<String,Object> summary(){String actor=workflow.actor();return jdbc.sql("SELECT count(*) FILTER(WHERE review_status='UNDER_REVIEW') AS \"awaitingReview\",count(*) FILTER(WHERE review_status='UNDER_REVIEW' AND assigned_reviewer_id=:actor) AS \"assignedToMe\",count(*) FILTER(WHERE review_status='UNDER_REVIEW' AND assigned_reviewer_id IS NULL) AS unassigned,count(*) FILTER(WHERE review_status='REQUIRES_UPDATE') AS \"requiresUpdate\",count(*) FILTER(WHERE review_status='UNDER_REVIEW' AND priority IN ('HIGH','URGENT')) AS \"highPriority\",COALESCE(EXTRACT(epoch FROM (now()-min(submitted_at) FILTER(WHERE review_status='UNDER_REVIEW')))/86400,0) AS \"oldestPendingAgeDays\" FROM review_item WHERE (:reviewer=true OR author_id=:actor)").param("actor",actor).param("reviewer",canReview()).query().singleRow();}
    public Map<String,Object> detail(UUID id){var item=one(id);String type=(String)item.get("contentType");UUID contentId=(UUID)item.get("contentId");item.put("content","KNOWLEDGE_FACT".equals(type)?facts.fact(contentId):questions.question(contentId));item.put("history",history(id));item.put("comments",comments(id));if("KNOWLEDGE_FACT".equals(type))item.put("sourceContext",sourceContext((UUID)item.get("contentVersionId")));else item.put("factSourceContext",factSourceContext((UUID)item.get("contentVersionId")));return item;}
    public List<Map<String,Object>> history(UUID id){one(id);return jdbc.sql("SELECT rr.id,rr.content_version_id AS \"contentVersionId\",rr.action,rr.from_status AS \"fromStatus\",rr.to_status AS \"toStatus\",rr.actor_id AS \"actorId\",rr.actor_roles AS \"actorRoles\",rr.comment,rr.reason_code AS \"reasonCode\",rr.metadata,rr.created_at AS \"createdAt\" FROM review_record rr JOIN review_item source ON source.id=:id JOIN review_item cycle ON cycle.id=rr.review_item_id AND cycle.content_type=source.content_type AND cycle.content_id=source.content_id ORDER BY rr.created_at,rr.id").param("id",id).query().listOfRows();}
    public List<Map<String,Object>> comments(UUID id){one(id);return jdbc.sql("SELECT rc.id,rc.content_version_id AS \"contentVersionId\",rc.author_id AS \"authorId\",rc.author_id AS \"authorName\",rc.body,rc.created_at AS \"createdAt\" FROM review_comment rc JOIN review_item source ON source.id=:id JOIN review_item cycle ON cycle.id=rc.review_item_id AND cycle.content_type=source.content_type AND cycle.content_id=source.content_id ORDER BY rc.created_at,rc.id").param("id",id).query().listOfRows();}

    @Transactional public Map<String,Object> claim(UUID id,long version){var item=one(id);if(workflow.actor().equals(item.get("authorId")))throw forbidden("Authors cannot claim their own content");int changed=jdbc.sql("UPDATE review_item SET assigned_reviewer_id=:actor,assigned_at=:now,updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND assigned_reviewer_id IS NULL AND review_status='UNDER_REVIEW'").param("actor",workflow.actor()).param("now",now()).param("id",id).param("version",version).update();if(changed==0)throw conflict("REVIEW_ITEM_ALREADY_CLAIMED","The review item is already claimed or stale");record(id,(UUID)item.get("contentVersionId"),"CLAIMED",null);return detail(id);}
    @Transactional public Map<String,Object> unclaim(UUID id,long version){var item=one(id);boolean admin=isAdmin();if(!admin&&!workflow.actor().equals(item.get("assignedReviewerId")))throw forbidden("Only the assigned reviewer may unclaim this item");int changed=jdbc.sql("UPDATE review_item SET assigned_reviewer_id=NULL,assigned_at=NULL,updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND assigned_reviewer_id IS NOT NULL").param("now",now()).param("id",id).param("version",version).update();if(changed==0)throw conflict("STALE_REVIEW_VERSION","The review item changed; reload it");record(id,(UUID)item.get("contentVersionId"),"UNCLAIMED",null);return detail(id);}
    @Transactional public Map<String,Object> assign(UUID id,long version,String reviewer){if(!isAdmin())throw forbidden("Only an administrator may assign reviewers");if(reviewer==null||reviewer.isBlank())throw validation("assignedReviewerId is required");var item=one(id);String action=item.get("assignedReviewerId")==null?"ASSIGNED":"REASSIGNED";int changed=jdbc.sql("UPDATE review_item SET assigned_reviewer_id=:reviewer,assigned_at=:now,updated_at=:now,version=version+1 WHERE id=:id AND version=:version AND review_status='UNDER_REVIEW'").param("reviewer",reviewer.trim()).param("now",now()).param("id",id).param("version",version).update();if(changed==0)throw conflict("STALE_REVIEW_VERSION","The review item changed; reload it");record(id,(UUID)item.get("contentVersionId"),action,"Assigned to "+reviewer.trim());return detail(id);}
    @Transactional public Map<String,Object> priority(UUID id,long version,String priority){if(!isAdmin())throw forbidden("Only an administrator may change priority");if(!List.of("LOW","NORMAL","HIGH","URGENT").contains(priority))throw validation("Invalid priority");var item=one(id);int changed=jdbc.sql("UPDATE review_item SET priority=:priority,updated_at=:now,version=version+1 WHERE id=:id AND version=:version").param("priority",priority).param("now",now()).param("id",id).param("version",version).update();if(changed==0)throw conflict("STALE_REVIEW_VERSION","The review item changed; reload it");record(id,(UUID)item.get("contentVersionId"),"PRIORITY_CHANGED","Priority changed to "+priority);return detail(id);}
    @Transactional public Map<String,Object> comment(UUID id,long version,String body){if(body==null||body.isBlank())throw validation("Comment body is required");var item=one(id);if(((Number)item.get("version")).longValue()!=version)throw conflict("STALE_REVIEW_VERSION","The review item changed; reload it");var commentId=UUID.randomUUID();var now=now();jdbc.sql("INSERT INTO review_comment(id,review_item_id,content_version_id,author_id,body,created_at) VALUES(:id,:item,:version,:author,:body,:now)").param("id",commentId).param("item",id).param("version",item.get("contentVersionId")).param("author",workflow.actor()).param("body",body.trim()).param("now",now).update();jdbc.sql("UPDATE review_item SET updated_at=:now,version=version+1 WHERE id=:id AND version=:version").param("now",now).param("id",id).param("version",version).update();record(id,(UUID)item.get("contentVersionId"),"REVIEW_COMMENT_ADDED",body.trim());return detail(id);}

    private Map<String,Object> one(UUID id){var rows=jdbc.sql(PROJECTION+" WHERE ri.id=:id").param("id",id).query().listOfRows();if(rows.isEmpty())throw new DomainException(HttpStatus.NOT_FOUND,"REVIEW_ITEM_NOT_FOUND","Review item was not found");var item=rows.getFirst();if(!canReview()&&!workflow.actor().equals(item.get("authorId")))throw forbidden("Authors may only view review history for their own content");return item;}
    private List<Map<String,Object>> sourceContext(UUID version){return jdbc.sql("SELECT sr.id,sr.publisher,sr.title,sr.url,sr.accessed_at AS \"accessedAt\",sr.review_status AS \"reviewStatus\",sr.status FROM knowledge_fact_source kfs JOIN source_reference sr ON sr.id=kfs.source_reference_id WHERE kfs.knowledge_fact_version_id=:id ORDER BY sr.publisher,sr.title").param("id",version).query().listOfRows();}
    private List<Map<String,Object>> factSourceContext(UUID version){return jdbc.sql("SELECT f.id AS \"factId\",kfv.canonical_statement AS \"canonicalStatement\",f.review_status AS \"reviewStatus\",f.status,sr.id AS \"sourceId\",sr.publisher,sr.title,sr.url,sr.review_status AS \"sourceReviewStatus\",sr.status AS \"sourceStatus\" FROM question_knowledge_fact qkf JOIN knowledge_fact_version kfv ON kfv.id=qkf.knowledge_fact_version_id JOIN knowledge_fact f ON f.id=kfv.knowledge_fact_id LEFT JOIN knowledge_fact_source kfs ON kfs.knowledge_fact_version_id=kfv.id LEFT JOIN source_reference sr ON sr.id=kfs.source_reference_id WHERE qkf.question_version_id=:id ORDER BY kfv.canonical_statement,sr.publisher").param("id",version).query().listOfRows();}
    private void record(UUID item,UUID version,String action,String comment){jdbc.sql("INSERT INTO review_record(id,review_item_id,content_version_id,action,actor_id,actor_roles,comment,created_at) VALUES(:id,:item,:version,:action,:actor,:roles,:comment,:now)").param("id",UUID.randomUUID()).param("item",item).param("version",version).param("action",action).param("actor",workflow.actor()).param("roles",SecurityContextHolder.getContext().getAuthentication().getAuthorities().toString()).param("comment",comment,Types.VARCHAR).param("now",now()).update();}
    private void params(JdbcClient.StatementSpec q,String search,String type,String review,String lifecycle,UUID subject,UUID topic,UUID objective,String author,String assigned,Boolean unassigned,Boolean mine,String current,LocalDate from,LocalDate to,String priority,Boolean warnings){q.param("search",blank(search)).param("type",blank(type)).param("review",blank(review)).param("lifecycle",blank(lifecycle)).param("subject",subject).param("topic",topic).param("objective",objective).param("author",blank(author)).param("assigned",blank(assigned)).param("unassigned",Boolean.TRUE.equals(unassigned)).param("mine",Boolean.TRUE.equals(mine)).param("current",current).param("fromDate",from,Types.DATE).param("toDate",to,Types.DATE).param("priority",blank(priority)).param("warnings",Boolean.TRUE.equals(warnings));}
    private boolean isAdmin(){return SecurityContextHolder.getContext().getAuthentication().getAuthorities().stream().anyMatch(a->"ROLE_ADMIN".equals(a.getAuthority()));}
    private boolean canReview(){return SecurityContextHolder.getContext().getAuthentication().getAuthorities().stream().anyMatch(a->List.of("ROLE_CONTENT_REVIEWER","ROLE_ADMIN").contains(a.getAuthority()));}
    private String blank(String v){return v==null||v.isBlank()?null:v;}
    private OffsetDateTime now(){return OffsetDateTime.now(ZoneOffset.UTC);}
    private DomainException validation(String m){return new DomainException(HttpStatus.UNPROCESSABLE_ENTITY,"VALIDATION_ERROR",m);}
    private DomainException forbidden(String m){return new DomainException(HttpStatus.FORBIDDEN,"AUTHORIZATION_REQUIRED",m);}
    private DomainException conflict(String code,String m){return new DomainException(HttpStatus.CONFLICT,code,m);}
}
